/**
 * CcpInspectionCard - 공정그룹별 CCP 점검 카드 (v3)
 *
 * [설계 원칙]
 * ┌──────────────────────────────────────────────────────────────┐
 * │ 탭 1: 설비 기준                                               │
 * │  - 설비별 온도(°C), 압력(bar) 측정 (인라인 편집)              │
 * │  - 설비는 물리적으로 일정한 컨디션 유지                        │
 * │  - h_ccp_rows.equipment_id / equipment_name 으로 구분         │
 * │                                                              │
 * │ 탭 2: 공정 기준                                               │
 * │  - 한 배치당 유휴시간 포함 소요 시간(분)                       │
 * │  - 제품 종류에 따라 공정시간이 다름                            │
 * │  - ccp_process_groups.time_min / time_max                    │
 * │  - 설비 순서별 배치 흐름 표시                                  │
 * │                                                              │
 * │ 탭 3: 기록 입력                                               │
 * │  - 설비 선택 후 실시간 측정값 입력                             │
 * │  - 결과(PASS/FAIL), 비고 수동 입력                            │
 * └──────────────────────────────────────────────────────────────┘
 */
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from "@/components/ui/select";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs";
import { trpc } from "@/lib/trpc";
import {
  AlertCircle,
  CheckCircle2,
  ChevronDown,
  ChevronUp,
  Clock,
  ClipboardList,
  Cpu,
  Edit2,
  Save,
  Settings2,
  Thermometer,
  Timer,
  X,
} from "lucide-react";
import { useState } from "react";
import { toast } from "sonner";

interface CcpRow {
  id: number;
  instanceId: number;
  sortOrder: number;
  rowType: string;
  measuredAt?: string | null;
  tempC?: string | null;
  durationMin?: number | null;
  pressureBar?: string | null;
  result?: string | null;
  note?: string | null;
  autoGenerated?: number;
  equipmentId?: number | null;
  equipmentName?: string | null;
  heatingMin?: number | null;
  cycleTotalMin?: number | null;
}

interface CcpInstance {
  id: number;
  ccpType: string;
  processGroupId?: number | null;
  processGroupName?: string | null;
  productName?: string | null;
  status: string;
  tempMin?: number | null;
  tempMax?: number | null;
  timeMin?: number | null;
  timeMax?: number | null;
  pressureMin?: number | null;
  pressureMax?: number | null;
  rows?: CcpRow[];
}

interface CcpInspectionCardProps {
  ccp: CcpInstance;
  onRecordSaved: () => void;
}

/** 배치 총소요시간 분해 계산
 * totalTime = cycleTotalMin + (heatingMin - equipDefaultHeat)
 * equipDefaultHeat = durationMin이 있고 cycleTotalMin도 있으면 → heatingMin이 별도 있음
 */
function calcCycleBreakdown(row: CcpRow): {
  cycleTotal: number | null;
  heating: number | null;
  total: number | null;
  defaultHeat: number | null;
} {
  if (row.cycleTotalMin == null && row.heatingMin == null) {
    return { cycleTotal: null, heating: null, total: row.durationMin ?? null, defaultHeat: null };
  }
  const cycleTotal  = row.cycleTotalMin ?? null;
  const heating     = row.heatingMin ?? null;
  const total       = row.durationMin ?? null;
  // defaultHeat = cycleTotalMin + heatingMin - durationMin → 설비기본가열시간 역산
  const defaultHeat =
    cycleTotal != null && heating != null && total != null
      ? cycleTotal + heating - total
      : null;
  return { cycleTotal, heating, total, defaultHeat };
}

const ccpTypeLabel: Record<string, string> = {
  "CCP-1B": "CCP-1B 교반/증숙",
  "CCP-2B": "CCP-2B 오븐굽기",
  "CCP-4P": "CCP-4P 금속검출",
  CCP_1B: "CCP-1B 교반/증숙",
  CCP_2B: "CCP-2B 오븐굽기",
  CCP_4P: "CCP-4P 금속검출",
};

const statusColor: Record<string, string> = {
  draft: "bg-gray-100 text-gray-700 dark:bg-gray-800 dark:text-gray-400",
  submitted: "bg-blue-100 text-blue-700 dark:bg-blue-950 dark:text-blue-400",
  approved:
    "bg-green-100 text-green-700 dark:bg-green-950 dark:text-green-400",
  rejected: "bg-red-100 text-red-700 dark:bg-red-950 dark:text-red-400",
};

const statusLabel: Record<string, string> = {
  draft: "초안",
  submitted: "제출됨",
  approved: "승인됨",
  rejected: "반려됨",
};

function ResultBadge({ result }: { result?: string | null }) {
  if (!result) return <span className="text-muted-foreground">-</span>;
  if (result === "PASS")
    return (
      <Badge className="bg-green-100 text-green-700 dark:bg-green-950 dark:text-green-400">
        ✓ PASS
      </Badge>
    );
  if (result === "FAIL")
    return (
      <Badge className="bg-red-100 text-red-700 dark:bg-red-950 dark:text-red-400">
        ✗ FAIL
      </Badge>
    );
  return <Badge variant="outline">{result}</Badge>;
}

/** 설비행 인라인 편집 행 컴포넌트 */
function EquipmentRowEdit({
  row,
  ccp,
  onSaved,
}: {
  row: CcpRow;
  ccp: CcpInstance;
  onSaved: () => void;
}) {
  const [editing, setEditing] = useState(false);
  const [tempC, setTempC] = useState(row.tempC ?? "");
  const [pressureBar, setPressureBar] = useState(row.pressureBar ?? "");
  const [durationMin, setDurationMin] = useState(
    row.durationMin != null ? String(row.durationMin) : "",
  );
  const [result, setResult] = useState<"PASS" | "FAIL" | "N/A">(
    (row.result as any) ?? "PASS",
  );
  const [note, setNote] = useState(row.note ?? "");

  const is1B2B =
    ccp.ccpType === "CCP-1B" ||
    ccp.ccpType === "CCP_1B" ||
    ccp.ccpType === "CCP-2B" ||
    ccp.ccpType === "CCP_2B";

  const updateMutation = trpc.ccp.updateRow.useMutation({
    onSuccess: () => {
      toast.success(`${row.equipmentName ?? "설비"} 측정값 저장됨`);
      setEditing(false);
      onSaved();
    },
    onError: (err) => {
      toast.error(`저장 실패: ${err.message}`);
    },
  });

  const handleSave = () => {
    updateMutation.mutate({
      rowId: row.id,
      tempC: tempC || undefined,
      pressureBar: pressureBar || undefined,
      durationMin: durationMin ? Number(durationMin) : undefined,
      result,
      note: note || undefined,
      measuredAt: new Date(),
    });
  };

  if (!editing) {
    return (
      <tr className="border-b hover:bg-accent/30 group">
        <td className="p-2 text-center font-mono text-xs text-muted-foreground">
          {row.sortOrder}
        </td>
        <td className="p-2 font-medium text-sm">
          {row.equipmentName ?? `설비-${row.equipmentId}`}
        </td>
        {is1B2B && (
          <>
            <td className="p-2">
              <span
                className={
                  row.tempC == null ? "text-muted-foreground text-xs" : "font-mono text-sm"
                }
              >
                {row.tempC != null ? `${row.tempC}°C` : "미입력"}
              </span>
            </td>
            <td className="p-2">
              <span
                className={
                  row.pressureBar == null
                    ? "text-muted-foreground text-xs"
                    : "font-mono text-sm"
                }
              >
                {row.pressureBar != null ? `${row.pressureBar} bar` : "미입력"}
              </span>
            </td>
            <td className="p-2">
              <span
                className={
                  row.durationMin == null
                    ? "text-muted-foreground text-xs"
                    : "font-mono text-sm"
                }
              >
                {row.durationMin != null ? `${row.durationMin}분` : "미입력"}
              </span>
            </td>
          </>
        )}
        <td className="p-2">
          <ResultBadge result={row.result} />
        </td>
        <td className="p-2 text-muted-foreground text-xs max-w-[120px] truncate">
          {row.note ?? "-"}
        </td>
        <td className="p-2 text-muted-foreground text-xs">
          {row.measuredAt
            ? new Date(row.measuredAt).toLocaleString("ko-KR", {
                month: "2-digit",
                day: "2-digit",
                hour: "2-digit",
                minute: "2-digit",
              })
            : row.autoGenerated
              ? "자동생성"
              : "-"}
        </td>
        <td className="p-2">
          <Button
            size="sm"
            variant="ghost"
            className="h-7 w-7 p-0 opacity-0 group-hover:opacity-100 transition-opacity"
            onClick={() => setEditing(true)}
          >
            <Edit2 className="h-3.5 w-3.5" />
          </Button>
        </td>
      </tr>
    );
  }

  // 편집 모드
  return (
    <tr className="border-b bg-accent/20">
      <td className="p-2 text-center font-mono text-xs text-muted-foreground">
        {row.sortOrder}
      </td>
      <td className="p-2 font-medium text-sm text-primary">
        {row.equipmentName ?? `설비-${row.equipmentId}`}
      </td>
      {is1B2B && (
        <>
          <td className="p-1.5">
            <Input
              type="number"
              step="0.1"
              className="h-7 text-xs w-20"
              placeholder={ccp.tempMin != null ? `≥${ccp.tempMin}` : "°C"}
              value={tempC}
              onChange={(e) => setTempC(e.target.value)}
            />
          </td>
          <td className="p-1.5">
            <Input
              type="number"
              step="0.01"
              className="h-7 text-xs w-20"
              placeholder={
                ccp.pressureMin != null
                  ? `≥${(ccp.pressureMin * 10).toFixed(1)}`
                  : "bar"
              }
              value={pressureBar}
              onChange={(e) => setPressureBar(e.target.value)}
            />
          </td>
          <td className="p-1.5">
            <Input
              type="number"
              className="h-7 text-xs w-20"
              placeholder={ccp.timeMin != null ? `≥${ccp.timeMin}` : "분"}
              value={durationMin}
              onChange={(e) => setDurationMin(e.target.value)}
            />
          </td>
        </>
      )}
      <td className="p-1.5">
        <Select
          value={result}
          onValueChange={(v) => setResult(v as "PASS" | "FAIL" | "N/A")}
        >
          <SelectTrigger className="h-7 text-xs w-20">
            <SelectValue />
          </SelectTrigger>
          <SelectContent>
            <SelectItem value="PASS">✓ PASS</SelectItem>
            <SelectItem value="FAIL">✗ FAIL</SelectItem>
            <SelectItem value="N/A">N/A</SelectItem>
          </SelectContent>
        </Select>
      </td>
      <td className="p-1.5" colSpan={2}>
        <Input
          className="h-7 text-xs"
          placeholder="비고"
          value={note}
          onChange={(e) => setNote(e.target.value)}
        />
      </td>
      <td className="p-1.5">
        <div className="flex gap-1">
          <Button
            size="sm"
            className="h-7 w-7 p-0 bg-green-600 hover:bg-green-700"
            onClick={handleSave}
            disabled={updateMutation.isPending}
          >
            <Save className="h-3.5 w-3.5" />
          </Button>
          <Button
            size="sm"
            variant="ghost"
            className="h-7 w-7 p-0"
            onClick={() => setEditing(false)}
          >
            <X className="h-3.5 w-3.5" />
          </Button>
        </div>
      </td>
    </tr>
  );
}

export function CcpInspectionCard({
  ccp,
  onRecordSaved,
}: CcpInspectionCardProps) {
  const [isExpanded, setIsExpanded] = useState(false);
  const [activeTab, setActiveTab] = useState("equipment");

  // 신규 행 입력 상태
  const [newTempC, setNewTempC] = useState("");
  const [newPressureBar, setNewPressureBar] = useState("");
  const [newDurationMin, setNewDurationMin] = useState("");
  const [newResult, setNewResult] = useState<"PASS" | "FAIL" | "N/A">("PASS");
  const [newNote, setNewNote] = useState("");
  // 기록 입력 탭: 설비 선택 ("none" = 미선택)
  const [selectedEquipmentId, setSelectedEquipmentId] = useState<string>("none");

  const rows: CcpRow[] = ccp.rows ?? [];

  // 설비 그룹: equipment_id 있는 행
  const equipmentRows = rows.filter(
    (r) => r.rowType === "measurement" && r.equipmentId != null,
  );

  // 공정 기준 행: equipment 없는 측정 행 (예: CCP-4P Fe/SUS)
  const processRows = rows.filter(
    (r) => r.rowType === "measurement" && r.equipmentId == null,
  );

  // 전체 행
  const allRows = rows.filter((r) => r.rowType === "measurement");

  const createRowMutation = trpc.ccp.createRow.useMutation({
    onSuccess: () => {
      toast.success("CCP 점검 행이 저장되었습니다");
      setNewTempC("");
      setNewPressureBar("");
      setNewDurationMin("");
      setNewResult("PASS");
      setNewNote("");
      setSelectedEquipmentId("none");
      onRecordSaved();
    },
    onError: (error) => {
      toast.error(`저장 실패: ${error.message}`);
    },
  });

  const handleSaveNewRow = () => {
    if (!newResult) {
      toast.error("결과를 선택해주세요");
      return;
    }

    // 선택된 설비 정보 추출 ("none" 또는 빈 문자열은 미선택으로 처리)
    const selEq = (selectedEquipmentId && selectedEquipmentId !== "none")
      ? equipmentRows.find((r) => String(r.equipmentId) === selectedEquipmentId)
      : null;

    createRowMutation.mutate({
      instanceId: ccp.id,
      sortOrder: allRows.length + 1,
      rowType: "measurement",
      tempC: newTempC || undefined,
      pressureBar: newPressureBar || undefined,
      durationMin: newDurationMin ? Number(newDurationMin) : undefined,
      result: newResult,
      note: newNote || undefined,
      equipmentId: selEq?.equipmentId ?? undefined,
      equipmentName: selEq?.equipmentName ?? undefined,
    });
  };

  const is1B2B =
    ccp.ccpType === "CCP-1B" ||
    ccp.ccpType === "CCP_1B" ||
    ccp.ccpType === "CCP-2B" ||
    ccp.ccpType === "CCP_2B";
  const is4P = ccp.ccpType === "CCP-4P" || ccp.ccpType === "CCP_4P";

  const groupName =
    ccp.processGroupName ||
    ccpTypeLabel[ccp.ccpType] ||
    ccp.ccpType;

  const hasEquipment = equipmentRows.length > 0;

  // 완료율 계산
  const completedRows = allRows.filter(
    (r) => r.result === "PASS" || r.result === "FAIL",
  ).length;
  const completionRate =
    allRows.length > 0
      ? Math.round((completedRows / allRows.length) * 100)
      : 0;

  return (
    <div className="border rounded-lg overflow-hidden">
      {/* ── 카드 헤더 ── */}
      <div
        className="flex items-center justify-between p-4 cursor-pointer hover:bg-accent/50 transition-colors"
        onClick={() => setIsExpanded(!isExpanded)}
      >
        <div className="flex items-center gap-3">
          <div
            className={`p-2 rounded-full ${statusColor[ccp.status] ?? statusColor.draft}`}
          >
            {ccp.status === "approved" ? (
              <CheckCircle2 className="h-5 w-5" />
            ) : (
              <Clock className="h-5 w-5" />
            )}
          </div>
          <div>
            <div className="font-semibold flex items-center gap-2">
              {groupName}
              <Badge variant="outline" className="text-xs font-mono">
                {ccp.ccpType}
              </Badge>
              {completionRate > 0 && (
                <Badge
                  className={
                    completionRate === 100
                      ? "bg-green-100 text-green-700 text-xs"
                      : "bg-amber-100 text-amber-700 text-xs"
                  }
                >
                  {completionRate}%
                </Badge>
              )}
            </div>
            <div className="text-sm text-muted-foreground flex items-center gap-3 mt-0.5 flex-wrap">
              <span>상태: {statusLabel[ccp.status] ?? ccp.status}</span>
              {ccp.tempMin != null && (
                <span className="flex items-center gap-1">
                  <Thermometer className="h-3 w-3" />
                  {ccp.tempMin}
                  {ccp.tempMax ? `~${ccp.tempMax}` : ""}°C
                </span>
              )}
              {ccp.pressureMin != null && (
                <span className="flex items-center gap-1">
                  <Settings2 className="h-3 w-3" />
                  ≥{(ccp.pressureMin * 10).toFixed(1)} bar
                </span>
              )}
              {ccp.timeMin != null && (
                <span className="flex items-center gap-1">
                  <Timer className="h-3 w-3" />
                  {ccp.timeMin}
                  {ccp.timeMax ? `~${ccp.timeMax}` : ""}분
                </span>
              )}
            </div>
          </div>
        </div>
        <div className="flex items-center gap-2">
          <span className="text-sm text-muted-foreground">
            {completedRows}/{allRows.length}건
          </span>
          {isExpanded ? (
            <ChevronUp className="h-5 w-5 text-muted-foreground" />
          ) : (
            <ChevronDown className="h-5 w-5 text-muted-foreground" />
          )}
        </div>
      </div>

      {/* ── 확장 영역 ── */}
      {isExpanded && (
        <div className="border-t">
          <Tabs value={activeTab} onValueChange={setActiveTab}>
            <TabsList className="w-full justify-start rounded-none border-b bg-background px-4">
              {is1B2B && (
                <>
                  <TabsTrigger
                    value="equipment"
                    className="flex items-center gap-1.5"
                  >
                    <Cpu className="h-3.5 w-3.5" />
                    설비 기준
                    {hasEquipment && (
                      <Badge
                        variant="secondary"
                        className="ml-1 text-xs h-4 px-1"
                      >
                        {equipmentRows.length}
                      </Badge>
                    )}
                  </TabsTrigger>
                  <TabsTrigger
                    value="process"
                    className="flex items-center gap-1.5"
                  >
                    <Timer className="h-3.5 w-3.5" />
                    공정 기준
                  </TabsTrigger>
                </>
              )}
              {is4P && (
                <TabsTrigger
                  value="metal"
                  className="flex items-center gap-1.5"
                >
                  <AlertCircle className="h-3.5 w-3.5" />
                  금속검출
                </TabsTrigger>
              )}
              <TabsTrigger
                value="record"
                className="flex items-center gap-1.5"
              >
                <ClipboardList className="h-3.5 w-3.5" />
                기록 입력
              </TabsTrigger>
            </TabsList>

            {/* ── 설비 기준 탭 ── */}
            {is1B2B && (
              <TabsContent value="equipment" className="p-4 space-y-3">
                <div className="text-sm text-muted-foreground bg-muted/50 rounded-md p-3">
                  <p className="font-medium mb-1">📋 설비 기준 측정값</p>
                  <p>
                    온도(°C)와 압력(bar)은 설비가 물리적으로 일정하게 유지하는
                    기준값입니다.
                  </p>
                  {ccp.tempMin != null && (
                    <p className="mt-1 font-mono text-xs">
                      한계기준: 온도 ≥ {ccp.tempMin}°C
                      {ccp.pressureMin != null
                        ? `, 압력 ≥ ${(ccp.pressureMin * 10).toFixed(1)} bar`
                        : ""}
                      {ccp.timeMin != null ? `, 시간 ≥ ${ccp.timeMin}분` : ""}
                    </p>
                  )}
                </div>
                {equipmentRows.length === 0 ? (
                  <div className="text-center py-6 text-muted-foreground">
                    <Cpu className="h-8 w-8 mx-auto mb-2 opacity-50" />
                    <p>설비 기준 측정 기록이 없습니다</p>
                    <p className="text-xs mt-1">
                      배치 생성 시 설비 순차 할당 기록이 자동 생성됩니다
                    </p>
                  </div>
                ) : (
                  <div className="overflow-x-auto">
                    <table className="w-full text-sm">
                      <thead>
                        <tr className="border-b bg-muted/30">
                          <th className="text-center p-2 font-medium w-8">#</th>
                          <th className="text-left p-2 font-medium">설비명</th>
                          <th className="text-left p-2 font-medium">온도(°C)</th>
                          <th className="text-left p-2 font-medium">압력(bar)</th>
                          <th className="text-left p-2 font-medium">시간(분)</th>
                          <th className="text-left p-2 font-medium">판정</th>
                          <th className="text-left p-2 font-medium">비고</th>
                          <th className="text-left p-2 font-medium">측정시각</th>
                          <th className="w-8"></th>
                        </tr>
                      </thead>
                      <tbody>
                        {equipmentRows.map((row) => (
                          <EquipmentRowEdit
                            key={row.id}
                            row={row}
                            ccp={ccp}
                            onSaved={onRecordSaved}
                          />
                        ))}
                      </tbody>
                    </table>
                  </div>
                )}

                {/* 완료율 프로그레스 */}
                {equipmentRows.length > 0 && (
                  <div className="mt-2">
                    <div className="flex justify-between text-xs text-muted-foreground mb-1">
                      <span>측정 완료율</span>
                      <span>
                        {
                          equipmentRows.filter(
                            (r) => r.result === "PASS" || r.result === "FAIL",
                          ).length
                        }
                        /{equipmentRows.length}
                      </span>
                    </div>
                    <div className="h-1.5 bg-muted rounded-full overflow-hidden">
                      <div
                        className="h-full bg-green-500 rounded-full transition-all"
                        style={{
                          width: `${
                            (equipmentRows.filter(
                              (r) =>
                                r.result === "PASS" || r.result === "FAIL",
                            ).length /
                              equipmentRows.length) *
                            100
                          }%`,
                        }}
                      />
                    </div>
                  </div>
                )}
              </TabsContent>
            )}

            {/* ── 공정 기준 탭 ── */}
            {is1B2B && (
              <TabsContent value="process" className="p-4 space-y-3">
                <div className="text-sm text-muted-foreground bg-muted/50 rounded-md p-3">
                  <p className="font-medium mb-1">⏱ 공정 기준 시간</p>
                  <p className="text-xs leading-relaxed">
                    <span className="font-semibold text-foreground">총소요시간</span>은{" "}
                    <span className="text-blue-600 dark:text-blue-400">설비 사이클(유휴 포함)</span> +{" "}
                    (<span className="text-orange-600 dark:text-orange-400">제품 가열시간</span> −{" "}
                    <span className="text-muted-foreground">설비 기본가열</span>)으로 계산됩니다.
                  </p>
                  {ccp.timeMin != null && (
                    <p className="mt-1.5 font-mono text-xs bg-background rounded px-2 py-1 border inline-block">
                      공정 가열기준: {ccp.timeMin}{ccp.timeMax ? `~${ccp.timeMax}` : ""}분
                    </p>
                  )}
                </div>

                {/* 공정 정보 요약 카드 */}
                <div className="grid grid-cols-2 md:grid-cols-4 gap-3">
                  <div className="p-3 border rounded-lg bg-blue-50 dark:bg-blue-950/30">
                    <div className="text-xs text-muted-foreground mb-1">
                      공정그룹
                    </div>
                    <div className="font-semibold text-sm">
                      {ccp.processGroupName ?? "-"}
                    </div>
                  </div>
                  <div className="p-3 border rounded-lg bg-orange-50 dark:bg-orange-950/30">
                    <div className="text-xs text-muted-foreground mb-1 flex items-center gap-1">
                      <Timer className="h-3 w-3" />
                      기준시간
                    </div>
                    <div className="font-semibold text-sm">
                      {ccp.timeMin != null
                        ? `${ccp.timeMin}${ccp.timeMax ? `~${ccp.timeMax}` : ""}분`
                        : "-"}
                    </div>
                  </div>
                  <div className="p-3 border rounded-lg bg-red-50 dark:bg-red-950/30">
                    <div className="text-xs text-muted-foreground mb-1 flex items-center gap-1">
                      <Thermometer className="h-3 w-3" />
                      목표온도
                    </div>
                    <div className="font-semibold text-sm">
                      {ccp.tempMin != null
                        ? `≥${ccp.tempMin}°C`
                        : "-"}
                    </div>
                  </div>
                  <div className="p-3 border rounded-lg">
                    <div className="text-xs text-muted-foreground mb-1">
                      사용 설비
                    </div>
                    <div className="font-semibold text-sm">
                      {equipmentRows.length}대
                    </div>
                  </div>
                </div>

                {/* 설비별 배치 배정 순서 (타임라인 뷰) */}
                {equipmentRows.length > 0 && (
                  <div>
                    <div className="text-sm font-medium mb-2 flex items-center gap-1">
                      <Cpu className="h-4 w-4" />
                      배치 적용 순서 (설비 순차 배정)
                    </div>
                    <div className="relative">
                      {/* 연결선 */}
                      {equipmentRows.length > 1 && (
                        <div className="absolute left-[14px] top-8 bottom-8 w-0.5 bg-border" />
                      )}
                      <div className="space-y-2">
                        {equipmentRows.map((row, idx) => (
                          <div
                            key={row.id}
                            className="flex items-center gap-3 p-3 border rounded-lg bg-background relative z-10"
                          >
                            <div
                              className={`w-7 h-7 rounded-full flex items-center justify-center text-xs font-bold flex-shrink-0 ${
                                row.result === "PASS"
                                  ? "bg-green-100 text-green-700"
                                  : row.result === "FAIL"
                                    ? "bg-red-100 text-red-700"
                                    : "bg-primary/10 text-primary"
                              }`}
                            >
                              {idx + 1}
                            </div>
                            <div className="flex-1 min-w-0">
                              <div className="font-medium text-sm mb-1">
                                {row.equipmentName ?? `설비-${row.equipmentId}`}
                              </div>
                              {/* 총소요시간 분해 공식 표시 */}
                              {(() => {
                                const bd = calcCycleBreakdown(row);
                                if (bd.cycleTotal != null && bd.heating != null && bd.defaultHeat != null) {
                                  return (
                                    <div className="text-xs space-y-0.5">
                                      <div className="flex items-center gap-1.5 text-blue-600 dark:text-blue-400">
                                        <span className="w-1.5 h-1.5 rounded-full bg-blue-400 flex-shrink-0" />
                                        설비사이클: {bd.cycleTotal}분 <span className="text-muted-foreground">(유휴 포함)</span>
                                      </div>
                                      <div className="flex items-center gap-1.5 text-orange-600 dark:text-orange-400">
                                        <span className="w-1.5 h-1.5 rounded-full bg-orange-400 flex-shrink-0" />
                                        공정가열: {bd.heating}분
                                        {bd.defaultHeat !== bd.heating && (
                                          <span className="text-muted-foreground">(설비기본 {bd.defaultHeat}분 → +{bd.heating - bd.defaultHeat!}분)</span>
                                        )}
                                      </div>
                                      <div className="flex items-center gap-1.5 font-semibold text-green-700 dark:text-green-400 bg-green-50 dark:bg-green-950/30 rounded px-1.5 py-0.5 mt-1">
                                        <span className="w-1.5 h-1.5 rounded-full bg-green-500 flex-shrink-0" />
                                        총소요: {bd.total}분
                                        <span className="font-normal text-muted-foreground text-xs ml-1">
                                          = {bd.cycleTotal} + ({bd.heating} - {bd.defaultHeat})
                                        </span>
                                      </div>
                                    </div>
                                  );
                                }
                                return (
                                  <div className="text-xs text-muted-foreground">
                                    {bd.total != null ? `가열시간: ${bd.total}분` : "시간 미기록"}
                                  </div>
                                );
                              })()}
                              {row.tempC != null && (
                                <div className="text-xs text-muted-foreground mt-1">
                                  🌡 목표온도: {row.tempC}°C
                                </div>
                              )}
                            </div>
                            <ResultBadge result={row.result} />
                          </div>
                        ))}
                      </div>
                    </div>
                  </div>
                )}
              </TabsContent>
            )}

            {/* ── 금속검출 탭 ── */}
            {is4P && (
              <TabsContent value="metal" className="p-4 space-y-3">
                <div className="text-sm text-muted-foreground bg-muted/50 rounded-md p-3">
                  <p className="font-medium mb-1">🔍 금속검출 (CCP-4P)</p>
                  <p>
                    Fe(철) 및 SUS(스테인리스) 기준 시편으로 검출 성능을
                    확인합니다.
                  </p>
                </div>
                {allRows.length === 0 ? (
                  <div className="text-center py-6 text-muted-foreground">
                    <AlertCircle className="h-8 w-8 mx-auto mb-2 opacity-50" />
                    <p>금속검출 기록이 없습니다</p>
                  </div>
                ) : (
                  <div className="space-y-2">
                    {allRows.map((row) => (
                      <div
                        key={row.id}
                        className="flex items-center justify-between p-3 border rounded-lg"
                      >
                        <div>
                          <div className="font-medium text-sm">
                            {row.note ?? `시편 #${row.sortOrder}`}
                          </div>
                          <div className="text-xs text-muted-foreground">
                            {row.measuredAt
                              ? new Date(row.measuredAt).toLocaleString("ko-KR")
                              : row.autoGenerated
                                ? "자동생성 대기"
                                : "-"}
                          </div>
                        </div>
                        <ResultBadge result={row.result} />
                      </div>
                    ))}
                  </div>
                )}
              </TabsContent>
            )}

            {/* ── 기록 입력 탭 ── */}
            <TabsContent value="record" className="p-4 space-y-4">
              <div className="p-4 bg-accent/20 rounded-lg space-y-3">
                <h4 className="font-semibold flex items-center gap-2 text-sm">
                  <ClipboardList className="h-4 w-4" />
                  실시간 점검 기록 입력
                </h4>

                {/* 설비 선택 (1B/2B에서 설비행이 있는 경우) */}
                {is1B2B && equipmentRows.length > 0 && (
                  <div className="space-y-1.5">
                    <Label className="text-xs">설비 선택 (선택사항)</Label>
                    <Select
                      value={selectedEquipmentId}
                      onValueChange={setSelectedEquipmentId}
                    >
                      <SelectTrigger>
                        <SelectValue placeholder="설비를 선택하세요..." />
                      </SelectTrigger>
                      <SelectContent>
                        <SelectItem value="none">설비 미선택</SelectItem>
                        {equipmentRows.map((eq) => (
                          <SelectItem
                            key={eq.equipmentId ?? `eq-${eq.sortOrder}`}
                            value={eq.equipmentId != null ? String(eq.equipmentId) : `eq-${eq.sortOrder}`}
                          >
                            {eq.equipmentName ??
                              `설비-${eq.equipmentId}`}
                          </SelectItem>
                        ))}
                      </SelectContent>
                    </Select>
                  </div>
                )}

                <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-3">
                  {is1B2B && (
                    <>
                      <div className="space-y-1.5">
                        <Label className="text-xs">온도 (°C)</Label>
                        <Input
                          type="number"
                          step="0.1"
                          placeholder={
                            ccp.tempMin != null
                              ? `기준 ≥ ${ccp.tempMin}`
                              : "예: 92.5"
                          }
                          value={newTempC}
                          onChange={(e) => setNewTempC(e.target.value)}
                        />
                      </div>
                      <div className="space-y-1.5">
                        <Label className="text-xs">압력 (bar)</Label>
                        <Input
                          type="number"
                          step="0.01"
                          placeholder={
                            ccp.pressureMin != null
                              ? `기준 ≥ ${(ccp.pressureMin * 10).toFixed(1)}`
                              : "예: 2.8"
                          }
                          value={newPressureBar}
                          onChange={(e) => setNewPressureBar(e.target.value)}
                        />
                      </div>
                      <div className="space-y-1.5">
                        <Label className="text-xs">소요 시간 (분)</Label>
                        <Input
                          type="number"
                          placeholder={
                            ccp.timeMin != null
                              ? `기준 ≥ ${ccp.timeMin}`
                              : "예: 12"
                          }
                          value={newDurationMin}
                          onChange={(e) => setNewDurationMin(e.target.value)}
                        />
                      </div>
                    </>
                  )}
                  <div className="space-y-1.5">
                    <Label className="text-xs">판정 *</Label>
                    <Select
                      value={newResult}
                      onValueChange={(v) =>
                        setNewResult(v as "PASS" | "FAIL" | "N/A")
                      }
                    >
                      <SelectTrigger>
                        <SelectValue />
                      </SelectTrigger>
                      <SelectContent>
                        <SelectItem value="PASS">✓ PASS (적합)</SelectItem>
                        <SelectItem value="FAIL">✗ FAIL (부적합)</SelectItem>
                        <SelectItem value="N/A">N/A</SelectItem>
                      </SelectContent>
                    </Select>
                  </div>
                </div>
                <div className="space-y-1.5">
                  <Label className="text-xs">비고</Label>
                  <Input
                    placeholder="추가 메모 (선택)"
                    value={newNote}
                    onChange={(e) => setNewNote(e.target.value)}
                  />
                </div>
                <Button
                  onClick={handleSaveNewRow}
                  disabled={createRowMutation.isPending}
                  className="w-full"
                  size="sm"
                >
                  {createRowMutation.isPending
                    ? "저장 중..."
                    : "점검 기록 저장"}
                </Button>
              </div>

              {/* 기존 점검 기록 목록 */}
              {allRows.length > 0 && (
                <div className="space-y-2">
                  <h4 className="font-semibold text-sm">
                    점검 이력 ({allRows.length}건)
                  </h4>
                  <div className="space-y-1.5 max-h-[300px] overflow-y-auto">
                    {allRows.map((row) => (
                      <div
                        key={row.id}
                        className="p-3 border rounded-lg bg-background text-sm"
                      >
                        <div className="flex items-center justify-between mb-1">
                          <span className="font-medium">
                            {row.equipmentName ??
                              (row.note ?? `행 #${row.sortOrder}`)}
                          </span>
                          <div className="flex items-center gap-2">
                            <ResultBadge result={row.result} />
                            <span className="text-xs text-muted-foreground">
                              {row.measuredAt
                                ? new Date(row.measuredAt).toLocaleString(
                                    "ko-KR",
                                  )
                                : row.autoGenerated
                                  ? "자동생성"
                                  : "-"}
                            </span>
                          </div>
                        </div>
                        <div className="flex gap-4 text-xs text-muted-foreground">
                          {row.tempC != null && (
                            <span>🌡 {row.tempC}°C</span>
                          )}
                          {row.pressureBar != null && (
                            <span>⚙ {row.pressureBar} bar</span>
                          )}
                          {row.durationMin != null && (
                            <span>⏱ {row.durationMin}분</span>
                          )}
                          {row.note && row.equipmentId == null && (
                            <span>📝 {row.note}</span>
                          )}
                        </div>
                      </div>
                    ))}
                  </div>
                </div>
              )}
            </TabsContent>
          </Tabs>
        </div>
      )}
    </div>
  );
}
