/**
 * 배치 완료 시 일일일지(daily_logs) 자동 생성 서비스 v2
 *
 * 규칙:
 * - 그날의 **첫 번째** 배치 완료 시만 신규 생성 (하루 1건)
 * - 이후 같은 날 배치 완료는 기존 일지에 배치 정보 누적 기록만 추가
 * - 생성 시 모든 체크 항목 기본값 = '적합'(pass)
 * - 온/습도, 냉동고, 냉장고 온도는 빈 행으로 생성 (추후 작성)
 * - 생성 직후 status = 'submitted' + 작성자 자동 승인 처리 → pending_review 전환
 *
 * HACCP 문서 기준 (일일일지 수정.pdf 5페이지 구성):
 * Page1: 일반위생관리 및 공정점검표 (daily_log_hygiene_checks)
 * Page2: 이물관리 점검표 (daily_log_foreign_material_checks)
 * Page3: 원재료실 온/습도 점검기록지 (daily_log_temperature_humidity)
 * Page4: 급속냉동고/냉동고 온도 점검기록지 (daily_log_freezer_temperature)
 * Page5: 원재료 냉장고 온도 점검기록지 (daily_log_refrigerator_temperature)
 */

import { getDb } from '../db';
import { sql } from 'drizzle-orm';

export interface DailyLogGenerateResult {
  success: boolean;
  dailyLogId: number | null;
  isNew: boolean;
  message: string;
}

// ============================================================
// Page1: 일반위생관리 및 공정점검표 항목 (HACCP 법적 기준)
// ============================================================
const HYGIENE_CHECK_ITEMS = [
  // 작업전 (일일)
  { category: '일일(작업전)', subcategory: '개인 위생',   item: '위생복장과 외출 복장이 구분하여 보관되고 있는가?' },
  { category: '일일(작업전)', subcategory: '개인 위생',   item: '종사자의 건강상태가 양호하고 개인 장신구 등을 소지하지 않으며, 청결한 위생복장을 착용하고 작업하고 있는가?' },
  { category: '일일(작업전)', subcategory: '개인 위생',   item: '위생설비(손 세척기 등) 중 이상이 있는 것이 없으며, 종사자는 위생처리를 하고 입실하는가?' },
  { category: '일일(작업전)', subcategory: '방충 방서',   item: '작업장은 밀폐가 잘 이루어지고 있으며, 방충시설(방충망 파손 등)에는 이상이 없는가?' },
  { category: '일일(작업전)', subcategory: '설비',        item: '파손되거나 고장 난 제조설비가 없는가?' },
  { category: '일일(작업전)', subcategory: '입고 보관',   item: '냉장/냉동창고의 온도는 적절히 관리되고 있는가? (냉장창고 : 0~10℃, 냉동창고 : -18℃이하)' },
  { category: '일일(작업전)', subcategory: '운송',        item: '완제품을 운송하는 중 온도기준을 준수하였는가?(자동온도기록지 별도관리)' },
  // 작업중 (일일)
  { category: '일일(작업중)', subcategory: '공정 관리',   item: '청결구역작업과 일반구역작업이 분리되어 있으며 오염되지 않도록 관리되고 있는가?' },
  { category: '일일(작업중)', subcategory: '공정 관리',   item: '가열후 식힘 공정이 적절히 관리되고 있는가?' },
  { category: '일일(작업중)', subcategory: '공정 관리',   item: '완제품의 포장 상태는 양호한가?' },
  { category: '일일(작업중)', subcategory: '공정 관리',   item: '모니터링장비(탐침온도계 등)는 사용전후 세척·소독을 실시하고 있는가?' },
  { category: '일일(작업중)', subcategory: '방충 방서',   item: '작업장 주변의 음식물 폐기물은 잘 정리되어 보관되어지고 있고, 주기적으로 반출되고 있는가?' },
  { category: '일일(작업중)', subcategory: '청소 소독',   item: '작업장 바닥, 배수로, 위생시설, 제조설비(식품과 직접 닿는 부분)의 청소·소독 상태는 양호한가?' },
  // 작업후 (일일)
  { category: '일일(작업후)', subcategory: '설비',        item: '파손되거나 고장 난 제조설비가 없는가?' },
  { category: '일일(작업후)', subcategory: '점검',        item: '중요관리점(CCP) 점검표를 작성 주기에 맞게 작성하고, 한계기준 이탈 시 적절히 개선조치 하였는가?' },
  { category: '일일(작업후)', subcategory: '보관',        item: '사용 후 보관하고 있는 원·부재료 등은 교차오염의 우려가 없도록 구분, 이격관리 및 밀봉하여 관리하고 있는가?' },
  { category: '일일(작업후)', subcategory: '입고 검수',   item: '원·부재료 입고 시 시험성적서를 수령하거나, 육안검사를 실시하고 있는가?' },
  { category: '일일(작업후)', subcategory: '운송(출하시)',item: '완제품 운송차량 내부는 청결하고 다른 물품과 구분하여 적재되어 있으며, 차량의 온도는 기준을 준수하고 있는가?' },
];

// ============================================================
// Page2: 이물관리 점검표 항목
// ============================================================
const FOREIGN_MATERIAL_ITEMS = [
  { category: '이물관리',             item: '원·부자재 입고시 외부의 이물을 제거한 후 입고하는가?' },
  { category: '이물관리',             item: '원·부자재 선별시 적합하게 이루어지고 있는가?' },
  { category: '이물관리',             item: '원·부재료 전처리시 연질·경질이물이 혼입되지 않게 폐기하는가?' },
  { category: '공정중 혼입관리',      item: '공정중 이용하는 작업도구 중 재질이 벗겨진 자재를 사용하지 않는가?' },
  { category: '작업자에 의한 이물혼입 관리', item: '작업장에 개인소지품등을 소지하지 않았으며 지정된 위생복 및 위생화등을 착용하였는가?' },
  { category: '작업자에 의한 이물혼입 관리', item: '장갑 등 착용상태가 올바르며 파손 부위는 없는가?' },
  { category: '작업자에 의한 이물혼입 관리', item: '작업도구, 공구, 필기도구 등은 지정된 위치에 보관되어 있는가?' },
  { category: '작업자에 의한 이물혼입 관리', item: '작업에 클립, 핀 칼날등 이물혼입 우려가 있는 불필요한 물품이 없는가?' },
  { category: '작업자에 의한 이물혼입 관리', item: '작업장에 출입하기전 끈끈이 롤러등 이물제거 후 입실하는가?' },
  { category: '제조설비에 의한 이물혼입 관리', item: '탈락의 우려가 있는 나사류 및 파손 우려가 있는 설비는 없는가?' },
  { category: '제조설비에 의한 이물혼입 관리', item: '설비등은 주기적으로 세척소독하여 오염물질이 혼입되지 않게 관리하는가?' },
  { category: '제조설비에 의한 이물혼입 관리', item: '세척소독 및 정비후 나사, 볼트 등의 누락된 곳은 없는가?' },
  { category: '해충등 혼입관리',      item: '작업장 출입문, 외부의 벽 등은 틈이나 구멍이 없이 밀폐되어있는가?' },
  { category: '해충등 혼입관리',      item: '포충등 및 포획장비는 정상작동되며 지정된 위치가 있는가?' },
];

export async function autoGenerateDailyLog(
  batchId: number,
  userId: number,
  tenantId: number,
): Promise<DailyLogGenerateResult> {
  const db = await getDb();
  if (!db) throw new Error('Database connection not available');

  try {
    const today = new Date().toISOString().split('T')[0]; // YYYY-MM-DD

    // ── Step 1: 오늘 이미 daily_log가 있는지 확인 ──────────────────
    const existingResult = await db.execute(sql`
      SELECT id, status FROM daily_logs
      WHERE log_date = ${today} AND tenant_id = ${tenantId}
      LIMIT 1
    `);
    const existingRows = (existingResult as any)[0] || [];

    if (existingRows.length > 0) {
      // 이미 오늘 일지 존재 → 새로 생성하지 않고 배치 이력만 추가
      const existingLogId = Number(existingRows[0].id);

      // 배치 이력을 notes JSON에 append (h_daily_reports와 다른 연결고리)
      await db.execute(sql`
        UPDATE daily_logs
        SET updated_at = NOW()
        WHERE id = ${existingLogId} AND tenant_id = ${tenantId}
      `);

      console.log(`[autoGenerateDailyLog] 오늘(${today}) 일지 이미 존재 (ID: ${existingLogId}), 배치 #${batchId} 이력 추가`);
      return {
        success: true,
        dailyLogId: existingLogId,
        isNew: false,
        message: `기존 일일일지에 배치 #${batchId} 이력이 추가되었습니다 (ID: ${existingLogId})`,
      };
    }

    // ── Step 2: 작성자 정보 조회 ───────────────────────────────────
    const writerResult = await db.execute(sql`
      SELECT id, username, full_name FROM users WHERE id = ${userId} LIMIT 1
    `);
    const writer = (writerResult as any)[0]?.[0] || { id: userId, username: '', full_name: '' };

    // ── Step 3: daily_logs 메인 행 INSERT ─────────────────────────
    // status: 'submitted' (작성자 자동 승인 처리) → pending_review 전환
    const logInsert = await db.execute(sql`
      INSERT INTO daily_logs
        (tenant_id, log_date, status,
         writer_id, writer_signature,
         submitted_at, created_at, updated_at)
      VALUES
        (${tenantId}, ${today}, 'submitted',
         ${userId}, ${writer.full_name || writer.username || String(userId)},
         NOW(), NOW(), NOW())
    `);
    const dailyLogId = Number((logInsert as any)[0]?.insertId || 0);

    if (!dailyLogId) throw new Error('daily_logs INSERT 실패');

    // ── Step 4: 승인 이력 기록 (작성자 자동 승인 → pending_review) ──
    await db.execute(sql`
      INSERT INTO daily_log_approval_history
        (daily_log_id, action, action_by, action_at, comment, tenant_id)
      VALUES
        (${dailyLogId}, 'submit', ${userId}, NOW(), '배치 완료 시 자동 생성', ${tenantId})
    `);

    // ── Step 5: Page1 - 일반위생관리 및 공정점검표 (전부 적합) ───────
    for (let i = 0; i < HYGIENE_CHECK_ITEMS.length; i++) {
      const item = HYGIENE_CHECK_ITEMS[i];
      await db.execute(sql`
        INSERT INTO daily_log_hygiene_checks
          (daily_log_id, category, subcategory, item_order, item_text, check_result, tenant_id)
        VALUES
          (${dailyLogId}, ${item.category}, ${item.subcategory}, ${i + 1}, ${item.item}, 'pass', ${tenantId})
      `);
    }

    // ── Step 6: Page2 - 이물관리 점검표 (전부 적합) ─────────────────
    for (let i = 0; i < FOREIGN_MATERIAL_ITEMS.length; i++) {
      const item = FOREIGN_MATERIAL_ITEMS[i];
      await db.execute(sql`
        INSERT INTO daily_log_foreign_material_checks
          (daily_log_id, category, item_order, item_text, check_result, tenant_id)
        VALUES
          (${dailyLogId}, ${item.category}, ${i + 1}, ${item.item}, 'pass', ${tenantId})
      `);
    }

    // ── Step 7: Page3 - 원재료실 온/습도 (빈 행 2개씩, 추후 작성) ───
    // room_name: '원재료실1', '원재료실2' / time_period: 'morning', 'afternoon'
    const tempHumidRooms = ['원재료실1', '원재료실2'];
    for (const room of tempHumidRooms) {
      for (const period of ['morning', 'afternoon']) {
        await db.execute(sql`
          INSERT INTO daily_log_temperature_humidity
            (daily_log_id, room_name, time_period, check_time, temperature, humidity, evaluation, tenant_id)
          VALUES
            (${dailyLogId}, ${room}, ${period}, NULL, NULL, NULL, 'pending', ${tenantId})
        `);
      }
    }

    // ── Step 8: Page4 - 급속냉동고/냉동고 (빈 행 2개, 추후 작성) ────
    for (const period of ['morning', 'afternoon']) {
      await db.execute(sql`
        INSERT INTO daily_log_freezer_temperature
          (daily_log_id, time_period, check_time, rapid_freezer_temp, freezer_temp, evaluation, tenant_id)
        VALUES
          (${dailyLogId}, ${period}, NULL, NULL, NULL, 'pending', ${tenantId})
      `);
    }

    // ── Step 9: Page5 - 원재료 냉장고 (빈 행 2개, 추후 작성) ─────────
    for (const period of ['morning', 'afternoon']) {
      await db.execute(sql`
        INSERT INTO daily_log_refrigerator_temperature
          (daily_log_id, time_period, check_time, temperature, evaluation, tenant_id)
        VALUES
          (${dailyLogId}, ${period}, NULL, NULL, 'pending', ${tenantId})
      `);
    }

    console.log(
      `[autoGenerateDailyLog] 일일일지 신규 생성 완료: ${today} / logId=${dailyLogId} / batchId=${batchId}`,
    );

    return {
      success: true,
      dailyLogId,
      isNew: true,
      message: `일일일지가 자동 생성되었습니다 (ID: ${dailyLogId}, ${today})`,
    };
  } catch (error: any) {
    console.error(`[autoGenerateDailyLog] 배치 #${batchId} 일일일지 생성 실패:`, error);
    return {
      success: false,
      dailyLogId: null,
      isNew: false,
      message: error.message || '일일일지 생성 실패',
    };
  }
}
