/**
 * 배치 CCP 자동 생성 기능 통합 테스트
 * 
 * 배치 생성 시 CCP 자동 생성 기능 검증
 */

import { describe, it, expect, beforeAll } from "vitest";
import * as db from "./db";

describe("배치 CCP 자동 생성 기능 테스트", () => {
  let testProductId: number;
  let testBatchId: number;
  let testUserId: number;

  beforeAll(async () => {
    // 테스트용 사용자 생성
    await db.upsertUser({
      email: "batch-test@test.com",
      passwordHash: "test",
      name: "배치 테스트 사용자",
      role: "worker"
    });
    const user = await db.getUserByEmail("batch-test@test.com");
    testUserId = user!.id;

    // 테스트용 제품 생성 (설기떡 - CCP-1B, CCP-4P 자동 생성 예상)
    const timestamp = Date.now();
    testProductId = await db.createProduct({
      productCode: `P-BATCH-${timestamp}`,
      productName: "백설기",
      productType: "떡류",
      unit: "kg",
      shelfLifeDays: 7,
      storageCondition: "냉장",
      isActive: 1,
      createdBy: testUserId
    });
  });

  it("1. 배치 생성 시 CCP가 자동으로 생성되어야 함", async () => {
    // 배치 생성
    testBatchId = await db.createBatch({
      siteId: 1,
      batchCode: `BATCH-TEST-${Date.now()}`,
      productId: testProductId,
      plannedQuantity: "50.00",
      plannedDate: new Date(),
      status: "planned",
      createdBy: testUserId
    });

    expect(testBatchId).toBeGreaterThan(0);

    // CCP 자동 생성 함수 호출
    const { autoCreateCcpInstancesForBatch } = await import("./services/ccp-batch");
    const product = await db.getProductById(testProductId);
    const workDate = new Date().toISOString().split('T')[0];
    
    const result = await autoCreateCcpInstancesForBatch({
      siteId: 1,
      workDate,
      batchId: testBatchId,
      productName: product!.productName,
      createdBy: testUserId
    });

    // CCP가 생성되었는지 확인 (백설기 → CCP-1B, CCP-4P)
    expect(result.instanceIds.length).toBeGreaterThan(0);

    // 배치에 연결된 CCP 조회
    const ccpInstances = await db.getCcpInstancesByBatchId(testBatchId);
    expect(ccpInstances.length).toBeGreaterThan(0);

    // CCP 타입 확인
    const ccpTypes = ccpInstances.map((instance: any) => instance.ccpType);
    expect(ccpTypes).toContain("CCP_4P"); // 금속검출은 모든 제품에 적용
    expect(ccpTypes).toContain("CCP_1B"); // 설기떡 → 증숙

    // CCP 행이 자동 생성되었는지 확인
    for (const instance of ccpInstances) {
      const rows = await db.getCcpRowsByInstanceId(instance.id);
      expect(rows.length).toBeGreaterThan(0);
      
      // autoGenerated 필드 확인
      const autoGeneratedRows = rows.filter((row: any) => row.autoGenerated === 1);
      expect(autoGeneratedRows.length).toBeGreaterThan(0);
    }
  });

  it("2. 제품명에 따라 적절한 CCP 타입이 생성되어야 함", async () => {
    // 다른 제품 생성 (김치 → CCP-3B 냉각)
    const timestamp = Date.now();
    const kimchiProductId = await db.createProduct({
      productCode: `P-KIMCHI-${timestamp}`,
      productName: "배추김치",
      productType: "김치류",
      unit: "kg",
      shelfLifeDays: 30,
      storageCondition: "냉장",
      isActive: 1,
      createdBy: testUserId
    });

    // 배치 생성
    const kimchiBatchId = await db.createBatch({
      siteId: 1,
      batchCode: `BATCH-KIMCHI-${timestamp}`,
      productId: kimchiProductId,
      plannedQuantity: "100.00",
      plannedDate: new Date(),
      status: "planned",
      createdBy: testUserId
    });

    // CCP 자동 생성
    const { autoCreateCcpInstancesForBatch } = await import("./services/ccp-batch");
    const product = await db.getProductById(kimchiProductId);
    const workDate = new Date().toISOString().split('T')[0];
    
    const result = await autoCreateCcpInstancesForBatch({
      siteId: 1,
      workDate,
      batchId: kimchiBatchId,
      productName: product!.productName,
      createdBy: testUserId
    });

    expect(result.instanceIds.length).toBeGreaterThan(0);

    // CCP 타입 확인
    const ccpInstances = await db.getCcpInstancesByBatchId(kimchiBatchId);
    const ccpTypes = ccpInstances.map((instance: any) => instance.ccpType);
    
    // 김치는 냉각 공정이 있으므로 CCP-3B가 생성되어야 함
    expect(ccpTypes).toContain("CCP_4P"); // 금속검출은 모든 제품에 적용
    expect(ccpTypes).toContain("CCP_3B"); // 김치 → 냉각
  });

  it("3. CCP 생성 실패 시에도 에러가 발생하지 않아야 함", async () => {
    // 존재하지 않는 제품으로 CCP 생성 시도
    const { autoCreateCcpInstancesForBatch } = await import("./services/ccp-batch");
    const workDate = new Date().toISOString().split('T')[0];
    
    // 에러가 발생하지 않고 빈 결과를 반환해야 함
    const result = await autoCreateCcpInstancesForBatch({
      siteId: 1,
      workDate,
      batchId: 999999, // 존재하지 않는 배치
      productName: "존재하지 않는 제품",
      createdBy: testUserId
    });

    // 실패해도 에러가 발생하지 않음
    expect(result.instanceIds).toBeDefined();
  });
});
