/**
 * 체크리스트 도메인 라우터 매핑 — _root.ts 분해 (2026-04-19)
 */
import {
  checklistRouter,
  checklistStatsRouter,
  checklistTemplateRouter,
  equipmentRouter,
  checklistDashboardRouter,
  waterQualityTestRouter,
  airCompressorRouter,
  validityEvaluationRouter,
  personalHygieneCheckRouter,
  waterUsageCheckRouter,
  equipmentCleaningRecordRouter,
  foreignMaterialRecordRouter,
  refrigerationCheckRouter,
  packagingStorageRecordRouter,
  qualityIssueRecordRouter,
  capaRecordRouter,
  genericChecklistRouter,
  calibrationRouter,
  checklistInstanceRouter,
  checklistScheduleRouter,
  healthCertificateRouter,
  hygieneRouter,
  pestControlRouter,
  qualityChecklistRouter,
  scanChecklistRouter,
} from "../checklist";

export const checklistRouterMap = {
  checklist: checklistRouter,
  checklistTemplate: checklistTemplateRouter,
  checklistStats: checklistStatsRouter,
  checklistDashboard: checklistDashboardRouter,
  checklistSchedule: checklistScheduleRouter,
  checklistInstance: checklistInstanceRouter,
  equipment: equipmentRouter,
  qualityChecklist: qualityChecklistRouter,
  scanChecklist: scanChecklistRouter,
  calibration: calibrationRouter,
  healthCertificate: healthCertificateRouter,
  hygiene: hygieneRouter,
  pestControl: pestControlRouter,
  waterQualityTest: waterQualityTestRouter,
  airCompressor: airCompressorRouter,
  validityEvaluation: validityEvaluationRouter,
  personalHygieneCheck: personalHygieneCheckRouter,
  waterUsageCheck: waterUsageCheckRouter,
  equipmentCleaningRecord: equipmentCleaningRecordRouter,
  foreignMaterialRecord: foreignMaterialRecordRouter,
  refrigerationCheck: refrigerationCheckRouter,
  packagingStorageRecord: packagingStorageRecordRouter,
  qualityIssueRecord: qualityIssueRecordRouter,
  capaRecord: capaRecordRouter,
  genericChecklist: genericChecklistRouter,
} as const;
