/**
 * 생산 도메인 라우터 매핑 — _root.ts 분해 (2026-04-19)
 */
import {
  batchRouter,
  batchApprovalRouter,
  batchCostRouter,
  batchScheduleRouter,
  costAnalysisRouter,
  costSavingAIRouter,
  dailyReportRouter,
  intermediateRouter,
  mfReportRouter,
  productRouter,
  productionRouter,
  productionDashboardRouter,
  productionPredictionRouter,
  productionScheduleRouter,
  recipeRouter,
  recipeApprovalRouter,
  recipeManagementRouter,
  scheduleOptimizationRouter,
  aiProductionParserRouter,
  dailyLogRouter,
  weeklyLogsRouter,
  monthlyLogsRouter,
  yearlyLogsRouter,
} from "../production";

export const productionRouterMap = {
  batch: batchRouter,
  batchApproval: batchApprovalRouter,
  batchCost: batchCostRouter,
  batchSchedule: batchScheduleRouter,
  product: productRouter,
  recipe: recipeRouter,
  recipeManagement: recipeManagementRouter,
  recipeApproval: recipeApprovalRouter,
  costAnalysis: costAnalysisRouter,
  costSavingAI: costSavingAIRouter,
  intermediate: intermediateRouter,
  mfReport: mfReportRouter,
  production: productionRouter,
  productionSchedule: productionScheduleRouter,
  productionDashboard: productionDashboardRouter,
  productionPrediction: productionPredictionRouter,
  scheduleOptimization: scheduleOptimizationRouter,
  aiProductionParser: aiProductionParserRouter,
  dailyReport: dailyReportRouter,
  dailyLog: dailyLogRouter,
  weeklyLog: weeklyLogsRouter,
  monthlyLog: monthlyLogsRouter,
  yearlyLog: yearlyLogsRouter,
} as const;
