/**
 * 시스템 도메인 라우터 매핑 — _root.ts 분해 (2026-04-19)
 */
import {
  approvalRouter,
  auditLogRouter,
  excelRouter,
  excelImportRouter,
  favoritesRouter,
  notificationRouter,
  notificationSettingsRouter,
  reportRouter,
  schedulerRouter,
  tenantRouter,
  uploadHistoryRouter,
  userRouter,
  supportRouter,
  subscriptionRouter,
  subscriptionPublicRouter,
  delegationRouter,
  workflowRouter,
  simplifiedImportRouter,
  adminRouter,
  adminEmployeeRouter,
  auditLogsRouter,
  auditReportRouter,
  bannerRouter,
  boardRouter,
  documentApprovalRouter,
  documentPrintRouter,
  employeeRouter,
  organizationRouter,
  reportsRouter,
  serverMonitorRouter,
  trainingRouter,
  dailyTrainingRouter,
  tenantsRouter,
  iotRouter,
  industryRouter,
  tenantIsolationAuditRouter,
} from "../system";

export const systemRouterMap = {
  admin: adminRouter,
  adminEmployee: adminEmployeeRouter,
  user: userRouter,
  tenant: tenantRouter,
  tenants: tenantsRouter,
  approval: approvalRouter,
  notification: notificationRouter,
  notificationSettings: notificationSettingsRouter,
  report: reportRouter,
  auditLog: auditLogRouter,
  auditLogs: auditLogsRouter,
  auditReport: auditReportRouter,
  excel: excelRouter,
  excelImport: excelImportRouter,
  simplifiedImport: simplifiedImportRouter,
  support: supportRouter,
  subscription: subscriptionRouter,
  subscriptionPublic: subscriptionPublicRouter,
  delegation: delegationRouter,
  workflow: workflowRouter,
  favorites: favoritesRouter,
  scheduler: schedulerRouter,
  uploadHistory: uploadHistoryRouter,
  banner: bannerRouter,
  board: boardRouter,
  documentApproval: documentApprovalRouter,
  documentPrint: documentPrintRouter,
  employee: employeeRouter,
  organization: organizationRouter,
  reports: reportsRouter,
  serverMonitor: serverMonitorRouter,
  training: trainingRouter,
  dailyTraining: dailyTrainingRouter,
  iot: iotRouter,
  industry: industryRouter,
  tenantIsolationAudit: tenantIsolationAuditRouter, // PR-W (2026-05-21)
} as const;
