import { Button } from "@/components/ui/button";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { trpc } from "@/lib/trpc";
import { BarChart3, Calendar, Loader2, TrendingUp } from "lucide-react";
import { useMemo, useState } from "react";
import {
  Bar,
  BarChart,
  CartesianGrid,
  Legend,
  Line,
  LineChart,
  ResponsiveContainer,
  Tooltip,
  XAxis,
  YAxis,
} from "recharts";

type DateRange = "7days" | "30days" | "90days" | "all";

export default function CcpStats() {
  const [dateRange, setDateRange] = useState<DateRange>("30days");

  const { startDate, endDate } = useMemo(() => {
    const end = new Date();
    const start = new Date();

    switch (dateRange) {
      case "7days":
        start.setDate(end.getDate() - 7);
        break;
      case "30days":
        start.setDate(end.getDate() - 30);
        break;
      case "90days":
        start.setDate(end.getDate() - 90);
        break;
      case "all":
        return { startDate: undefined, endDate: undefined };
    }

    return {
      startDate: start.toISOString().split("T")[0],
      endDate: end.toISOString().split("T")[0],
    };
  }, [dateRange]);

  const { data: stats, isLoading, error } = trpc.ccp.getStats.useQuery(
    { startDate, endDate },
    { retry: 1, retryDelay: 1000 }
  );

  if (error) {
    return (
      <div className="flex flex-col gap-3">
        <div>
          <h1 className="text-lg font-bold tracking-tight">CCP 자동 생성 통계</h1>
          <p className="text-muted-foreground text-sm">통계 데이터를 불러올 수 없습니다.</p>
        </div>
        <div className="text-center py-6 text-muted-foreground">
          <p className="text-sm">CCP 데이터가 아직 없거나 서버와 연결할 수 없습니다.</p>
          <p className="text-xs mt-2 text-gray-400">{error.message}</p>
        </div>
      </div>
    );
  }

  return (
      <div className="flex flex-col gap-3">
        {/* 헤더 */}
        <div className="flex items-center justify-between">
          <div>
            <h1 className="text-lg font-bold tracking-tight">CCP 자동 생성 통계</h1>
            <p className="text-muted-foreground text-sm">
              제품별 CCP 자동 생성 현황 및 추이를 확인합니다
            </p>
          </div>
          <div className="flex items-center gap-2">
            <Select value={dateRange} onValueChange={(value) => setDateRange(value as DateRange)}>
              <SelectTrigger className="w-[160px] h-9">
                <Calendar className="mr-1.5 h-3.5 w-3.5" />
                <SelectValue />
              </SelectTrigger>
              <SelectContent>
                <SelectItem value="7days">최근 7일</SelectItem>
                <SelectItem value="30days">최근 30일</SelectItem>
                <SelectItem value="90days">최근 90일</SelectItem>
                <SelectItem value="all">전체 기간</SelectItem>
              </SelectContent>
            </Select>
          </div>
        </div>

        {isLoading ? (
          <div className="flex items-center justify-center py-6">
            <Loader2 className="h-6 w-6 animate-spin text-muted-foreground" />
          </div>
        ) : !stats ? (
          <div className="text-center py-6 text-muted-foreground">
            통계 데이터를 불러올 수 없습니다
          </div>
        ) : (
          <>
            {/* 전체 통계 카드 */}
            <div className="grid grid-cols-2 md:grid-cols-4 gap-2">
              <Card>
                <CardContent className="p-3">
                  <p className="text-xs text-muted-foreground">전체 배치</p>
                  <p className="text-xl font-bold mt-1">{stats.overview.totalBatches}</p>
                </CardContent>
              </Card>
              <Card>
                <CardContent className="p-3">
                  <p className="text-xs text-muted-foreground">CCP 인스턴스</p>
                  <p className="text-xl font-bold mt-1">{stats.overview.totalCcpInstances}</p>
                </CardContent>
              </Card>
              <Card>
                <CardContent className="p-3">
                  <p className="text-xs text-muted-foreground">자동 생성 행</p>
                  <p className="text-xl font-bold mt-1">{stats.overview.autoGeneratedCount}</p>
                </CardContent>
              </Card>
              <Card>
                <CardContent className="p-3">
                  <p className="text-xs text-muted-foreground">자동 생성 비율</p>
                  <p className="text-xl font-bold mt-1 flex items-center gap-1">
                    {stats.overview.autoGeneratedRate.toFixed(1)}%
                    <TrendingUp className="h-4 w-4 text-green-500" />
                  </p>
                </CardContent>
              </Card>
            </div>

            {/* 제품별 통계 */}
            <Card>
              <CardHeader className="pb-2 pt-3 px-4">
                <CardTitle className="flex items-center gap-2 text-sm">
                  <BarChart3 className="h-4 w-4" />
                  제품별 CCP 생성 현황
                </CardTitle>
              </CardHeader>
              <CardContent className="px-4 pb-3">
                {stats.byProduct.length === 0 ? (
                  <div className="text-center py-4 text-muted-foreground text-sm">
                    데이터가 없습니다
                  </div>
                ) : (
                  <ResponsiveContainer width="100%" height={220}>
                    <BarChart data={stats.byProduct}>
                      <CartesianGrid strokeDasharray="3 3" />
                      <XAxis dataKey="productName" />
                      <YAxis />
                      <Tooltip />
                      <Legend />
                      <Bar dataKey="ccpInstanceCount" name="CCP 인스턴스" fill="#3b82f6" />
                      <Bar dataKey="autoGeneratedCount" name="자동 생성 행" fill="#10b981" />
                    </BarChart>
                  </ResponsiveContainer>
                )}
              </CardContent>
            </Card>

            {/* CCP 타입별 통계 */}
            <Card>
              <CardHeader className="pb-2 pt-3 px-4">
                <CardTitle className="text-sm">CCP 타입별 생성 현황</CardTitle>
              </CardHeader>
              <CardContent className="px-4 pb-3">
                {stats.byCcpType.length === 0 ? (
                  <div className="text-center py-4 text-muted-foreground text-sm">
                    데이터가 없습니다
                  </div>
                ) : (
                  <ResponsiveContainer width="100%" height={220}>
                    <BarChart data={stats.byCcpType}>
                      <CartesianGrid strokeDasharray="3 3" />
                      <XAxis dataKey="ccpType" />
                      <YAxis />
                      <Tooltip />
                      <Legend />
                      <Bar dataKey="instanceCount" name="CCP 인스턴스" fill="#8b5cf6" />
                      <Bar dataKey="autoGeneratedCount" name="자동 생성 행" fill="#10b981" />
                    </BarChart>
                  </ResponsiveContainer>
                )}
              </CardContent>
            </Card>

            {/* 추이 차트 */}
            {stats.trend.length > 0 && (
              <Card>
                <CardHeader className="pb-2 pt-3 px-4">
                  <CardTitle className="text-sm">CCP 생성 추이</CardTitle>
                </CardHeader>
                <CardContent className="px-4 pb-3">
                  <ResponsiveContainer width="100%" height={220}>
                    <LineChart data={stats.trend}>
                      <CartesianGrid strokeDasharray="3 3" />
                      <XAxis dataKey="date" />
                      <YAxis />
                      <Tooltip />
                      <Legend />
                      <Line
                        type="monotone"
                        dataKey="batchCount"
                        name="배치 수"
                        stroke="#3b82f6"
                        strokeWidth={2}
                      />
                      <Line
                        type="monotone"
                        dataKey="ccpInstanceCount"
                        name="CCP 인스턴스"
                        stroke="#8b5cf6"
                        strokeWidth={2}
                      />
                      <Line
                        type="monotone"
                        dataKey="autoGeneratedCount"
                        name="자동 생성 행"
                        stroke="#10b981"
                        strokeWidth={2}
                      />
                    </LineChart>
                  </ResponsiveContainer>
                </CardContent>
              </Card>
            )}

            {/* 제품별 상세 테이블 */}
            <Card>
              <CardHeader className="pb-2 pt-3 px-4">
                <CardTitle className="text-sm">제품별 상세 통계</CardTitle>
              </CardHeader>
              <CardContent className="px-4 pb-3">
                {stats.byProduct.length === 0 ? (
                  <div className="text-center py-4 text-muted-foreground text-sm">
                    데이터가 없습니다
                  </div>
                ) : (
                  <div className="overflow-x-auto">
                    <table className="w-full">
                      <thead>
                        <tr className="border-b">
                          <th className="text-left p-2 font-medium text-xs">제품명</th>
                          <th className="text-right p-2 font-medium text-xs">배치 수</th>
                          <th className="text-right p-2 font-medium text-xs">CCP 인스턴스</th>
                          <th className="text-right p-2 font-medium text-xs">자동 생성 행</th>
                          <th className="text-right p-2 font-medium text-xs">자동 생성 비율</th>
                        </tr>
                      </thead>
                      <tbody>
                        {stats.byProduct.map((product: any) => {
                          const rate =
                            product.ccpInstanceCount > 0
                              ? ((product.autoGeneratedCount / product.ccpInstanceCount) * 100).toFixed(1)
                              : "0.0";
                          return (
                            <tr key={product.productId} className="border-b hover:bg-accent/50">
                              <td className="p-2 text-sm">{product.productName}</td>
                              <td className="text-right p-2 text-sm">{product.batchCount}</td>
                              <td className="text-right p-2 text-sm">{product.ccpInstanceCount}</td>
                              <td className="text-right p-2 text-sm">{product.autoGeneratedCount}</td>
                              <td className="text-right p-2 text-sm">
                                <span className="font-medium text-green-600">{rate}%</span>
                              </td>
                            </tr>
                          );
                        })}
                      </tbody>
                    </table>
                  </div>
                )}
              </CardContent>
            </Card>
          </>
        )}
      </div>
  );
}
