import { Button } from "@/components/ui/button";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { trpc } from "@/lib/trpc";
import { BarChart3, Calendar, Loader2, TrendingUp } from "lucide-react";
import { useMemo, useState } from "react";
import {
  Bar,
  BarChart,
  CartesianGrid,
  Legend,
  Line,
  LineChart,
  ResponsiveContainer,
  Tooltip,
  XAxis,
  YAxis,
} from "recharts";

type DateRange = "7days" | "30days" | "90days" | "all";

export default function CcpStats() {
  const [dateRange, setDateRange] = useState<DateRange>("30days");

  const { startDate, endDate } = useMemo(() => {
    const end = new Date();
    const start = new Date();

    switch (dateRange) {
      case "7days":
        start.setDate(end.getDate() - 7);
        break;
      case "30days":
        start.setDate(end.getDate() - 30);
        break;
      case "90days":
        start.setDate(end.getDate() - 90);
        break;
      case "all":
        return { startDate: undefined, endDate: undefined };
    }

    return {
      startDate: start.toISOString().split("T")[0],
      endDate: end.toISOString().split("T")[0],
    };
  }, [dateRange]);

  const { data: stats, isLoading } = trpc.ccp.getStats.useQuery({
    startDate,
    endDate,
  });

  return (
    
      <div className="flex flex-col gap-6">
        {/* 헤더 */}
        <div className="flex items-center justify-between">
          <div>
            <h1 className="text-3xl font-bold tracking-tight">CCP 자동 생성 통계</h1>
            <p className="text-muted-foreground mt-2">
              제품별 CCP 자동 생성 현황 및 추이를 확인합니다
            </p>
          </div>
          <div className="flex items-center gap-3">
            <Select value={dateRange} onValueChange={(value) => setDateRange(value as DateRange)}>
              <SelectTrigger className="w-[180px]">
                <Calendar className="mr-2 h-4 w-4" />
                <SelectValue />
              </SelectTrigger>
              <SelectContent>
                <SelectItem value="7days">최근 7일</SelectItem>
                <SelectItem value="30days">최근 30일</SelectItem>
                <SelectItem value="90days">최근 90일</SelectItem>
                <SelectItem value="all">전체 기간</SelectItem>
              </SelectContent>
            </Select>
          </div>
        </div>

        {isLoading ? (
          <div className="flex items-center justify-center py-12">
            <Loader2 className="h-8 w-8 animate-spin text-muted-foreground" />
          </div>
        ) : !stats ? (
          <div className="text-center py-12 text-muted-foreground">
            통계 데이터를 불러올 수 없습니다
          </div>
        ) : (
          <>
            {/* 전체 통계 카드 */}
            <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-4">
              <Card>
                <CardHeader className="pb-3">
                  <CardDescription>전체 배치</CardDescription>
                  <CardTitle className="text-3xl">{stats.overview.totalBatches}</CardTitle>
                </CardHeader>
                <CardContent>
                  <p className="text-xs text-muted-foreground">생성된 배치 수</p>
                </CardContent>
              </Card>

              <Card>
                <CardHeader className="pb-3">
                  <CardDescription>CCP 인스턴스</CardDescription>
                  <CardTitle className="text-3xl">{stats.overview.totalCcpInstances}</CardTitle>
                </CardHeader>
                <CardContent>
                  <p className="text-xs text-muted-foreground">생성된 CCP 수</p>
                </CardContent>
              </Card>

              <Card>
                <CardHeader className="pb-3">
                  <CardDescription>자동 생성 행</CardDescription>
                  <CardTitle className="text-3xl">{stats.overview.autoGeneratedCount}</CardTitle>
                </CardHeader>
                <CardContent>
                  <p className="text-xs text-muted-foreground">자동으로 생성된 점검 행</p>
                </CardContent>
              </Card>

              <Card>
                <CardHeader className="pb-3">
                  <CardDescription>자동 생성 비율</CardDescription>
                  <CardTitle className="text-3xl flex items-center gap-2">
                    {stats.overview.autoGeneratedRate.toFixed(1)}%
                    <TrendingUp className="h-5 w-5 text-green-500" />
                  </CardTitle>
                </CardHeader>
                <CardContent>
                  <p className="text-xs text-muted-foreground">전체 CCP 대비 자동 생성 비율</p>
                </CardContent>
              </Card>
            </div>

            {/* 제품별 통계 */}
            <Card>
              <CardHeader>
                <CardTitle className="flex items-center gap-2">
                  <BarChart3 className="h-5 w-5" />
                  제품별 CCP 생성 현황
                </CardTitle>
                <CardDescription>제품별 배치 수 및 CCP 자동 생성 현황</CardDescription>
              </CardHeader>
              <CardContent>
                {stats.byProduct.length === 0 ? (
                  <div className="text-center py-8 text-muted-foreground">
                    데이터가 없습니다
                  </div>
                ) : (
                  <ResponsiveContainer width="100%" height={300}>
                    <BarChart data={stats.byProduct}>
                      <CartesianGrid strokeDasharray="3 3" />
                      <XAxis dataKey="productName" />
                      <YAxis />
                      <Tooltip />
                      <Legend />
                      <Bar dataKey="ccpInstanceCount" name="CCP 인스턴스" fill="#3b82f6" />
                      <Bar dataKey="autoGeneratedCount" name="자동 생성 행" fill="#10b981" />
                    </BarChart>
                  </ResponsiveContainer>
                )}
              </CardContent>
            </Card>

            {/* CCP 타입별 통계 */}
            <Card>
              <CardHeader>
                <CardTitle>CCP 타입별 생성 현황</CardTitle>
                <CardDescription>CCP 타입별 인스턴스 생성 및 자동 생성 현황</CardDescription>
              </CardHeader>
              <CardContent>
                {stats.byCcpType.length === 0 ? (
                  <div className="text-center py-8 text-muted-foreground">
                    데이터가 없습니다
                  </div>
                ) : (
                  <ResponsiveContainer width="100%" height={300}>
                    <BarChart data={stats.byCcpType}>
                      <CartesianGrid strokeDasharray="3 3" />
                      <XAxis dataKey="ccpType" />
                      <YAxis />
                      <Tooltip />
                      <Legend />
                      <Bar dataKey="instanceCount" name="CCP 인스턴스" fill="#8b5cf6" />
                      <Bar dataKey="autoGeneratedCount" name="자동 생성 행" fill="#10b981" />
                    </BarChart>
                  </ResponsiveContainer>
                )}
              </CardContent>
            </Card>

            {/* 추이 차트 */}
            {stats.trend.length > 0 && (
              <Card>
                <CardHeader>
                  <CardTitle>CCP 생성 추이</CardTitle>
                  <CardDescription>일별 배치 및 CCP 생성 추이</CardDescription>
                </CardHeader>
                <CardContent>
                  <ResponsiveContainer width="100%" height={300}>
                    <LineChart data={stats.trend}>
                      <CartesianGrid strokeDasharray="3 3" />
                      <XAxis dataKey="date" />
                      <YAxis />
                      <Tooltip />
                      <Legend />
                      <Line
                        type="monotone"
                        dataKey="batchCount"
                        name="배치 수"
                        stroke="#3b82f6"
                        strokeWidth={2}
                      />
                      <Line
                        type="monotone"
                        dataKey="ccpInstanceCount"
                        name="CCP 인스턴스"
                        stroke="#8b5cf6"
                        strokeWidth={2}
                      />
                      <Line
                        type="monotone"
                        dataKey="autoGeneratedCount"
                        name="자동 생성 행"
                        stroke="#10b981"
                        strokeWidth={2}
                      />
                    </LineChart>
                  </ResponsiveContainer>
                </CardContent>
              </Card>
            )}

            {/* 제품별 상세 테이블 */}
            <Card>
              <CardHeader>
                <CardTitle>제품별 상세 통계</CardTitle>
                <CardDescription>제품별 배치, CCP, 자동 생성 상세 현황</CardDescription>
              </CardHeader>
              <CardContent>
                {stats.byProduct.length === 0 ? (
                  <div className="text-center py-8 text-muted-foreground">
                    데이터가 없습니다
                  </div>
                ) : (
                  <div className="overflow-x-auto">
                    <table className="w-full">
                      <thead>
                        <tr className="border-b">
                          <th className="text-left p-3 font-medium">제품명</th>
                          <th className="text-right p-3 font-medium">배치 수</th>
                          <th className="text-right p-3 font-medium">CCP 인스턴스</th>
                          <th className="text-right p-3 font-medium">자동 생성 행</th>
                          <th className="text-right p-3 font-medium">자동 생성 비율</th>
                        </tr>
                      </thead>
                      <tbody>
                        {stats.byProduct.map((product) => {
                          const rate =
                            product.ccpInstanceCount > 0
                              ? ((product.autoGeneratedCount / product.ccpInstanceCount) * 100).toFixed(1)
                              : "0.0";
                          return (
                            <tr key={product.productId} className="border-b hover:bg-accent/50">
                              <td className="p-3">{product.productName}</td>
                              <td className="text-right p-3">{product.batchCount}</td>
                              <td className="text-right p-3">{product.ccpInstanceCount}</td>
                              <td className="text-right p-3">{product.autoGeneratedCount}</td>
                              <td className="text-right p-3">
                                <span className="font-medium text-green-600">{rate}%</span>
                              </td>
                            </tr>
                          );
                        })}
                      </tbody>
                    </table>
                  </div>
                )}
              </CardContent>
            </Card>
          </>
        )}
      </div>
    
  );
}
