/**
 * CcpInspectionCard 분해 — 헬퍼 + EquipmentRowEdit.
 *  - calcCycleBreakdown  배치 총소요시간 분해 계산
 *  - ResultBadge         PASS/FAIL 배지
 *  - EquipmentRowEdit    설비 행 인라인 편집
 */
import { useState } from "react";
import { trpc } from "@/lib/trpc";
import { toast } from "sonner";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import {
  Select, SelectContent, SelectItem, SelectTrigger, SelectValue,
} from "@/components/ui/select";
import { Edit2, Save, X } from "lucide-react";

// 로컬 타입 (CcpInspectionCard의 타입 사용 — 동일 구조 재선언)
export interface CcpRow {
  id: number;
  instanceId: number;
  sortOrder: number;
  rowType: string;
  measuredAt?: string | null;
  tempC?: string | null;
  durationMin?: number | null;
  pressureBar?: string | null;
  result?: string | null;
  note?: string | null;
  autoGenerated?: number;
  equipmentId?: number | null;
  equipmentName?: string | null;
  heatingMin?: number | null;
  cycleTotalMin?: number | null;
  batchNo?: number | null;
}

export function calcCycleBreakdown(row: CcpRow): {
  cycleTotal: number | null;
  heating: number | null;
  total: number | null;
  defaultHeat: number | null;
} {
  if (row.cycleTotalMin == null && row.heatingMin == null) {
    return { cycleTotal: null, heating: null, total: row.durationMin ?? null, defaultHeat: null };
  }
  const cycleTotal  = row.cycleTotalMin ?? null;
  const heating     = row.heatingMin ?? null;
  const total       = row.durationMin ?? null;
  // defaultHeat = cycleTotalMin + heatingMin - durationMin → 설비기본가열시간 역산
  const defaultHeat =
    cycleTotal != null && heating != null && total != null
      ? cycleTotal + heating - total
      : null;
  return { cycleTotal, heating, total, defaultHeat };
}

const ccpTypeLabel: Record<string, string> = {
  "CCP-1B": "CCP-1B 교반/증숙",
  "CCP-2B": "CCP-2B 오븐굽기",
  "CCP-4P": "CCP-4P 금속검출",
  CCP_1B: "CCP-1B 교반/증숙",
  CCP_2B: "CCP-2B 오븐굽기",
  CCP_4P: "CCP-4P 금속검출",
};

const statusColor: Record<string, string> = {
  draft: "bg-gray-100 text-gray-700 dark:bg-gray-800 dark:text-gray-400",
  submitted: "bg-blue-100 text-blue-700 dark:bg-blue-950 dark:text-blue-400",
  approved:
    "bg-green-100 text-green-700 dark:bg-green-950 dark:text-green-400",
  rejected: "bg-red-100 text-red-700 dark:bg-red-950 dark:text-red-400",
};

const statusLabel: Record<string, string> = {
  draft: "초안",
  submitted: "제출됨",
  approved: "승인됨",
  rejected: "반려됨",
};

export function ResultBadge({ result }: { result?: string | null }) {
  if (!result) return <span className="text-muted-foreground">-</span>;
  if (result === "PASS")
    return (
      <Badge className="bg-green-100 text-green-700 dark:bg-green-950 dark:text-green-400">
        ✓ PASS
      </Badge>
    );
  if (result === "FAIL")
    return (
      <Badge className="bg-red-100 text-red-700 dark:bg-red-950 dark:text-red-400">
        ✗ FAIL
      </Badge>
    );
  return <Badge variant="outline">{result}</Badge>;
}

/** 설비행 인라인 편집 행 컴포넌트 */
export function EquipmentRowEdit({
  row,
  ccp,
  onSaved,
  showBatchNo = false,
}: {
  row: CcpRow;
  ccp: CcpInstance;
  onSaved: () => void;
  showBatchNo?: boolean;
}) {
  const [editing, setEditing] = useState(false);
  const [tempC, setTempC] = useState(row.tempC ?? "");
  const [pressureBar, setPressureBar] = useState(row.pressureBar ?? "");
  const [durationMin, setDurationMin] = useState(
    row.durationMin != null ? String(row.durationMin) : "",
  );
  const [result, setResult] = useState<"PASS" | "FAIL" | "N/A">(
    (row.result as any) ?? "PASS",
  );
  const [note, setNote] = useState(row.note ?? "");

  const is1B2B =
    ccp.ccpType === "CCP-1B" ||
    ccp.ccpType === "CCP_1B" ||
    ccp.ccpType === "CCP-2B" ||
    ccp.ccpType === "CCP_2B";

  const updateMutation = trpc.ccp.updateRow.useMutation({
    onSuccess: () => {
      toast.success(`${row.equipmentName ?? "설비"} 측정값 저장됨`);
      setEditing(false);
      onSaved();
    },
    onError: (err: { message: string }) => {
      toast.error(`저장 실패: ${err.message}`);
    },
  });

  const handleSave = () => {
    updateMutation.mutate({
      rowId: row.id,
      tempC: tempC || undefined,
      pressureBar: pressureBar || undefined,
      durationMin: durationMin ? Number(durationMin) : undefined,
      result,
      note: note || undefined,
      measuredAt: new Date(),
    });
  };

  if (!editing) {
    return (
      <tr className="border-b hover:bg-accent/30 group">
        <td className="p-2 text-center font-mono text-xs text-muted-foreground">
          {row.sortOrder}
        </td>
        {showBatchNo && (
          <td className="p-2 text-center">
            <Badge variant="outline" className="text-xs font-mono">
              {row.batchNo ?? "-"}
            </Badge>
          </td>
        )}
        <td className="p-2 font-medium text-sm">
          {row.equipmentName ?? `설비-${row.equipmentId}`}
        </td>
        {is1B2B && (
          <>
            <td className="p-2">
              <span
                className={
                  row.tempC == null ? "text-muted-foreground text-xs" : "font-mono text-sm"
                }
              >
                {row.tempC != null ? `${row.tempC}°C` : "미입력"}
              </span>
            </td>
            <td className="p-2">
              <span
                className={
                  row.pressureBar == null
                    ? "text-muted-foreground text-xs"
                    : "font-mono text-sm"
                }
              >
                {row.pressureBar != null ? `${row.pressureBar} bar` : "미입력"}
              </span>
            </td>
            <td className="p-2">
              <span
                className={
                  row.durationMin == null
                    ? "text-muted-foreground text-xs"
                    : "font-mono text-sm"
                }
              >
                {row.durationMin != null ? `${row.durationMin}분` : "미입력"}
              </span>
            </td>
          </>
        )}
        <td className="p-2">
          <ResultBadge result={row.result} />
        </td>
        <td className="p-2 text-muted-foreground text-xs max-w-[120px] truncate">
          {row.note ?? "-"}
        </td>
        <td className="p-2 text-muted-foreground text-xs">
          {row.measuredAt
            ? new Date(row.measuredAt).toLocaleString("ko-KR", {
                month: "2-digit",
                day: "2-digit",
                hour: "2-digit",
                minute: "2-digit",
              })
            : row.autoGenerated
              ? "자동생성"
              : "-"}
        </td>
        <td className="p-2">
          <Button
            size="sm"
            variant="ghost"
            className="h-7 w-7 p-0 opacity-0 group-hover:opacity-100 transition-opacity"
            onClick={() => setEditing(true)}
          >
            <Edit2 className="h-3.5 w-3.5" />
          </Button>
        </td>
      </tr>
    );
  }

  // 편집 모드
  return (
    <tr className="border-b bg-accent/20">
      <td className="p-2 text-center font-mono text-xs text-muted-foreground">
        {row.sortOrder}
      </td>
      {showBatchNo && (
        <td className="p-2 text-center">
          <Badge variant="outline" className="text-xs font-mono">
            {row.batchNo ?? "-"}
          </Badge>
        </td>
      )}
      <td className="p-2 font-medium text-sm text-primary">
        {row.equipmentName ?? `설비-${row.equipmentId}`}
      </td>
      {is1B2B && (
        <>
          <td className="p-1.5">
            <Input
              type="number"
              step="0.1"
              className="h-7 text-xs w-20"
              placeholder={ccp.tempMin != null ? `≥${ccp.tempMin}` : "°C"}
              value={tempC}
              onChange={(e) => setTempC(e.target.value)}
            />
          </td>
          <td className="p-1.5">
            <Input
              type="number"
              step="0.01"
              className="h-7 text-xs w-20"
              placeholder={
                ccp.pressureMin != null
                  ? `≥${(ccp.pressureMin * 10).toFixed(1)}`
                  : "bar"
              }
              value={pressureBar}
              onChange={(e) => setPressureBar(e.target.value)}
            />
          </td>
          <td className="p-1.5">
            <Input
              type="number"
              className="h-7 text-xs w-20"
              placeholder={ccp.timeMin != null ? `≥${ccp.timeMin}` : "분"}
              value={durationMin}
              onChange={(e) => setDurationMin(e.target.value)}
            />
          </td>
        </>
      )}
      <td className="p-1.5">
        <Select
          value={result}
          onValueChange={(v) => setResult(v as "PASS" | "FAIL" | "N/A")}
        >
          <SelectTrigger className="h-7 text-xs w-20">
            <SelectValue />
          </SelectTrigger>
          <SelectContent>
            <SelectItem value="PASS">✓ PASS</SelectItem>
            <SelectItem value="FAIL">✗ FAIL</SelectItem>
            <SelectItem value="N/A">N/A</SelectItem>
          </SelectContent>
        </Select>
      </td>
      <td className="p-1.5" colSpan={2}>
        <Input
          className="h-7 text-xs"
          placeholder="비고"
          value={note}
          onChange={(e) => setNote(e.target.value)}
        />
      </td>
      <td className="p-1.5">
        <div className="flex gap-1">
          <Button
            size="sm"
            className="h-7 w-7 p-0 bg-green-600 hover:bg-green-700"
            onClick={handleSave}
            disabled={updateMutation.isPending}
          >
            <Save className="h-3.5 w-3.5" />
          </Button>
          <Button
            size="sm"
            variant="ghost"
            className="h-7 w-7 p-0"
            onClick={() => setEditing(false)}
          >
            <X className="h-3.5 w-3.5" />
          </Button>
        </div>
      </td>
    </tr>
  );
}

