/**
 * 일일일지 자동 생성 — 소급(backfill) 등록 통합 테스트
 *
 * 설계 원칙 (2026-10-06 CEO 확정):
 *   자동 생성값의 기준 날짜는 등록 시각이 아니라 배치일자(batch.planned_date).
 *   과거 작업을 오늘 한꺼번에 등록해도 일일일지는 각 배치일자에 생성되어야 하고,
 *   온·습도 실측 필드는 다른 날짜의 값을 복사하지 않는다 (빈 값 → 작성자 입력).
 *
 * 실제 DB 가 필요한 통합 테스트. 테스트 데이터는 2031년 날짜를 사용해 운영 데이터와 격리.
 */
import { describe, it, expect, beforeAll, afterAll } from "vitest";
import { sql } from "drizzle-orm";
import { getDb } from "./db";
import { users, hBatches } from "../drizzle/schema";
import { hProductsV2 } from "../drizzle/schema/schema_main_products";
import { autoGenerateDailyReport } from "./lib/production/autoDailyReport";

const TENANT_ID = 1;
const SITE_ID = 1;
const PRIOR_DATE = "2031-09-19";    // 가장 최근 "과거" 일지 (복사 원본)
const BACKFILL_DATE = "2031-09-21"; // 소급 등록 대상 배치일자
const OTHER_DATE = "2031-10-15";    // 다른 배치일자 (같은 시각 등록)

async function loadRecord(db: any, recordId: number) {
  const res = await db.execute(sql`
    SELECT id, DATE_FORMAT(form_date, '%Y-%m-%d') AS form_date, form_data
    FROM h_generic_checklist_records
    WHERE id = ${recordId}
  `);
  const row = (res as any)[0]?.[0];
  if (!row) return null;
  const formData = typeof row.form_data === "string" ? JSON.parse(row.form_data) : row.form_data;
  return { id: Number(row.id), formDate: String(row.form_date), formData };
}

async function countRecordsForDate(db: any, dateStr: string) {
  const res = await db.execute(sql`
    SELECT COUNT(*) AS cnt FROM h_generic_checklist_records
    WHERE form_type = 'daily_log' AND tenant_id = ${TENANT_ID} AND site_id = ${SITE_ID}
      AND form_date = ${dateStr}
  `);
  return Number((res as any)[0]?.[0]?.cnt || 0);
}

describe("autoGenerateDailyReport — 소급 등록 시나리오", () => {
  const ts = Date.now();
  let userId: number;
  let productId: number;
  let priorRecordId: number;
  const createdBatchIds: number[] = [];
  const createdRecordIds: number[] = [];

  beforeAll(async () => {
    const db = await getDb();
    if (!db) throw new Error("DB 연결 실패");

    // 혹시 남아있는 이전 실행 잔재 정리 (2031 날짜는 테스트 전용)
    for (const d of [PRIOR_DATE, BACKFILL_DATE, OTHER_DATE]) {
      await db.execute(sql`
        DELETE FROM h_generic_checklist_records
        WHERE form_type = 'daily_log' AND tenant_id = ${TENANT_ID} AND site_id = ${SITE_ID} AND form_date = ${d}
      `);
      await db.execute(sql`
        DELETE FROM h_daily_reports
        WHERE tenant_id = ${TENANT_ID} AND site_id = ${SITE_ID} AND report_date = ${d} AND report_type = 'production'
      `);
    }

    const [user] = await db.insert(users).values({
      email: `backfill-test-${ts}@test.com`,
      name: "Backfill Test",
      passwordHash: "test",
      role: "worker",
      isActive: true,
    } as any).$returningId();
    userId = user.id;

    const [product] = await db.insert(hProductsV2).values({
      tenantId: TENANT_ID,
      productCode: `PROD-BACKFILL-${ts}`,
      productName: "소급 테스트 제품",
      unit: "kg",
      isActive: 1,
    } as any).$returningId();
    productId = product.id;

    // "가장 최근 과거" 일지: 실측값이 채워진 상태로 저장 (복사되면 안 되는 값)
    const priorFormData = {
      date: PRIOR_DATE,
      hygieneChecks: { facility1: "pass", facility2: "pass", hygiene1: "fail", storageTemp: "4℃" },
      foreignMaterialChecks: { material1: "pass", material2: "pass" },
      temperatureHumidity: {
        room1Morning: { time: "08:10", temp: "27.3", humidity: "58.0", pass: true },
        room1Afternoon: { time: "15:20", temp: "29.1", humidity: "49.5", pass: true },
        room2Morning: { time: "08:12", temp: "26.9", humidity: "57.0", pass: true },
        room2Afternoon: { time: "15:22", temp: "28.8", humidity: "50.0", pass: true },
      },
      freezerTemperature: {
        morning: { time: "08:00", rapidFreezer: "-31.0", freezer: "-19.0", pass: true },
        afternoon: { time: "15:10", rapidFreezer: "-31.2", freezer: "-19.5", pass: true },
      },
      refrigeratorTemperature: {
        morning: { time: "08:05", temp: "1.2", pass: true },
        afternoon: { time: "15:15", temp: "1.4", pass: true },
      },
      batches: [],
      autoGenerated: false,
    };
    const ins = await db.execute(sql`
      INSERT INTO h_generic_checklist_records
        (site_id, tenant_id, form_type, tenant_seq, form_date, title, form_data, status, created_by)
      VALUES
        (${SITE_ID}, ${TENANT_ID}, 'daily_log', 999001, ${PRIOR_DATE}, ${`일일일지 - ${PRIOR_DATE}`},
         ${JSON.stringify(priorFormData)}, 'draft', ${userId})
    `);
    priorRecordId = Number((ins as any)[0]?.insertId || 0);
    createdRecordIds.push(priorRecordId);
  });

  afterAll(async () => {
    const db = await getDb();
    if (!db) return;
    for (const id of createdRecordIds) {
      await db.execute(sql`DELETE FROM h_approval_requests WHERE request_type = 'daily_log' AND reference_type = 'checklist' AND reference_id = ${id} AND tenant_id = ${TENANT_ID}`);
      await db.execute(sql`DELETE FROM h_generic_checklist_records WHERE id = ${id}`);
    }
    for (const d of [PRIOR_DATE, BACKFILL_DATE, OTHER_DATE]) {
      await db.execute(sql`DELETE FROM h_daily_reports WHERE tenant_id = ${TENANT_ID} AND site_id = ${SITE_ID} AND report_date = ${d} AND report_type = 'production'`);
    }
    for (const id of createdBatchIds) {
      await db.execute(sql`DELETE FROM h_batches WHERE id = ${id} AND tenant_id = ${TENANT_ID}`);
    }
    if (productId) await db.execute(sql`DELETE FROM h_products_v2 WHERE id = ${productId} AND tenant_id = ${TENANT_ID}`);
    if (userId) await db.execute(sql`DELETE FROM users WHERE id = ${userId}`);
  });

  async function insertBatch(db: any, code: string, plannedDate: Date) {
    const [b] = await db.insert(hBatches).values({
      tenantId: TENANT_ID,
      siteId: SITE_ID,
      batchCode: code,
      productId,
      plannedQuantity: "100.00",
      plannedDate,
      status: "planned",
      createdBy: userId,
    } as any).$returningId();
    createdBatchIds.push(b.id);
    return b.id as number;
  }

  it("오늘 등록한 9/21 배치 → 일일일지는 배치일자(9/21)에 생성되고 온·습도는 전일 값을 복사하지 않는다", async () => {
    const db = await getDb();
    if (!db) throw new Error("DB 연결 실패");

    // 등록 시각은 "오늘" 이지만 배치일자는 과거. batch.create 라우터와 동일하게 작업일을 override 로 전달.
    const batchId = await insertBatch(db, `TEST-BACKFILL-A-${ts}`, new Date(`${BACKFILL_DATE}T12:00:00+09:00`));
    const result = await autoGenerateDailyReport(batchId, userId, BACKFILL_DATE);

    expect(result.success).toBe(true);
    expect(result.isNew).toBe(true);
    expect(result.checklistRecordId).toBeTruthy();
    createdRecordIds.push(result.checklistRecordId!);

    const rec = await loadRecord(db, result.checklistRecordId!);
    expect(rec).not.toBeNull();
    // 기준은 배치일자 — 등록일(오늘)이 아님
    expect(rec!.formDate).toBe(BACKFILL_DATE);
    expect(rec!.formData.date).toBe(BACKFILL_DATE);

    // 체크 항목은 가장 최근 과거 일지(9/19)에서 복사됨 (기존 동작 유지)
    expect(rec!.formData.preFilledFrom).toBe(PRIOR_DATE);
    expect(rec!.formData.hygieneChecks.facility1).toBe("pass");
    expect(rec!.formData.hygieneChecks.hygiene1).toBe("fail");
    expect(rec!.formData.foreignMaterialChecks.material1).toBe("pass");

    // 온·습도 실측 필드는 복사되지 않고 빈 값 (작성자가 당일 측정값 입력)
    const th = rec!.formData.temperatureHumidity;
    for (const slot of ["room1Morning", "room1Afternoon", "room2Morning", "room2Afternoon"]) {
      expect(th[slot].temp).toBe("");
      expect(th[slot].humidity).toBe("");
      expect(th[slot].time).toBe("");
      expect(th[slot].pass).toBeNull();
    }
    const fz = rec!.formData.freezerTemperature;
    expect(fz.morning.rapidFreezer).toBe("");
    expect(fz.morning.freezer).toBe("");
    expect(fz.afternoon.freezer).toBe("");
    const rf = rec!.formData.refrigeratorTemperature;
    expect(rf.morning.temp).toBe("");
    expect(rf.afternoon.temp).toBe("");

    // 9/19 원본 값이 어디에도 새어 들어가지 않았는지
    const serialized = JSON.stringify({ th, fz, rf });
    expect(serialized).not.toContain("27.3");
    expect(serialized).not.toContain("-31.0");
  });

  it("같은 시각에 등록한 다른 배치일자(10/15) 배치는 별도 일일일지로 생성된다 (planned_date 폴백 경로)", async () => {
    const db = await getDb();
    if (!db) throw new Error("DB 연결 실패");

    // workDateOverride 없이 호출 → batch.planned_date 로 작업일 결정
    const batchId = await insertBatch(db, `TEST-BACKFILL-B-${ts}`, new Date(`${OTHER_DATE}T12:00:00+09:00`));
    const result = await autoGenerateDailyReport(batchId, userId);

    expect(result.success).toBe(true);
    expect(result.isNew).toBe(true);
    createdRecordIds.push(result.checklistRecordId!);

    const rec = await loadRecord(db, result.checklistRecordId!);
    expect(rec!.formDate).toBe(OTHER_DATE);
    expect(rec!.formData.date).toBe(OTHER_DATE);
    // 이제 가장 최근 과거 일지는 9/21 (위 테스트에서 생성) — 체크 항목은 거기서 복사
    expect(rec!.formData.preFilledFrom).toBe(BACKFILL_DATE);
    // 온·습도는 여전히 빈 값
    expect(rec!.formData.temperatureHumidity.room1Morning.temp).toBe("");
    expect(rec!.formData.refrigeratorTemperature.morning.temp).toBe("");

    // 9/21 과 10/15 는 서로 다른 레코드
    expect(await countRecordsForDate(db, BACKFILL_DATE)).toBe(1);
    expect(await countRecordsForDate(db, OTHER_DATE)).toBe(1);
  });

  it("같은 배치일자(9/21)에 배치를 하나 더 등록하면 기존 일일일지에 추가되고 새 일지는 생기지 않는다", async () => {
    const db = await getDb();
    if (!db) throw new Error("DB 연결 실패");

    const batchId = await insertBatch(db, `TEST-BACKFILL-C-${ts}`, new Date(`${BACKFILL_DATE}T12:00:00+09:00`));
    const result = await autoGenerateDailyReport(batchId, userId, BACKFILL_DATE);

    expect(result.success).toBe(true);
    expect(result.isNew).toBe(false);
    expect(await countRecordsForDate(db, BACKFILL_DATE)).toBe(1);

    const rec = await loadRecord(db, result.checklistRecordId!);
    expect(rec!.formData.batches.length).toBe(2);
    // 배치 추가는 온·습도를 건드리지 않음
    expect(rec!.formData.temperatureHumidity.room1Morning.temp).toBe("");
  });
});
