/**
 * 배치 투입/문서 자동생성
 * batchFunctions.ts에서 분할
 */
import { eq, and, desc, sql, like } from "drizzle-orm";
import { getDb, getRawConnection } from "../connection";
import { todayKST, toKSTTimestamp } from "../../utils/timezone";
import { hBatches, hBatchInputs, hCcpInstances, hCcpRecords, hProductsV2, hMaterials, hInventory, hInventoryTransactions, hApprovalRequests } from "../../../drizzle/schema";


/**
 * 배치 투입 라인 1건 추가.
 *
 * **`materialId` 의 의미:**
 *   반드시 `h_materials.id` (원재료 마스터) 값. 중간재(`h_intermediates.id`) 또는
 *   완제품(`h_products_v2.id`) 을 넘기면 데이터 무결성이 깨집니다.
 *   (Drizzle schema: `hBatchInputs.materialId.references(() => hMaterials.id)`)
 *
 * 호출자(라우터/서비스) 단에서 입력 검증 시 이 ID 가 raw_material 임을
 * 보장해야 합니다. tRPC zod input 에는 `.describe()` 로 의미를 명시.
 */
export async function addBatchInput(input: {
  batchId: number;
  /** **반드시 `h_materials.id` (원재료 마스터)**. intermediates/products 금지. */
  materialId: number;
  quantity: string;
  unitPrice?: string;
  totalPrice?: string;
  notes?: string;
  createdBy: number;
  tenantId?: number;
}) {
  const db = await getDb();
  if (!db) throw new Error("Database not available");

  const { hBatchInputs } = await import("../../../drizzle/schema");

  // tenantId 격리: 배치 소유권 검증
  if (input.tenantId) {
    const batchCheck = await db.select({ id: hBatches.id }).from(hBatches)
      .where(and(eq(hBatches.id, input.batchId), eq(hBatches.tenantId, input.tenantId))).limit(1);
    if (batchCheck.length === 0) throw new Error("해당 배치에 대한 접근 권한이 없습니다");
  }

  const [result] = await db.insert(hBatchInputs).values({
    batchId: input.batchId,
    materialId: input.materialId,
    quantity: input.quantity,
    unitPrice: input.unitPrice || "0",
    totalPrice: input.totalPrice || "0",
    notes: input.notes || null,
    createdBy: input.createdBy,
    tenantId: input.tenantId || 1
  } as any);

  return Number(result.insertId);
}

/**
 * 배치 투입 내역 조회
 */
export async function getBatchInputs(batchId: number) {
  const db = await getDb();
  if (!db) return [];

  const { hBatchInputs } = await import("../../../drizzle/schema");

  const result = await db
    .select()
    .from(hBatchInputs)
    .where(eq(hBatchInputs.batchId, batchId));

  return result;
}

// 배치 생성 시 자동 문서 생성 함수
// ★ 2026-04-15: tenantId 파라미터 추가 (이전: NULL 로 저장되어 테넌트 격리 위반)
export async function autoGenerateDocumentsForBatch(
  batchId: number,
  siteId: number,
  productId: number,
  workDate: Date,
  createdBy: number,
  tenantId?: number
) {
  const db = await getDb();
  if (!db) {
    console.error('[autoGenerateDocumentsForBatch] DB 연결 실패');
    return [];
  }

  try {
    const rawConn = await getRawConnection();
    if (!rawConn) {
      console.error('[autoGenerateDocumentsForBatch] Raw connection 실패');
      return [];
    }

    // tenantId 미지정 시 배치에서 조회 (호환성 폴백)
    let resolvedTenantId = tenantId;
    if (!resolvedTenantId) {
      const [batchRows] = await rawConn.execute(
        "SELECT tenant_id FROM h_batches WHERE id = ? LIMIT 1",
        [batchId]
      );
      resolvedTenantId = (batchRows as any[])[0]?.tenant_id;
      if (!resolvedTenantId) {
        console.error(`[autoGenerateDocumentsForBatch] tenant_id 결정 실패 (batch=${batchId})`);
        return [];
      }
    }

    const workDateStr = workDate instanceof Date
      ? `${workDate.getFullYear()}-${String(workDate.getMonth() + 1).padStart(2, "0")}-${String(workDate.getDate()).padStart(2, "0")}`
      : workDate;
    const now = toKSTTimestamp(new Date());

    // 1. auto_generate_on_batch = 1인 문서 유형 조회
    const [docTypes] = await rawConn.execute(
      "SELECT id, code, name, category FROM document_types WHERE auto_generate_on_batch = 1"
    );

    if (!docTypes || (docTypes as any[]).length === 0) {
      console.log('[autoGenerateDocumentsForBatch] 자동 생성 대상 문서 유형 없음');
      return [];
    }

    const generatedDocs: any[] = [];

    // 2. 각 문서 유형별로 document_instances 생성
    for (const docType of (docTypes as any[])) {
      // 이미 생성된 문서가 있는지 확인 (중복 방지, tenant_id 격리)
      const [existing] = await rawConn.execute(
        "SELECT id FROM document_instances WHERE batch_id = ? AND document_type_id = ? AND site_id = ? AND tenant_id = ?",
        [batchId, docType.id, siteId, resolvedTenantId]
      );

      if ((existing as any[]).length > 0) {
        console.log(`[autoGenerateDocumentsForBatch] 이미 존재: batch=${batchId}, docType=${docType.code}`);
        continue;
      }

      // document_instances 생성 (tenant_id 포함)
      const [result] = await rawConn.execute(
        `INSERT INTO document_instances
         (tenant_id, site_id, document_type_id, batch_id, product_id, work_date, status, is_auto_generated, created_by, created_at)
         VALUES (?, ?, ?, ?, ?, ?, 'pending_review', 1, ?, ?)`,
        [resolvedTenantId, siteId, docType.id, batchId, productId, workDateStr, createdBy, now]
      );

      const insertId = (result as any).insertId;
      generatedDocs.push({
        id: insertId,
        documentTypeCode: docType.code,
        documentTypeName: docType.name,
        category: docType.category,
      });

      console.log(`[autoGenerateDocumentsForBatch] 문서 생성: batch=${batchId}, docType=${docType.code}, id=${insertId}`);
    }

    console.log(`[autoGenerateDocumentsForBatch] 총 ${generatedDocs.length}건 문서 자동 생성 완료`);
    return generatedDocs;
  } catch (error) {
    console.error('[autoGenerateDocumentsForBatch] 오류:', error);
    return [];
  }
}
