import PDFDocument from "pdfkit";
import { format } from "date-fns";
import { ko } from "date-fns/locale";

interface DocumentPDFData {
  document: any;
  documentType: any;
  batch?: any;
  product?: any;
  creator?: any;
  reviewer?: any;
  approver?: any;
}

// 개별 문서 PDF 생성
export async function generateDocumentPDF(data: DocumentPDFData): Promise<Buffer> {
  return new Promise((resolve, reject) => {
    try {
      const doc = new PDFDocument({ size: "A4", margin: 50 });
      const chunks: Buffer[] = [];

      doc.on("data", (chunk) => chunks.push(chunk));
      doc.on("end", () => resolve(Buffer.concat(chunks)));
      doc.on("error", reject);

      // 헤더
      doc.fontSize(20).text(data.documentType.name, { align: "center" });
      doc.moveDown();
      
      // 문서 정보
      doc.fontSize(14).text("문서 정보", { underline: true });
      doc.moveDown(0.5);
      doc.fontSize(10);
      doc.text(`문서 번호: DOC-${data.document.id}`);
      doc.text(`작업 날짜: ${format(new Date(data.document.workDate), "PPP", { locale: ko })}`);
      doc.text(`상태: ${getStatusText(data.document.status)}`);
      doc.moveDown();

      // 배치 정보 (있는 경우)
      if (data.batch) {
        doc.fontSize(14).text("배치 정보", { underline: true });
        doc.moveDown(0.5);
        doc.fontSize(10);
        doc.text(`배치 코드: ${data.batch.batchCode}`);
        if (data.product) {
          doc.text(`제품명: ${data.product.name || "N/A"}`);
        }
        doc.text(`계획 수량: ${data.batch.plannedQuantity}`);
        doc.moveDown();
      }

      // 승인 정보
      doc.fontSize(14).text("승인 정보", { underline: true });
      doc.moveDown(0.5);
      doc.fontSize(10);
      
      if (data.creator) {
        doc.text(`작성자: ${data.creator.name || data.creator.email}`);
        doc.text(`작성 일시: ${format(new Date(data.document.createdAt), "PPpp", { locale: ko })}`);
      }
      
      if (data.reviewer && data.document.reviewedAt) {
        doc.text(`검토자: ${data.reviewer.name || data.reviewer.email}`);
        doc.text(`검토 일시: ${format(new Date(data.document.reviewedAt), "PPpp", { locale: ko })}`);
      }
      
      if (data.approver && data.document.approvedAt) {
        doc.text(`승인자: ${data.approver.name || data.approver.email}`);
        doc.text(`승인 일시: ${format(new Date(data.document.approvedAt), "PPpp", { locale: ko })}`);
      }
      
      doc.moveDown();

      // 자동 생성 여부
      if (data.document.isAutoGenerated) {
        doc.fontSize(10).fillColor("gray");
        doc.text("※ 이 문서는 자동으로 생성되었습니다.", { align: "center" });
      }

      // 푸터
      doc.fontSize(8).fillColor("gray");
      doc.text(
        `생성 일시: ${format(new Date(), "PPpp", { locale: ko })}`,
        50,
        doc.page.height - 50,
        { align: "center" }
      );

      doc.end();
    } catch (error) {
      reject(error);
    }
  });
}

// 일괄 출력 통합 PDF 생성
export async function generateBatchPrintPDF(documents: DocumentPDFData[]): Promise<Buffer> {
  return new Promise((resolve, reject) => {
    try {
      const doc = new PDFDocument({ size: "A4", margin: 50 });
      const chunks: Buffer[] = [];

      doc.on("data", (chunk) => chunks.push(chunk));
      doc.on("end", () => resolve(Buffer.concat(chunks)));
      doc.on("error", reject);

      // 표지
      doc.fontSize(24).text("일괄 출력 문서", { align: "center" });
      doc.moveDown();
      doc.fontSize(12).text(`총 ${documents.length}개 문서`, { align: "center" });
      doc.fontSize(10).text(
        `생성 일시: ${format(new Date(), "PPpp", { locale: ko })}`,
        { align: "center" }
      );
      
      // 각 문서별로 페이지 추가
      documents.forEach((docData, index) => {
        doc.addPage();
        
        // 헤더
        doc.fontSize(18).text(`${index + 1}. ${docData.documentType.name}`, { underline: true });
        doc.moveDown();
        
        // 문서 정보
        doc.fontSize(10);
        doc.text(`문서 번호: DOC-${docData.document.id}`);
        doc.text(`작업 날짜: ${format(new Date(docData.document.workDate), "PPP", { locale: ko })}`);
        doc.text(`상태: ${getStatusText(docData.document.status)}`);
        doc.moveDown();

        // 배치 정보 (있는 경우)
        if (docData.batch) {
          doc.fontSize(12).text("배치 정보", { underline: true });
          doc.moveDown(0.5);
          doc.fontSize(10);
          doc.text(`배치 코드: ${docData.batch.batchCode}`);
          if (docData.product) {
            doc.text(`제품명: ${docData.product.name || "N/A"}`);
          }
          doc.text(`계획 수량: ${docData.batch.plannedQuantity}`);
          doc.moveDown();
        }

        // 승인 정보
        doc.fontSize(12).text("승인 정보", { underline: true });
        doc.moveDown(0.5);
        doc.fontSize(10);
        
        if (docData.creator) {
          doc.text(`작성자: ${docData.creator.name || docData.creator.email}`);
        }
        
        if (docData.approver && docData.document.approvedAt) {
          doc.text(`승인자: ${docData.approver.name || docData.approver.email}`);
          doc.text(`승인 일시: ${format(new Date(docData.document.approvedAt), "PPpp", { locale: ko })}`);
        }
      });

      doc.end();
    } catch (error) {
      reject(error);
    }
  });
}

function getStatusText(status: string): string {
  const statusMap: Record<string, string> = {
    draft: "초안",
    pending_review: "검토 대기",
    pending_approval: "승인 대기",
    approved: "승인 완료",
    rejected: "반려"
  };
  return statusMap[status] || status;
}
