/**
 * h_inventory_deduction_log INSERT 헬퍼 (PR #299 F5-4)
 *
 * 배경:
 *   - h_inventory_deduction_log 는 HACCP 생산이력 화면에서 SELECT 만 했고
 *     INSERT 코드는 코드베이스 어디에도 존재하지 않았음.
 *   - 결과: 표는 항상 비어 있었고, 실제 차감 내역과 보고용 로그가 분리됨.
 *
 * 설계 원칙:
 *   1. h_inventory_deduction_log.production_log_id 는 NOT NULL 이므로
 *      먼저 h_production_log (단수형, mf_report_version 기반) 행을 보장.
 *   2. ensureProductionLog: idempotent.
 *      - 동일 (mf_report_version_id, production_date, batch ref in notes) 가 있으면 그 행 사용
 *      - 없으면 INSERT
 *   3. INSERT 실패가 차감 main flow 를 절대 막지 않도록 모든 함수가
 *      try/catch + console.warn — best-effort 보고용 로깅.
 *   4. 단수형 h_production_log + h_inventory_deduction_log 는 자체 tenant_id
 *      컬럼이 없어 mf_report_version → mf_report.tenant_id 로 격리됨.
 *
 * 사용:
 *   const productionLogId = await ensureProductionLogForBatch(batchId, tenantId, conn);
 *   if (productionLogId) {
 *     await insertInventoryDeductionLog({
 *       productionLogId,
 *       materialId: canonicalId,
 *       materialType: "raw_material",
 *       deductedQuantity: qty,
 *       unit: "kg",
 *     }, conn);
 *   }
 */

import type { AnyConn } from "./materialIdResolver";

/**
 * 배치 → 최신 APPROVED mf_report_version → h_production_log 행 보장
 *
 * @returns production_log_id 또는 null (실패 시)
 */
export async function ensureProductionLogForBatch(
  batchId: number,
  tenantId: number,
  conn: AnyConn,
): Promise<number | null> {
  try {
    // STEP 1: 배치 → 최신 APPROVED mf_report_version_id 추적
    const [verRows]: any = await conn.execute(
      `SELECT
         b.id AS batch_id,
         b.product_id,
         b.planned_date,
         b.batch_code,
         COALESCE(b.actual_quantity, b.planned_quantity, 0) AS produced_qty,
         v.id AS version_id
       FROM h_batches b
       JOIN h_mf_reports r
         ON r.product_id = b.product_id
        AND r.tenant_id = b.tenant_id
       JOIN h_mf_report_versions v
         ON v.mf_report_id = r.id
       WHERE b.id = ?
         AND b.tenant_id = ?
       ORDER BY
         CASE WHEN v.approval_status = 'APPROVED' THEN 0 ELSE 1 END,
         v.version_no DESC
       LIMIT 1`,
      [batchId, tenantId],
    );

    const row = (verRows as any[])[0];
    if (!row || !row.version_id) {
      console.warn(
        `[deductionLog] ensureProductionLog: batch=${batchId} 의 mf_report_version 을 찾지 못함 — skip`,
      );
      return null;
    }

    const versionId = Number(row.version_id);
    const productionDate = row.planned_date; // YYYY-MM-DD
    const batchCode = String(row.batch_code || "");
    const producedQty = Number(row.produced_qty) || 0;

    // STEP 2: idempotent 조회 — notes 에 batch ref 가 있는 동일 production_log 찾기
    //   notes 에 'batch_id:NN' 패턴을 심어 두면 추후 같은 배치에서 다시 호출 시 재사용 가능
    const batchRef = `batch_id:${batchId}`;
    const [existingRows]: any = await conn.execute(
      `SELECT id FROM h_production_log
        WHERE mf_report_version_id = ?
          AND production_date = ?
          AND notes LIKE ?
        ORDER BY id DESC
        LIMIT 1`,
      [versionId, productionDate, `%${batchRef}%`],
    );

    const existing = (existingRows as any[])[0];
    if (existing && existing.id) {
      return Number(existing.id);
    }

    // STEP 3: 없으면 INSERT — produced_quantity 는 INT 컬럼이므로 round
    const [insertResult]: any = await conn.execute(
      `INSERT INTO h_production_log
         (mf_report_version_id, production_date, batch_size_kg, produced_quantity, notes)
       VALUES (?, ?, ?, ?, ?)`,
      [
        versionId,
        productionDate,
        producedQty.toFixed(2),
        Math.round(producedQty),
        `auto-generated by autoMaterialIssue | batch_code:${batchCode} | ${batchRef}`,
      ],
    );

    const insertId = Number(insertResult?.insertId || 0);
    if (insertId > 0) {
      return insertId;
    }
    console.warn(
      `[deductionLog] ensureProductionLog: INSERT insertId=0 batch=${batchId}`,
    );
    return null;
  } catch (e: any) {
    console.warn(
      `[deductionLog] ensureProductionLog 예외 batch=${batchId}: ${e?.message || e}`,
    );
    return null;
  }
}

/**
 * h_inventory_deduction_log 단일 행 INSERT
 * 실패해도 차감 main flow 에 영향 없음 (best-effort).
 */
export async function insertInventoryDeductionLog(
  params: {
    productionLogId: number;
    materialId: number | null;
    intermediateId?: number | null;
    materialType: string; // 'raw_material' | 'subsidiary' | 'intermediate' 등
    deductedQuantity: number;
    unit: string;
  },
  conn: AnyConn,
): Promise<boolean> {
  try {
    if (!params.productionLogId) return false;
    if (!(params.deductedQuantity > 0)) return false; // 0 이하 차감은 로깅 의미 없음

    await conn.execute(
      `INSERT INTO h_inventory_deduction_log
         (production_log_id, material_id, intermediate_id, material_type,
          deducted_quantity, unit, deduction_date)
       VALUES (?, ?, ?, ?, ?, ?, NOW())`,
      [
        params.productionLogId,
        params.materialId ?? null,
        params.intermediateId ?? null,
        params.materialType,
        params.deductedQuantity.toFixed(3),
        params.unit,
      ],
    );
    return true;
  } catch (e: any) {
    console.warn(
      `[deductionLog] insertInventoryDeductionLog 예외 prodLog=${params.productionLogId} mat=${params.materialId}: ${e?.message || e}`,
    );
    return false;
  }
}
