/**
 * DailyLogRenderers.tsx
 * Render functions for daily_log pages and related sub-forms:
 * - renderDailyLogPages (5-page daily log)
 * - renderEmployeeHealthCheck
 * - renderAirCompressorMaintenance
 * - renderEquipmentInspection
 * - renderTemperatureHumidityCheck
 * - renderAirborneBacteriaTest
 * - renderTrainingLog
 */
import React from "react";
import { TitleWithApproval } from "./PrintHelpers";

// ============================================================================
// daily_log 5페이지 전용 렌더러
// ============================================================================
export function renderDailyLogPages(data: any, doc?: any): React.ReactNode[] {
  const d = data || {};
  const authorName = doc?.authorName || "";
  const approverName = doc?.approverName || "";

  const TitleRow = ({ title, subtitle, info }: { title: string; subtitle?: string; info?: React.ReactNode }) => (
    <TitleWithApproval title={title} subtitle={subtitle} doc={doc} infoLeft={info} />
  );

  // 자동생성 일일일지 — 위생 점검이 아직 미작성이면 안내 메시지 표시
  // ★ hygieneChecks가 작성되어 있으면 정상 렌더링으로 진행 (수동 보완 후 제출한 경우)
  const hasFilledHygiene = Array.isArray(d.hygieneChecks)
    ? d.hygieneChecks.some((c: any) => c.checkResult && c.checkResult !== '')
    : (d.hygieneChecks && Object.keys(d.hygieneChecks).length > 0);
  if (d.autoGenerated && Array.isArray(d.batches) && !hasFilledHygiene) {
    const dateStr = d.date || "";
    const autoPage = (
      <div>
        <div className="text-center mb-4">
          <h2 className="text-xl font-bold">일반위생관리 및 공정점검표</h2>
          <p className="text-sm text-gray-500">작업일: {dateStr}</p>
        </div>
        <div className="mb-4 p-3 bg-yellow-50 border border-yellow-300 rounded text-sm text-yellow-800">
          ⚠ 이 점검표는 배치 생성 시 자동 생성되었습니다. 위생 점검 항목을 직접 작성하여 제출하세요.
        </div>
        <div className="mt-4 p-3 bg-gray-50 border border-gray-200 rounded text-sm">
          <p className="font-medium mb-1">위생 점검 미작성 항목</p>
          <p className="text-gray-500">위생 점검 내용이 아직 작성되지 않았습니다. 승인 관리 &gt; 일일일지에서 내용을 보완한 후 제출하세요.</p>
        </div>
      </div>
    );
    return [autoPage];
  }

  // hygieneChecks/foreignMaterialChecks: 배열이면 객체로 변환, 객체면 그대로
  const normalizeChecks = (raw: any, keys: string[]): Record<string, any> => {
    if (!raw) return {};
    if (!Array.isArray(raw)) return raw; // 이미 객체
    // 배열이면 checkResult → boolean 변환 ('yes', true, '적합' 모두 적합)
    const obj: Record<string, any> = {};
    raw.forEach((item: any, i: number) => {
      if (keys[i]) obj[keys[i]] = item.checkResult === 'yes' || item.checkResult === true || item.checkResult === '적합';
    });
    return obj;
  };
  const hygieneKeys = ['hygiene1','hygiene2','hygiene3','pest1','facility1','storage1','process1','process2','process3','process4','pest2','cleaning1','facility2','ccp1','storage2','inspection1','transport1','transport2'];
  const foreignKeys = ['material1','material2','material3','process1','process2','process3','worker1','worker2','worker3','equipment1','equipment2','equipment3','pest1','pest2'];
  const hc = normalizeChecks(d.hygieneChecks, hygieneKeys);
  const fc = normalizeChecks(d.foreignMaterialChecks, foreignKeys);

  // 온도: 배열이면 객체로 변환
  const normTemp = (raw: any): any => {
    if (!raw) return {};
    if (Array.isArray(raw)) {
      // DailyLogForm 배열 구조 → 인쇄 객체 구조
      const obj: any = {};
      for (const item of raw) {
        const key = `${item.roomName || ''}${item.timePeriod || ''}`.replace(/\s/g, '');
        const mapped: any = {
          time: item.checkTime || '',
          temp: item.temperature || item.rapidFreezerTemp || '',
          humidity: item.humidity || '',
          rapidFreezer: item.rapidFreezerTemp || '',
          freezer: item.freezerTemp || '',
          pass: item.evaluation === 'pass' || item.evaluation === true || item.evaluation === '적합',
        };
        // 자동 키 매핑 (roomName에 '1','2' 포함 또는 순서 기반)
        const rn = item.roomName || '';
        const isRoom1 = rn.includes('1') || rn.includes('재료실1');
        const isRoom2 = rn.includes('2') || rn.includes('재료실2');
        if (isRoom1 && item.timePeriod === '오전') obj.room1Morning = mapped;
        else if (isRoom1 && item.timePeriod === '오후') obj.room1Afternoon = mapped;
        else if (isRoom2 && item.timePeriod === '오전') obj.room2Morning = mapped;
        else if (isRoom2 && item.timePeriod === '오후') obj.room2Afternoon = mapped;
        else if (item.timePeriod === '오전' && !obj.room1Morning && !obj.morning) {
          // 번호 없는 단일 룸 → room1 또는 morning에 배정
          obj.room1Morning = mapped; obj.morning = mapped;
        } else if (item.timePeriod === '오후' && !obj.room1Afternoon && !obj.afternoon) {
          obj.room1Afternoon = mapped; obj.afternoon = mapped;
        } else if (item.timePeriod === '오전') { obj.room2Morning = mapped; obj.morning = obj.morning || mapped; }
        else if (item.timePeriod === '오후') { obj.room2Afternoon = mapped; obj.afternoon = obj.afternoon || mapped; }
      }
      return obj;
    }
    return raw; // 이미 객체
  };
  // temperatureRecords 통합 배열에서 roomName 기준으로 3개 카테고리 분리
  const splitTemperatureRecords = (records: any[]) => {
    const tempHumidity: any[] = []; // 원재료실
    const freezer: any[] = [];      // 냉동창고/완제품창고(급속냉동고/냉동고)
    const fridge: any[] = [];       // 냉장창고
    for (const r of records) {
      const name = (r.roomName || '').toLowerCase();
      if (name.includes('원재료') || name.includes('재료실') || name.includes('작업장')) tempHumidity.push(r);
      else if (name.includes('냉동') || name.includes('완제품') || name.includes('급속')) freezer.push(r);
      else if (name.includes('냉장')) fridge.push(r);
      else tempHumidity.push(r); // fallback
    }
    // 냉동 카테고리: 급속냉동고/냉동고/완제품창고를 오전/오후로 합산
    // 같은 시간대의 여러 냉동 기록을 하나의 레코드로 병합 (rapidFreezer + freezer)
    const mergeFreezerRecords = (recs: any[]): any[] => {
      const byPeriod: Record<string, any> = {};
      for (const r of recs) {
        const period = r.timePeriod || '오전';
        if (!byPeriod[period]) {
          byPeriod[period] = { ...r, rapidFreezerTemp: null, freezerTemp: null };
        }
        const name = (r.roomName || '');
        if (name.includes('급속') || name.includes('완제품')) {
          byPeriod[period].rapidFreezerTemp = r.temperature;
        } else if (name.includes('냉동')) {
          byPeriod[period].freezerTemp = r.temperature;
        }
        // 시간/평가 최신 유지
        if (r.checkTime) byPeriod[period].checkTime = r.checkTime;
        if (r.evaluation) byPeriod[period].evaluation = r.evaluation;
      }
      return Object.values(byPeriod);
    };
    return { tempHumidity, freezer: mergeFreezerRecords(freezer), fridge };
  };
  // 기존 개별 필드 또는 통합 temperatureRecords 배열 모두 지원
  let th = normTemp(d.temperatureHumidity);
  let ft = normTemp(d.freezerTemperature);
  let rt = normTemp(d.refrigeratorTemperature);
  // temperatureRecords 통합 배열이 있고 개별 필드가 비어있으면 분리
  if (Array.isArray(d.temperatureRecords) && d.temperatureRecords.length > 0) {
    const split = splitTemperatureRecords(d.temperatureRecords);
    if (!d.temperatureHumidity && split.tempHumidity.length > 0) th = normTemp(split.tempHumidity);
    if (!d.freezerTemperature && split.freezer.length > 0) ft = normTemp(split.freezer);
    if (!d.refrigeratorTemperature && split.fridge.length > 0) rt = normTemp(split.fridge);
  }
  const date = d.date || "";
  const inspector = d.inspector || d.approval?.writerName || "";
  // 특이사항/조치 데이터: 중첩 구조(hygieneNotes, temperatureHumidityIssues 등)와 평탄 구조 모두 지원
  const hygieneNotes = d.hygieneNotes || {};
  const foreignNotes = d.foreignMaterialNotes || {};
  const tempIssues = d.temperatureHumidityIssues || {};
  const freezerIssues = d.freezerIssues || {};
  const refIssues = d.refrigeratorIssues || {};
  const confirmer = d.confirmer || hygieneNotes.confirmedBy || "";
  const actionContent = d.actionContent || hygieneNotes.improvementAction || "";
  const actionTaker = d.actionTaker || hygieneNotes.actionBy || "";
  const specialNotes1 = d.specialNotes || hygieneNotes.specialNotes || "";
  const specialNotes2 = foreignNotes.specialNotes || "";
  const foreignActionContent = foreignNotes.improvementAction || actionContent;
  const foreignActionTaker = foreignNotes.actionBy || actionTaker;
  const foreignConfirmer = foreignNotes.confirmedBy || confirmer;

  // 적합/부적합 판정: true, 'yes', 'pass', '적합' → 적합, 그 외(값 없으면 포함) → 부적합
  const check = (v: any) => (v === true || v === 'yes' || v === 'pass' || v === '적합') ? "적합" : "부적합";
  // 데이터 없으면 "-" 표시 (아예 미입력 상태)
  const checkOrDash = (v: any) => v === null || v === undefined ? "-" : check(v);
  const cellCls = "border border-gray-400 px-2 py-1 text-sm";
  const headCls = "border border-gray-400 px-2 py-1 text-sm font-medium bg-gray-50";
  const secCls = "border border-gray-400 px-2 py-1 text-sm font-bold bg-blue-50";

  // 페이지 1: 일반위생관리 및 공정점검표
  const page1 = (
    <div>
      <TitleRow title="일반위생관리 및 공정점검표" subtitle="(매일 작성)" info={<><span className="font-medium">점검일자:</span> {date} &nbsp;&nbsp; <span className="font-medium">점검자:</span> {authorName || inspector || "-"}</>} />
      <table className="w-full border-collapse border border-gray-400 text-sm">
        <thead>
          <tr className="bg-blue-100">
            <th className={headCls} style={{width:"80px"}}>구분</th>
            <th className={headCls} style={{width:"100px"}}>분류</th>
            <th className={headCls}>점검 내용</th>
            <th className={headCls} style={{width:"80px"}}>기록</th>
          </tr>
        </thead>
        <tbody>
          <tr><td className={secCls} rowSpan={10}>일일{"\n"}(작업전)</td><td className={cellCls} rowSpan={3}>개인위생</td><td className={cellCls}>위생복장과 이물 복장이 구분하여 보관되고 있는가?</td><td className={cellCls + " text-center"}>{check(hc.hygiene1)}</td></tr>
          <tr><td className={cellCls}>종사자의 건강상태가 양호하고 개인 장신구 등을 소지하지 않으며, 청결한 위생복장을 착용하고 있는가?</td><td className={cellCls + " text-center"}>{check(hc.hygiene2)}</td></tr>
          <tr><td className={cellCls}>위생설비(손 세척기 등) 중 이상이 있는 것이 없으며, 종사자는 위생처리를 하고 입실하는가?</td><td className={cellCls + " text-center"}>{check(hc.hygiene3)}</td></tr>
          <tr><td className={cellCls}>방충방서</td><td className={cellCls}>작업장 입구전등은 밀폐가 잘 이루어져 있으며, 방충시설(방충망 파손 등)에는 이상이 없는가?</td><td className={cellCls + " text-center"}>{check(hc.pest1)}</td></tr>
          <tr><td className={cellCls}>설비</td><td className={cellCls}>작업장 벽, 제조설비(제품과 직접 닿지 않는 부분)에 대한 청소·소독 상태는 양호한가?</td><td className={cellCls + " text-center"}>{check(hc.facility1)}</td></tr>
          <tr><td className={cellCls}>입고보관</td><td className={cellCls}>냉장/냉동창고의 온도는 적절히 관리되고 있는가?{hc.storageTemp ? ` (${hc.storageTemp}℃)` : ""}</td><td className={cellCls + " text-center"}>{check(hc.storage1)}</td></tr>
          <tr><td className={cellCls} rowSpan={4}>공정관리</td><td className={cellCls}>위생복 세탁은 실시하였는가?</td><td className={cellCls + " text-center"}>{check(hc.process1)}</td></tr>
          <tr><td className={cellCls}>냉장창고 내부 청소 상태는 양호한가?</td><td className={cellCls + " text-center"}>{check(hc.process2)}</td></tr>
          <tr><td className={cellCls}>작업장 내부 청소 상태는 양호한가?</td><td className={cellCls + " text-center"}>{check(hc.process3)}</td></tr>
          <tr><td className={cellCls}>제조설비 세척·소독 상태는 양호한가?</td><td className={cellCls + " text-center"}>{check(hc.process4)}</td></tr>

          <tr><td className={secCls} rowSpan={6}>일일{"\n"}(작업중)</td><td className={cellCls}>방충방서</td><td className={cellCls}>작업 중 해충 발견 시 즉시 조치하였는가?</td><td className={cellCls + " text-center"}>{check(hc.pest2)}</td></tr>
          <tr><td className={cellCls}>청소소독</td><td className={cellCls}>작업 중 청소·소독을 실시하고 있는가?</td><td className={cellCls + " text-center"}>{check(hc.cleaning1)}</td></tr>
          <tr><td className={cellCls}>설비</td><td className={cellCls}>제조설비의 작동 상태는 양호한가?</td><td className={cellCls + " text-center"}>{check(hc.facility2)}</td></tr>
          <tr><td className={cellCls}>CCP점검</td><td className={cellCls}>CCP 점검을 실시하였는가?</td><td className={cellCls + " text-center"}>{check(hc.ccp1)}</td></tr>
          <tr><td className={cellCls}>보관</td><td className={cellCls}>완제품 보관 상태는 양호한가?</td><td className={cellCls + " text-center"}>{check(hc.storage2)}</td></tr>
          <tr><td className={cellCls}>입고검수</td><td className={cellCls}>원재료 입고 시 검수를 실시하였는가?</td><td className={cellCls + " text-center"}>{check(hc.inspection1)}</td></tr>
        </tbody>
      </table>
      <table className="w-full border-collapse border border-gray-400 text-sm mt-3">
        <tbody>
          <tr><td className={headCls} style={{width:"120px"}}>특이사항</td><td className={cellCls}>{specialNotes1 || "-"}</td></tr>
          <tr><td className={headCls}>개선조치 및 결과</td><td className={cellCls}>{actionContent || "-"}</td></tr>
          <tr><td className={headCls}>조치자</td><td className={cellCls}>{actionTaker || "-"}</td></tr>
          <tr><td className={headCls}>확인</td><td className={cellCls}>{confirmer || "-"}</td></tr>
        </tbody>
      </table>
    </div>
  );

  // 페이지 2: 이물관리 점검표
  const page2 = (
    <div>
      <TitleRow title="이물관리 점검표" info={<><span className="font-medium">점검일자:</span> {date} &nbsp;&nbsp; <span className="font-medium">점검자:</span> {authorName || inspector || "-"} &nbsp;&nbsp; <span className="text-gray-600">검사방법: 육안검사 | 점검주기: 1회/일</span></>} />
      <table className="w-full border-collapse border border-gray-400 text-sm">
        <thead>
          <tr className="bg-blue-100">
            <th className={headCls} style={{width:"150px"}}>구분</th>
            <th className={headCls}>점검 내용</th>
            <th className={headCls} style={{width:"90px"}}>점검결과</th>
          </tr>
        </thead>
        <tbody>
          <tr><td className={secCls} rowSpan={3}>원료 입고중{"\n"}이물관리</td><td className={cellCls}>원·부재료 입고시 외부의 이물을 제거한 후 입고하는가?</td><td className={cellCls + " text-center"}>{check(fc.material1)}</td></tr>
          <tr><td className={cellCls}>원·부재료 선별시 적절하게 이루어지고 있는가?</td><td className={cellCls + " text-center"}>{check(fc.material2)}</td></tr>
          <tr><td className={cellCls}>원·부재료 전처리시 먼지·결절이물이 혼입되지 않게 배기하는가?</td><td className={cellCls + " text-center"}>{check(fc.material3)}</td></tr>

          <tr><td className={secCls} rowSpan={3}>공정중{"\n"}혼입관리</td><td className={cellCls}>공정중 이용하는 작업도구 중 재질이 낡거나 자재를 사용하지 않는가?</td><td className={cellCls + " text-center"}>{check(fc.process1)}</td></tr>
          <tr><td className={cellCls}>작업장에 개인소지품들을 소지하지 않았으며 지정된 위생복 및 위생화를 착용하였는가?</td><td className={cellCls + " text-center"}>{check(fc.process2)}</td></tr>
          <tr><td className={cellCls}>장갑 등 작업상태가 올바르며 파손 부위는 없는가?</td><td className={cellCls + " text-center"}>{check(fc.process3)}</td></tr>

          <tr><td className={secCls} rowSpan={3}>작업자에 의한{"\n"}이물혼입 관리</td><td className={cellCls}>작업도구, 공구, 필기도구 등은 지정된 위치에 보관되어 있는가?</td><td className={cellCls + " text-center"}>{check(fc.worker1)}</td></tr>
          <tr><td className={cellCls}>작업에 클립, 핀 칼날등 이물혼입 우려가 있는 불필요한 물품이 없는가?</td><td className={cellCls + " text-center"}>{check(fc.worker2)}</td></tr>
          <tr><td className={cellCls}>작업장에 출입하기전 끈끈이 클리너 이용제거 후 입실하는가?</td><td className={cellCls + " text-center"}>{check(fc.worker3)}</td></tr>

          <tr><td className={secCls} rowSpan={3}>제조설비에 의한{"\n"}이물혼입 관리</td><td className={cellCls}>탈락의 우려가 있는 나사류 및 파손 우려가 있는 설비는 없는가?</td><td className={cellCls + " text-center"}>{check(fc.equipment1)}</td></tr>
          <tr><td className={cellCls}>설비등은 주기적으로 세척소독하여 오염물질이 혼입되지 않게 관리하는가?</td><td className={cellCls + " text-center"}>{check(fc.equipment2)}</td></tr>
          <tr><td className={cellCls}>세척소독 및 정비후 나사, 볼트 등의 누락된 곳은 없는가?</td><td className={cellCls + " text-center"}>{check(fc.equipment3)}</td></tr>

          <tr><td className={secCls} rowSpan={2}>해충등{"\n"}혼입관리</td><td className={cellCls}>작업장 출입문, 외부의 벽 등은 틈이나 구멍이 없이 밀폐되어있는가?</td><td className={cellCls + " text-center"}>{check(fc.pest1)}</td></tr>
          <tr><td className={cellCls}>포충등 및 포획장비는 정상작동되며 지정된 위치가 있는가?</td><td className={cellCls + " text-center"}>{check(fc.pest2)}</td></tr>
        </tbody>
      </table>
      <table className="w-full border-collapse border border-gray-400 text-sm mt-3">
        <tbody>
          <tr><td className={headCls} style={{width:"120px"}}>특이사항</td><td className={cellCls}>{specialNotes2 || "-"}</td></tr>
          <tr><td className={headCls}>개선조치 및 결과</td><td className={cellCls}>{foreignActionContent || "-"}</td></tr>
          <tr><td className={headCls}>조치자</td><td className={cellCls}>{foreignActionTaker || "-"}</td></tr>
          <tr><td className={headCls}>확인</td><td className={cellCls}>{foreignConfirmer || "-"}</td></tr>
        </tbody>
      </table>
    </div>
  );

  // 페이지 3: 원재료실 온/습도 점검기록지
  const r1m = th.room1Morning || {};
  const r1a = th.room1Afternoon || {};
  const r2m = th.room2Morning || {};
  const r2a = th.room2Afternoon || {};
  const page3 = (
    <div>
      <TitleRow title="원재료실 온/습도 점검기록지" info={<><span className="font-medium">일자:</span> {date} &nbsp;&nbsp; <span className="font-medium">작성자:</span> {authorName || inspector || "-"}</>} />
      <div className="border border-gray-400 rounded p-3 mb-3 bg-gray-50 text-xs space-y-1">
        <p><span className="font-bold">관리기준:</span> 온도: 1℃~35℃, 습도: 65%이하</p>
        <p><span className="font-bold">점검방법:</span> 생산팀 담당자가 관찰 수치 기록 | 일2회</p>
        <p className="font-bold mt-2">개선조치사항:</p>
        <p>① 관리기준 이탈 시 즉시 원인 파악 및 조치</p>
        <p>② 설비 이상 시 수리 후 재가동</p>
        <p>③ 이상 발생 시 관리자에게 보고</p>
      </div>
      <table className="w-full border-collapse border border-gray-400 text-sm">
        <thead>
          <tr className="bg-blue-100">
            <th className={headCls}>구분</th>
            <th className={headCls}>감시시각</th>
            <th className={headCls}>온도 (℃)</th>
            <th className={headCls}>습도 (%)</th>
            <th className={headCls}>평가</th>
          </tr>
        </thead>
        <tbody>
          <tr><td className={cellCls + " font-medium"}>원재료실1 오전</td><td className={cellCls + " text-center"}>{r1m.time || "-"}</td><td className={cellCls + " text-center"}>{r1m.temp || "-"}</td><td className={cellCls + " text-center"}>{r1m.humidity || "-"}</td><td className={cellCls + " text-center"}>{checkOrDash(r1m.pass)}</td></tr>
          <tr><td className={cellCls + " font-medium"}>원재료실1 오후</td><td className={cellCls + " text-center"}>{r1a.time || "-"}</td><td className={cellCls + " text-center"}>{r1a.temp || "-"}</td><td className={cellCls + " text-center"}>{r1a.humidity || "-"}</td><td className={cellCls + " text-center"}>{checkOrDash(r1a.pass)}</td></tr>
          <tr><td className={cellCls + " font-medium"}>원재료실2 오전</td><td className={cellCls + " text-center"}>{r2m.time || "-"}</td><td className={cellCls + " text-center"}>{r2m.temp || "-"}</td><td className={cellCls + " text-center"}>{r2m.humidity || "-"}</td><td className={cellCls + " text-center"}>{checkOrDash(r2m.pass)}</td></tr>
          <tr><td className={cellCls + " font-medium"}>원재료실2 오후</td><td className={cellCls + " text-center"}>{r2a.time || "-"}</td><td className={cellCls + " text-center"}>{r2a.temp || "-"}</td><td className={cellCls + " text-center"}>{r2a.humidity || "-"}</td><td className={cellCls + " text-center"}>{checkOrDash(r2a.pass)}</td></tr>
        </tbody>
      </table>
      <div className="mt-3 text-sm font-medium">이상 발생 내용</div>
      <table className="w-full border-collapse border border-gray-400 text-sm mt-1">
        <thead><tr className="bg-gray-50"><th className={headCls}>발생내용</th><th className={headCls}>조치내용 및 결과</th><th className={headCls}>완료일자</th><th className={headCls}>조치자</th><th className={headCls}>확인자</th></tr></thead>
        <tbody><tr><td className={cellCls}>{tempIssues.issueDescription || actionContent || "-"}</td><td className={cellCls}>{tempIssues.actionTaken || actionContent || "-"}</td><td className={cellCls}>{tempIssues.completionDate || date}</td><td className={cellCls}>{tempIssues.actionBy || actionTaker || "-"}</td><td className={cellCls}>{tempIssues.confirmedBy || confirmer || "-"}</td></tr></tbody>
      </table>
    </div>
  );

  // 페이지 4: 급속냉동고/냉동고 온도 점검기록지
  const fm = ft.morning || {};
  const fa = ft.afternoon || {};
  const page4 = (
    <div>
      <TitleRow title="급속냉동고 / 냉동고 온도 점검기록지" info={<><span className="font-medium">일자:</span> {date} &nbsp;&nbsp; <span className="font-medium">작성자:</span> {authorName || inspector || "-"}</>} />
      <div className="border border-gray-400 rounded p-3 mb-3 bg-gray-50 text-xs space-y-1">
        <p><span className="font-bold">관리기준:</span> 급속냉동고: -27℃ 이하, 냉동고: -18℃ 이하</p>
        <p><span className="font-bold">점검방법:</span> 생산팀 담당자가 관찰 수치 기록 | 일2회</p>
        <p className="font-bold mt-2">개선조치사항:</p>
        <p>① 관리기준 이탈 시 즉시 원인 파악 및 조치</p>
        <p>② 설비 이상 시 수리 후 재가동</p>
        <p>③ 이상 발생 시 관리자에게 보고</p>
      </div>
      <table className="w-full border-collapse border border-gray-400 text-sm">
        <thead>
          <tr className="bg-blue-100">
            <th className={headCls}>구분</th>
            <th className={headCls}>감시시각</th>
            <th className={headCls}>급속냉동고 (℃)</th>
            <th className={headCls}>냉동고 (℃)</th>
            <th className={headCls}>평가</th>
          </tr>
        </thead>
        <tbody>
          <tr><td className={cellCls + " font-medium"}>오전</td><td className={cellCls + " text-center"}>{fm.time || "-"}</td><td className={cellCls + " text-center"}>{fm.rapidFreezer || "-"}</td><td className={cellCls + " text-center"}>{fm.freezer || "-"}</td><td className={cellCls + " text-center"}>{checkOrDash(fm.pass)}</td></tr>
          <tr><td className={cellCls + " font-medium"}>오후</td><td className={cellCls + " text-center"}>{fa.time || "-"}</td><td className={cellCls + " text-center"}>{fa.rapidFreezer || "-"}</td><td className={cellCls + " text-center"}>{fa.freezer || "-"}</td><td className={cellCls + " text-center"}>{checkOrDash(fa.pass)}</td></tr>
        </tbody>
      </table>
      <div className="mt-3 text-sm font-medium">이상 발생 내용</div>
      <table className="w-full border-collapse border border-gray-400 text-sm mt-1">
        <thead><tr className="bg-gray-50"><th className={headCls}>발생내용</th><th className={headCls}>조치내용 및 결과</th><th className={headCls}>완료일자</th><th className={headCls}>조치자</th><th className={headCls}>확인자</th></tr></thead>
        <tbody><tr><td className={cellCls}>{freezerIssues.issueDescription || actionContent || "-"}</td><td className={cellCls}>{freezerIssues.actionTaken || actionContent || "-"}</td><td className={cellCls}>{freezerIssues.completionDate || date}</td><td className={cellCls}>{freezerIssues.actionBy || actionTaker || "-"}</td><td className={cellCls}>{freezerIssues.confirmedBy || confirmer || "-"}</td></tr></tbody>
      </table>
    </div>
  );

  // 페이지 5: 원재료 냉장고 온도 점검 기록지
  const rm = rt.morning || {};
  const ra = rt.afternoon || {};
  const page5 = (
    <div>
      <TitleRow title="원재료 냉장고 온도 점검 기록지" info={<><span className="font-medium">일자:</span> {date} &nbsp;&nbsp; <span className="font-medium">작성자:</span> {authorName || inspector || "-"}</>} />
      <div className="border border-gray-400 rounded p-3 mb-3 bg-gray-50 text-xs space-y-1">
        <p><span className="font-bold">관리기준:</span> 0℃~10℃</p>
        <p><span className="font-bold">점검방법:</span> 생산팀 담당자가 관찰 수치 기록 | 일2회</p>
        <p className="font-bold mt-2">개선조치사항:</p>
        <p>① 관리기준 이탈 시 즉시 원인 파악 및 조치</p>
        <p>② 설비 이상 시 수리 후 재가동</p>
        <p>③ 이상 발생 시 관리자에게 보고</p>
      </div>
      <table className="w-full border-collapse border border-gray-400 text-sm">
        <thead>
          <tr className="bg-blue-100">
            <th className={headCls}>구분</th>
            <th className={headCls}>감시시각</th>
            <th className={headCls}>온도 (℃)</th>
            <th className={headCls}>평가</th>
          </tr>
        </thead>
        <tbody>
          <tr><td className={cellCls + " font-medium"}>오전</td><td className={cellCls + " text-center"}>{rm.time || "-"}</td><td className={cellCls + " text-center"}>{rm.temp || "-"}</td><td className={cellCls + " text-center"}>{checkOrDash(rm.pass)}</td></tr>
          <tr><td className={cellCls + " font-medium"}>오후</td><td className={cellCls + " text-center"}>{ra.time || "-"}</td><td className={cellCls + " text-center"}>{ra.temp || "-"}</td><td className={cellCls + " text-center"}>{checkOrDash(ra.pass)}</td></tr>
        </tbody>
      </table>
      <div className="mt-3 text-sm font-medium">이상 발생 내용</div>
      <table className="w-full border-collapse border border-gray-400 text-sm mt-1">
        <thead><tr className="bg-gray-50"><th className={headCls}>일시</th><th className={headCls}>발생내용</th><th className={headCls}>조치내용 및 결과</th><th className={headCls}>완료일자</th><th className={headCls}>조치자</th><th className={headCls}>확인자</th></tr></thead>
        <tbody><tr><td className={cellCls}>{refIssues.issueDatetime || date}</td><td className={cellCls}>{refIssues.issueDescription || actionContent || "-"}</td><td className={cellCls}>{refIssues.actionTaken || actionContent || "-"}</td><td className={cellCls}>{refIssues.completionDate || date}</td><td className={cellCls}>{refIssues.actionBy || actionTaker || "-"}</td><td className={cellCls}>{refIssues.confirmedBy || confirmer || "-"}</td></tr></tbody>
      </table>
    </div>
  );

  return [page1, page2, page3, page4, page5];
}

// ============================================================================
// 종사자 건강상태 확인 일지 전용 렌더러
// ============================================================================
export function renderEmployeeHealthCheck(data: any) {
  const questions = data?.questions || [];
  const employeeRows = data?.employeeRows || [];
  const checkDate = data?.checkDate || "";
  const specialNotes = data?.specialNotes || "";
  const writerName = data?.approval?.writerName || "";

  return (
    <div>
      <div className="text-center mb-4">
        <h2 className="text-xl font-bold">작업장 출입 전 종사자 건강상태 확인 일지</h2>
      </div>
      <div className="text-sm mb-3 space-y-0.5">
        <p>★ 작업 시작 전 종사자 본인이 직접 아래 질문(1~5번)에 대한 답변 작성</p>
        <p className="ml-4">→ 해당하는 경우 "O" / 해당하지 않는 경우 "X" 기재</p>
        <p>★ 작업 시작 전 팀장은 종사자가 작성한 내용 확인</p>
        <p className="ml-4">→ "O" 표시한 항목이 있는 경우, 팀장 확인 후 당일 작업 여부 결정</p>
      </div>
      <div className="flex items-center gap-8 mb-3 text-sm border border-gray-400 p-2">
        <div><span className="font-medium bg-gray-100 px-2 py-0.5">작성일자</span> {checkDate}</div>
        <div><span className="font-medium bg-gray-100 px-2 py-0.5">작성자</span> {writerName || "-"}</div>
      </div>
      <div className="text-center font-bold text-sm mb-1">질문내용</div>
      <table className="w-full border-collapse border border-gray-400 text-[10px]">
        <thead>
          <tr className="bg-gray-50">
            <th rowSpan={2} className="border border-gray-400 px-1 py-1 w-20">종사자명</th>
            {questions.map((q: any, idx: number) => (
              <th key={idx} colSpan={2} className="border border-gray-400 px-1 py-1 text-center">{q.text || `질문 ${idx + 1}`}</th>
            ))}
          </tr>
          <tr className="bg-gray-50">
            {questions.map((_: any, idx: number) => (
              <React.Fragment key={idx}>
                <th className="border border-gray-400 px-1 py-0.5 text-center w-6">O</th>
                <th className="border border-gray-400 px-1 py-0.5 text-center w-6">X</th>
              </React.Fragment>
            ))}
          </tr>
        </thead>
        <tbody>
          {employeeRows.length > 0 ? employeeRows.map((row: any, idx: number) => (
            <tr key={idx}>
              <td className="border border-gray-400 px-1 py-0.5 text-center">{row.name || `종사자 ${idx + 1}`}</td>
              {questions.map((q: any, qIdx: number) => {
                const answer = row.answers?.[q.id] || "X";
                return (
                  <React.Fragment key={qIdx}>
                    <td className="border border-gray-400 px-1 py-0.5 text-center">{answer === "O" ? "✓" : ""}</td>
                    <td className="border border-gray-400 px-1 py-0.5 text-center">{answer === "X" ? "✓" : ""}</td>
                  </React.Fragment>
                );
              })}
            </tr>
          )) : (
            <tr><td colSpan={1 + questions.length * 2} className="border border-gray-400 px-2 py-3 text-center text-gray-400">기록 없음</td></tr>
          )}
        </tbody>
      </table>
      {specialNotes && <div className="mt-3 border border-gray-400 p-2 text-sm"><span className="font-bold">특이사항: </span>{specialNotes}</div>}
    </div>
  );
}

// ============================================================================
// 에어컴프레서 유지보수 기록
// ============================================================================
export function renderAirCompressorMaintenance(data: any) {
  const rows = data?.rows || [];
  return (
    <div>
      <div className="text-center mb-4">
        <h2 className="text-xl font-bold">에어 콤프레샤</h2>
        <h3 className="text-base mt-1">윤활유(식품오일, H1급) 및 에어 크리너 세척, 소독 점검표</h3>
      </div>
      <div className="border border-gray-400 rounded p-3 mb-4 bg-gray-50 text-xs">
        <p className="font-bold mb-1">관리 기준</p>
        <ul className="list-disc list-inside space-y-0.5">
          <li>에어 콤프레샤 윤활유는 식품오일(H1급)으로 한다.</li>
          <li>식품용 윤활유는 매년 2회. 6월, 12월 첫째주 월요일에 정기적으로 교환한다.</li>
          <li>에어 크리너는 매월 3개월 마다. 첫째주 월요일에 정기적으로 세척, 소독한다.</li>
        </ul>
      </div>
      <table className="w-full border-collapse border border-gray-400 text-sm">
        <thead>
          <tr className="bg-blue-50">
            <th className="border border-gray-400 px-2 py-1">월 일</th>
            <th className="border border-gray-400 px-2 py-1">식품오일 교환</th>
            <th className="border border-gray-400 px-2 py-1">에어크리너 세척</th>
            <th className="border border-gray-400 px-2 py-1">작업자</th>
          </tr>
        </thead>
        <tbody>
          {rows.length > 0 ? rows.map((row: any, idx: number) => (
            <tr key={idx}>
              <td className="border border-gray-400 px-2 py-1 text-center">{row.date || "-"}</td>
              <td className="border border-gray-400 px-2 py-1 text-center">{row.oilChange ? "✓" : "-"}</td>
              <td className="border border-gray-400 px-2 py-1 text-center">{row.cleanerWash ? "✓" : "-"}</td>
              <td className="border border-gray-400 px-2 py-1 text-center">{row.worker || "-"}</td>
            </tr>
          )) : (<tr><td colSpan={4} className="border border-gray-400 px-2 py-4 text-center text-gray-400">기록 없음</td></tr>)}
        </tbody>
      </table>
    </div>
  );
}

// ============================================================================
// 설비 점검 기록
// ============================================================================
export function renderEquipmentInspection(data: any) {
  const items = data?.data || data?.items || [];
  return (
    <div>
      <div className="text-center mb-4"><h2 className="text-xl font-bold">설비 점검 기록</h2></div>
      <table className="w-full border-collapse border border-gray-400 text-sm">
        <thead><tr className="bg-blue-50">
          <th className="border border-gray-400 px-2 py-1">No.</th>
          <th className="border border-gray-400 px-2 py-1">설비명</th>
          <th className="border border-gray-400 px-2 py-1">외관</th>
          <th className="border border-gray-400 px-2 py-1">작동</th>
          <th className="border border-gray-400 px-2 py-1">청결</th>
          <th className="border border-gray-400 px-2 py-1">안전</th>
          <th className="border border-gray-400 px-2 py-1">판정</th>
        </tr></thead>
        <tbody>
          {items.length > 0 ? items.map((item: any, idx: number) => (
            <tr key={idx}>
              <td className="border border-gray-400 px-2 py-1 text-center">{idx + 1}</td>
              <td className="border border-gray-400 px-2 py-1">{item.equipmentName || item["설비명"] || "-"}</td>
              <td className="border border-gray-400 px-2 py-1 text-center">{item.appearance || item["외관상태"] || "-"}</td>
              <td className="border border-gray-400 px-2 py-1 text-center">{item.operation || item["작동상태"] || "-"}</td>
              <td className="border border-gray-400 px-2 py-1 text-center">{item.cleanliness || item["청결상태"] || "-"}</td>
              <td className="border border-gray-400 px-2 py-1 text-center">{item.safety || item["안전장치"] || "-"}</td>
              <td className="border border-gray-400 px-2 py-1 text-center">{item.result || item["판정"] || "-"}</td>
            </tr>
          )) : (<tr><td colSpan={7} className="border border-gray-400 px-2 py-4 text-center text-gray-400">기록 없음</td></tr>)}
        </tbody>
      </table>
    </div>
  );
}

// ============================================================================
// 온·습도 점검표
// ============================================================================
export function renderTemperatureHumidityCheck(data: any) {
  const records = data?.spaceRows || data?.records || data?.rows || data?.data || [];
  return (
    <div>
      <div className="text-center mb-4"><h2 className="text-xl font-bold">온·습도 점검표</h2></div>
      <table className="w-full border-collapse border border-gray-400 text-sm">
        <thead><tr className="bg-blue-50">
          <th className="border border-gray-400 px-2 py-1">No.</th>
          <th className="border border-gray-400 px-2 py-1">구역</th>
          <th className="border border-gray-400 px-2 py-1">위치</th>
          <th className="border border-gray-400 px-2 py-1">온도(℃)</th>
          <th className="border border-gray-400 px-2 py-1">기준</th>
          <th className="border border-gray-400 px-2 py-1">판정</th>
        </tr></thead>
        <tbody>
          {records.length > 0 ? records.map((r: any, idx: number) => (
            <tr key={idx}>
              <td className="border border-gray-400 px-2 py-1 text-center">{idx + 1}</td>
              <td className="border border-gray-400 px-2 py-1">{r.area || r.location || "-"}</td>
              <td className="border border-gray-400 px-2 py-1 text-center">{r.location || "-"}</td>
              <td className="border border-gray-400 px-2 py-1 text-center">{r.tempResult ?? r.temperature ?? "-"}</td>
              <td className="border border-gray-400 px-2 py-1 text-center">{r.tempStandard || r.standard || "-"}</td>
              <td className="border border-gray-400 px-2 py-1 text-center">{r.judgment || r.result || "-"}</td>
            </tr>
          )) : (<tr><td colSpan={6} className="border border-gray-400 px-2 py-4 text-center text-gray-400">기록 없음</td></tr>)}
        </tbody>
      </table>
    </div>
  );
}

// ============================================================================
// 공중낙하세균 검사 성적서
// ============================================================================
export function renderAirborneBacteriaTest(data: any) {
  const rows = data?.rows || data?.data || [];
  return (
    <div>
      <div className="text-center mb-4"><h2 className="text-xl font-bold">공중낙하세균 검사 성적서</h2></div>
      <table className="w-full border-collapse border border-gray-400 text-sm">
        <thead><tr className="bg-blue-50">
          <th className="border border-gray-400 px-2 py-1">No.</th>
          <th className="border border-gray-400 px-2 py-1">검사장소</th>
          <th className="border border-gray-400 px-2 py-1">검사일</th>
          <th className="border border-gray-400 px-2 py-1">노출시간</th>
          <th className="border border-gray-400 px-2 py-1">세균수(CFU)</th>
          <th className="border border-gray-400 px-2 py-1">기준</th>
          <th className="border border-gray-400 px-2 py-1">판정</th>
        </tr></thead>
        <tbody>
          {rows.length > 0 ? rows.map((r: any, idx: number) => (
            <tr key={idx}>
              <td className="border border-gray-400 px-2 py-1 text-center">{idx + 1}</td>
              <td className="border border-gray-400 px-2 py-1">{r.location || "-"}</td>
              <td className="border border-gray-400 px-2 py-1 text-center">{r.inspectionDate || r.date || "-"}</td>
              <td className="border border-gray-400 px-2 py-1 text-center">{r.exposureTime || "-"}</td>
              <td className="border border-gray-400 px-2 py-1 text-center">{r.bacteriaCount || r.result || r.cfu || "-"}</td>
              <td className="border border-gray-400 px-2 py-1 text-center">{r.criteria || r.standard || "-"}</td>
              <td className="border border-gray-400 px-2 py-1 text-center">{r.result || r.judgment || "-"}</td>
            </tr>
          )) : (<tr><td colSpan={7} className="border border-gray-400 px-2 py-4 text-center text-gray-400">기록 없음</td></tr>)}
        </tbody>
      </table>
    </div>
  );
}

// ============================================================================
// 교육훈련 기록
// ============================================================================
export function renderTrainingLog(data: any) {
  const formData = data || {};
  return (
    <div>
      <div className="text-center mb-4"><h2 className="text-xl font-bold">교육훈련 기록</h2></div>
      <table className="w-full border-collapse border border-gray-400 text-sm mb-4">
        <tbody>
          {formData.date && <tr><td className="border border-gray-400 px-3 py-2 bg-gray-50 font-medium w-1/4">교육일</td><td className="border border-gray-400 px-3 py-2">{formData.date}</td></tr>}
          {formData.title && <tr><td className="border border-gray-400 px-3 py-2 bg-gray-50 font-medium">교육명</td><td className="border border-gray-400 px-3 py-2">{formData.title}</td></tr>}
          {formData.instructor && <tr><td className="border border-gray-400 px-3 py-2 bg-gray-50 font-medium">교육자</td><td className="border border-gray-400 px-3 py-2">{formData.instructor}</td></tr>}
          {formData.content && <tr><td className="border border-gray-400 px-3 py-2 bg-gray-50 font-medium">교육내용</td><td className="border border-gray-400 px-3 py-2 whitespace-pre-wrap">{formData.content}</td></tr>}
        </tbody>
      </table>
    </div>
  );
}
