import {mysqlTable, varchar, decimal, timestamp, text, mysqlEnum, tinyint, int, bigint} from "drizzle-orm/mysql-core";
import { tenants } from './schema_main';

// CCP 한계기준 테이블
export const ccpLimits = mysqlTable('ccp_limits', {
  id: int('id').primaryKey().autoincrement(),
  tenantId: int('tenant_id').notNull().references(() => tenants.id),
  ccpType: varchar('ccp_type', { length: 10 }).notNull(),
  productName: varchar('product_name', { length: 255 }).notNull(),
  heatingTimeMinMin: int('heating_time_min_min'), // 가열 시간 최소 (분)
  heatingTimeMinMax: int('heating_time_min_max'), // 가열 시간 최대 (분)
  pressureMpaMin: decimal('pressure_mpa_min', { precision: 5, scale: 2 }), // 압력 최소 (Mpa)
  temperatureCMin: decimal('temperature_c_min', { precision: 5, scale: 2 }), // 온도 최소 (℃)
  monitoringFrequency: text('monitoring_frequency'), // 모니터링 주기
  createdAt: timestamp('created_at').defaultNow(),
  updatedAt: timestamp('updated_at').defaultNow().onUpdateNow(),
});

// CCP 모니터링 기록 테이블 (통합)
export const ccpMonitoringRecords = mysqlTable('ccp_monitoring_records', {
  id: int('id').primaryKey().autoincrement(),
  tenantId: int('tenant_id').notNull().references(() => tenants.id),
  recordDate: timestamp('record_date').notNull(), // 기록 일시
  ccpType: varchar('ccp_type', { length: 10 }).notNull(), // CCP 유형
  batchId: varchar('batch_id', { length: 255 }), // 배치 ID
  productName: varchar('product_name', { length: 255 }).notNull(), // 제품명
  measurementTime: varchar('measurement_time', { length: 10 }), // 측정 시각 (HH:mm)
  
  // 가열 공정 관련 필드
  heatingTimeMin: int('heating_time_min'), // 가열 시간 (분)
  pressureMpa: decimal('pressure_mpa', { precision: 5, scale: 2 }), // 압력 (Mpa) - CCP-1B만
  temperatureC: decimal('temperature_c', { precision: 5, scale: 2 }), // 온도 (℃)
  inputAmountKg: decimal('input_amount_kg', { precision: 10, scale: 2 }), // 투입량 (kg)
  tempEdgeC: decimal('temp_edge_c', { precision: 5, scale: 2 }), // 품온 모서리 (℃) - CCP-1B만
  tempCenterC: decimal('temp_center_c', { precision: 5, scale: 2 }), // 품온 중심부 (℃) - CCP-1B만
  
  // 금속검출 공정 관련 필드 (CCP-4P)
  metalDetectorId: varchar('metal_detector_id', { length: 100 }), // 금속검출기 ID
  sensitivitySetting: int('sensitivity_setting'), // 감도 설정
  feTestPiecePass: varchar('fe_test_piece_pass', { length: 10 }), // Fe 시편 테스트 결과 (O/X)
  stsTestPiecePass: varchar('sts_test_piece_pass', { length: 10 }), // STS 시편 테스트 결과 (O/X)
  productOnlyPass: varchar('product_only_pass', { length: 10 }), // 제품만 통과 (O/X)
  feProductPass: varchar('fe_product_pass', { length: 10 }), // Fe+제품 통과 (O/X)
  stsProductPass: varchar('sts_product_pass', { length: 10 }), // STS+제품 통과 (O/X)
  passedQuantity: int('passed_quantity'), // 통과량 (개)
  detectedQuantity: int('detected_quantity'), // 검출량 (개)
  
  // 공통 필드
  passFail: mysqlEnum('pass_fail', ['적합', '부적합']).notNull(), // 적합/부적합
  operatorId: int('operator_id').notNull(), // 작업자 ID
  reviewerId: int('reviewer_id'), // 승인자 ID
  
  // 자동 기입 관련 필드
  source: varchar('source', { length: 50 }).default('manual'), // manual, auto, sensor
  autoGenerated: tinyint('auto_generated').default(0), // 자동 생성 여부
  equipmentId: int('equipment_id'), // 설비 ID (자동 생성 시 참조)
  
  // 이탈 및 개선조치
  deviationContent: text('deviation_content'), // 이탈 내용
  correctiveAction: text('corrective_action'), // 개선조치 및 결과
  correctiveActionBy: int('corrective_action_by'), // 조치자 ID
  confirmedBy: int('confirmed_by'), // 확인자 ID
  
  createdAt: timestamp('created_at').defaultNow(),
  updatedAt: timestamp('updated_at').defaultNow().onUpdateNow(),
});

// 금속검출 테스트 기록 테이블
export const metalDetectionTests = mysqlTable('metal_detection_tests', {
  id: int('id').primaryKey().autoincrement(),
  tenantId: int('tenant_id').notNull().references(() => tenants.id),
  testDate: timestamp('test_date').notNull(), // 테스트 일자
  productCategory: varchar('product_category', { length: 255 }).notNull(), // 제품 카테고리
  metalType: mysqlEnum('metal_type', ['Fe', 'STS']).notNull(), // 금속 유형
  sizeMm: decimal('size_mm', { precision: 3, scale: 1 }).notNull(), // 금속 크기 (mmΦ)
  position: mysqlEnum('position', ['좌상', '좌하', '중상', '중하', '우상', '우하']).notNull(), // 위치
  testResults: text('test_results').notNull(), // 테스트 결과 1-10회 (JSON)
  detectionRate: int('detection_rate').notNull(), // 검출율 (%)
  testerId: int('tester_id').notNull(), // 테스트 수행자 ID
  reviewerId: int('reviewer_id'), // 확인자 ID
  createdAt: timestamp('created_at').defaultNow(),
  updatedAt: timestamp('updated_at').defaultNow().onUpdateNow(),
});

// 금속검출 기준 테이블
export const metalDetectionStandards = mysqlTable('metal_detection_standards', {
  id: int('id').primaryKey().autoincrement(),
  tenantId: int('tenant_id').notNull().references(() => tenants.id),
  productCategory: varchar('product_category', { length: 255 }).notNull(), // 제품 카테고리
  metalType: mysqlEnum('metal_type', ['Fe', 'STS']).notNull(), // 금속 유형
  sizeMm: decimal('size_mm', { precision: 3, scale: 1 }).notNull(), // 금속 크기 (mmΦ)
  detectionRate: int('detection_rate').notNull(), // 검출율 (%)
  sensitivitySetting: int('sensitivity_setting').notNull(), // 감도 설정값
  createdAt: timestamp('created_at').defaultNow(),
  updatedAt: timestamp('updated_at').defaultNow().onUpdateNow(),
});

// 검증 기록 테이블
export const verificationRecords = mysqlTable('verification_records', {
  id: int('id').primaryKey().autoincrement(),
  tenantId: int('tenant_id').notNull().references(() => tenants.id),
  verificationDate: timestamp('verification_date').notNull(), // 검증 일자
  verificationType: mysqlEnum('verification_type', ['최초', '일상', '정기', '특별']).notNull(), // 검증 유형
  verifierId: int('verifier_id').notNull(), // 검증원 ID
  findings: text('findings'), // 검증 결과
  nonconformities: text('nonconformities'), // 부적합 사항
  correctiveActions: text('corrective_actions'), // 개선조치
  approvedBy: int('approved_by'), // 승인자 ID
  createdAt: timestamp('created_at').defaultNow(),
  updatedAt: timestamp('updated_at').defaultNow().onUpdateNow(),
});

// 위해요소 분석 테이블
export const hazardAnalysis = mysqlTable('hazard_analysis', {
  id: int('id').primaryKey().autoincrement(),
  tenantId: int('tenant_id').notNull().references(() => tenants.id),
  processName: varchar('process_name', { length: 255 }).notNull(), // 공정명
  hazardCategory: mysqlEnum('hazard_category', ['생물학적', '화학적', '물리적']).notNull(), // 위해요소 구분
  hazardName: varchar('hazard_name', { length: 255 }).notNull(), // 명칭
  cause: text('cause'), // 발생원인
  severity: int('severity').notNull(), // 심각성 (1-3)
  occurrence: int('occurrence').notNull(), // 발생가능성 (1-3)
  riskLevel: int('risk_level').notNull(), // 종합평가 (1-3)
  preventionMeasures: text('prevention_measures'), // 예방조치 및 관리방법
  productCategory: varchar('product_category', { length: 255 }), // 제품 카테고리
  createdAt: timestamp('created_at').defaultNow(),
  updatedAt: timestamp('updated_at').defaultNow().onUpdateNow(),
});

// 제품 설명서 테이블
export const productSpecifications = mysqlTable('product_specifications', {
  id: int('id').primaryKey().autoincrement(),
  tenantId: int('tenant_id').notNull().references(() => tenants.id),
  productName: varchar('product_name', { length: 255 }).notNull(), // 제품명
  foodType: varchar('food_type', { length: 255 }), // 식품의 유형
  appearance: text('appearance'), // 성상
  reportDate: timestamp('report_date'), // 품목제조보고 연월일
  reportNumber: varchar('report_number', { length: 255 }), // 품목제조보고 번호
  authorId: int('author_id'), // 작성자 ID
  authorDate: timestamp('author_date'), // 작성연월일
  ingredients: text('ingredients'), // 성분배합비율 (JSON)
  packagingSizes: text('packaging_sizes'), // 제조(포장) 단위 (JSON)
  
  // 완제품 규격
  biologicalStandards: text('biological_standards'), // 생물학적 규격 (JSON)
  chemicalStandards: text('chemical_standards'), // 화학적 규격 (JSON)
  physicalStandards: text('physical_standards'), // 물리적 규격 (JSON)
  
  // 보관·유통 정보
  storageConditions: varchar('storage_conditions', { length: 255 }), // 보관 조건
  transportConditions: varchar('transport_conditions', { length: 255 }), // 운송 조건
  distributionConditions: varchar('distribution_conditions', { length: 255 }), // 유통 조건
  
  // 제품 정보
  productUsage: text('product_usage'), // 제품용도
  consumptionMethod: text('consumption_method'), // 섭취방법
  expiryPeriod: varchar('expiry_period', { length: 255 }), // 소비기한
  
  // 포장 정보
  packagingMethod: text('packaging_method'), // 포장방법
  packagingMaterial: text('packaging_material'), // 포장재질
  
  // 표시사항
  labelingInfo: text('labeling_info'), // 표시사항
  
  createdAt: timestamp('created_at').defaultNow(),
  updatedAt: timestamp('updated_at').defaultNow().onUpdateNow(),
});


// 제품별 CCP 한계기준 스펙 테이블
export const productCcpSpecs = mysqlTable('product_ccp_specs', {
  id: bigint('id', { mode: 'number' }).primaryKey().autoincrement(),
  tenantId: int('tenant_id').notNull().default(1),
  productId: bigint('product_id', { mode: 'number' }).notNull(),
  ccpType: varchar('ccp_type', { length: 50 }).notNull(),
  minTempC: decimal('min_temp_c', { precision: 5, scale: 1 }),
  maxTempC: decimal('max_temp_c', { precision: 5, scale: 1 }),
  minDurationMin: int('min_duration_min'),
  maxDurationMin: int('max_duration_min'),
  minPressureBar: decimal('min_pressure_bar', { precision: 5, scale: 2 }),
  maxPressureBar: decimal('max_pressure_bar', { precision: 5, scale: 2 }),
  feSensitivity: decimal('fe_sensitivity', { precision: 5, scale: 2 }),
  susSensitivity: decimal('sus_sensitivity', { precision: 5, scale: 2 }),
  description: text('description'),
  isActive: tinyint('is_active').notNull().default(1),
  createdAt: timestamp('created_at').defaultNow(),
  updatedAt: timestamp('updated_at').defaultNow().onUpdateNow(),
  createdBy: bigint('created_by', { mode: 'number' }),
});

// CCP 공정 그룹 (설비 병렬 그룹화 + 법적 한계치)
export const ccpProcessGroups = mysqlTable('ccp_process_groups', {
  id: int('id').primaryKey().autoincrement(),
  tenantId: int('tenant_id').notNull().default(1),
  name: varchar('name', { length: 255 }).notNull(),
  ccpType: varchar('ccp_type', { length: 50 }).notNull(),
  description: text('description'),
  temperatureMin: decimal('temperature_min', { precision: 5, scale: 2 }),
  temperatureMax: decimal('temperature_max', { precision: 5, scale: 2 }),
  timeMin: int('time_min'),
  timeMax: int('time_max'),
  pressureMin: decimal('pressure_min', { precision: 5, scale: 2 }),
  pressureMax: decimal('pressure_max', { precision: 5, scale: 2 }),
  phMin: decimal('ph_min', { precision: 4, scale: 2 }),
  phMax: decimal('ph_max', { precision: 4, scale: 2 }),
  monitoringMethod: text('monitoring_method'),
  correctiveAction: text('corrective_action'),
  sortOrder: int('sort_order').default(0),
  status: varchar('status', { length: 50 }).notNull().default('active'),
  createdAt: timestamp('created_at').defaultNow().notNull(),
  updatedAt: timestamp('updated_at').defaultNow().onUpdateNow().notNull(),
});

// 공정 그룹에 속한 설비 (병렬 그룹) - tenant_id 추가
export const ccpProcessGroupEquipments = mysqlTable('ccp_process_group_equipments', {
  id: int('id').primaryKey().autoincrement(),
  tenantId: int('tenant_id').notNull().default(1),  // ★ 테넌트 격리 추가
  processGroupId: int('process_group_id').notNull(),
  equipmentId: int('equipment_id').notNull(),
  sortOrder: int('sort_order').default(0),
  createdAt: timestamp('created_at').defaultNow().notNull(),
});

// ★ 신규: 제품 ↔ 공정그룹 고정 매핑 (병렬 제품군)
export const ccpProcessGroupProducts = mysqlTable('ccp_process_group_products', {
  id: int('id').primaryKey().autoincrement(),
  tenantId: int('tenant_id').notNull().default(1),
  processGroupId: int('process_group_id').notNull(),  // ccp_process_groups.id
  productId: int('product_id').notNull(),              // h_products_v2.id 또는 제품 PK
  createdAt: timestamp('created_at').defaultNow().notNull(),
});

// ★ 신규: 공정별 시간 프로파일 (운영시간 관리)
// 설기류/약식류 등 법적 CL 타입별 시간 프로파일
export const ccpTimeProfiles = mysqlTable('ccp_time_profiles', {
  id: int('id').primaryKey().autoincrement(),
  tenantId: int('tenant_id').notNull().default(1),
  processType: varchar('process_type', { length: 50 }).notNull(),  // MIX | STEAM | OVEN
  profileName: varchar('profile_name', { length: 255 }).notNull(), // 설기류, 약식류, 기타 등
  timeMinutes: int('time_minutes').notNull(),                       // 운영 시간 (분)
  ccpProcessGroupId: int('ccp_process_group_id'),                   // 법적 CL 타입과 연결
  description: text('description'),
  isActive: tinyint('is_active').notNull().default(1),
  createdAt: timestamp('created_at').defaultNow().notNull(),
  updatedAt: timestamp('updated_at').defaultNow().onUpdateNow().notNull(),
});

// ★ 신규: 제품별 고정 시간 프로파일 매핑
// 제품마다 공정별 고정 시간을 매핑 (핵심 테이블)
export const ccpProductTimeProfileMap = mysqlTable('ccp_product_time_profile_map', {
  id: int('id').primaryKey().autoincrement(),
  tenantId: int('tenant_id').notNull().default(1),
  productId: int('product_id').notNull(),                           // h_products_v2.id
  processType: varchar('process_type', { length: 50 }).notNull(),  // 보통 STEAM만 먼저 적용
  timeProfileId: int('time_profile_id').notNull(),                  // ccp_time_profiles.id
  createdAt: timestamp('created_at').defaultNow().notNull(),
  updatedAt: timestamp('updated_at').defaultNow().onUpdateNow().notNull(),
});
