import { mysqlTable, bigint, int, varchar, decimal, text, timestamp, index, uniqueIndex } from "drizzle-orm/mysql-core";

// 일별 원료수불 상세
export const materialLedgerDaily = mysqlTable("material_ledger_daily", {
  id: bigint("id", { mode: "number" }).primaryKey().autoincrement(),
  tenantId: int("tenant_id").notNull().default(2),
  materialId: bigint("material_id", { mode: "number" }).notNull(),
  ledgerDate: varchar("ledger_date", { length: 10 }).notNull(),
  receivingQty: decimal("receiving_qty", { precision: 12, scale: 3 }).default("0"),
  usageQty: decimal("usage_qty", { precision: 12, scale: 3 }).default("0"),
  adjustmentQty: decimal("adjustment_qty", { precision: 12, scale: 3 }).default("0"),
  runningStock: decimal("running_stock", { precision: 12, scale: 3 }).default("0"),
  notes: text("notes"),
  source: varchar("source", { length: 50 }).default("auto"),
  createdAt: timestamp("created_at").defaultNow(),
  updatedAt: timestamp("updated_at").defaultNow().onUpdateNow(),
}, (table) => ({
  // ★ ON DUPLICATE KEY UPDATE 동작을 위한 UNIQUE 제약
  uqTenantMaterialDate: uniqueIndex("uq_mld_tenant_material_date").on(table.tenantId, table.materialId, table.ledgerDate),
  tenantDateIdx: index("idx_tenant_date").on(table.tenantId, table.ledgerDate),
  materialDateIdx: index("idx_material_date").on(table.materialId, table.ledgerDate),
}));

// 월별 원료수불부 (집계) - 일별 컬럼 포함
export const materialLedgerMonthly = mysqlTable("material_ledger_monthly", {
  id: bigint("id", { mode: "number" }).primaryKey().autoincrement(),
  tenantId: int("tenant_id").notNull().default(2),
  materialId: bigint("material_id", { mode: "number" }).notNull(),
  yearMonth: varchar("year_month", { length: 7 }).notNull(),
  prevStock: decimal("prev_stock", { precision: 12, scale: 3 }).default("0"),
  receivingTotal: decimal("receiving_total", { precision: 12, scale: 3 }).default("0"),
  receivingDay01: decimal("receiving_day_01", { precision: 12, scale: 3 }).default("0"),
  receivingDay02: decimal("receiving_day_02", { precision: 12, scale: 3 }).default("0"),
  receivingDay03: decimal("receiving_day_03", { precision: 12, scale: 3 }).default("0"),
  receivingDay04: decimal("receiving_day_04", { precision: 12, scale: 3 }).default("0"),
  receivingDay05: decimal("receiving_day_05", { precision: 12, scale: 3 }).default("0"),
  receivingDay06: decimal("receiving_day_06", { precision: 12, scale: 3 }).default("0"),
  receivingDay07: decimal("receiving_day_07", { precision: 12, scale: 3 }).default("0"),
  receivingDay08: decimal("receiving_day_08", { precision: 12, scale: 3 }).default("0"),
  receivingDay09: decimal("receiving_day_09", { precision: 12, scale: 3 }).default("0"),
  receivingDay10: decimal("receiving_day_10", { precision: 12, scale: 3 }).default("0"),
  receivingDay11: decimal("receiving_day_11", { precision: 12, scale: 3 }).default("0"),
  receivingDay12: decimal("receiving_day_12", { precision: 12, scale: 3 }).default("0"),
  receivingDay13: decimal("receiving_day_13", { precision: 12, scale: 3 }).default("0"),
  receivingDay14: decimal("receiving_day_14", { precision: 12, scale: 3 }).default("0"),
  receivingDay15: decimal("receiving_day_15", { precision: 12, scale: 3 }).default("0"),
  receivingDay16: decimal("receiving_day_16", { precision: 12, scale: 3 }).default("0"),
  receivingDay17: decimal("receiving_day_17", { precision: 12, scale: 3 }).default("0"),
  receivingDay18: decimal("receiving_day_18", { precision: 12, scale: 3 }).default("0"),
  receivingDay19: decimal("receiving_day_19", { precision: 12, scale: 3 }).default("0"),
  receivingDay20: decimal("receiving_day_20", { precision: 12, scale: 3 }).default("0"),
  receivingDay21: decimal("receiving_day_21", { precision: 12, scale: 3 }).default("0"),
  receivingDay22: decimal("receiving_day_22", { precision: 12, scale: 3 }).default("0"),
  receivingDay23: decimal("receiving_day_23", { precision: 12, scale: 3 }).default("0"),
  receivingDay24: decimal("receiving_day_24", { precision: 12, scale: 3 }).default("0"),
  receivingDay25: decimal("receiving_day_25", { precision: 12, scale: 3 }).default("0"),
  receivingDay26: decimal("receiving_day_26", { precision: 12, scale: 3 }).default("0"),
  receivingDay27: decimal("receiving_day_27", { precision: 12, scale: 3 }).default("0"),
  receivingDay28: decimal("receiving_day_28", { precision: 12, scale: 3 }).default("0"),
  receivingDay29: decimal("receiving_day_29", { precision: 12, scale: 3 }).default("0"),
  receivingDay30: decimal("receiving_day_30", { precision: 12, scale: 3 }).default("0"),
  receivingDay31: decimal("receiving_day_31", { precision: 12, scale: 3 }).default("0"),
  usageTotal: decimal("usage_total", { precision: 12, scale: 3 }).default("0"),
  usageDay01: decimal("usage_day_01", { precision: 12, scale: 3 }).default("0"),
  usageDay02: decimal("usage_day_02", { precision: 12, scale: 3 }).default("0"),
  usageDay03: decimal("usage_day_03", { precision: 12, scale: 3 }).default("0"),
  usageDay04: decimal("usage_day_04", { precision: 12, scale: 3 }).default("0"),
  usageDay05: decimal("usage_day_05", { precision: 12, scale: 3 }).default("0"),
  usageDay06: decimal("usage_day_06", { precision: 12, scale: 3 }).default("0"),
  usageDay07: decimal("usage_day_07", { precision: 12, scale: 3 }).default("0"),
  usageDay08: decimal("usage_day_08", { precision: 12, scale: 3 }).default("0"),
  usageDay09: decimal("usage_day_09", { precision: 12, scale: 3 }).default("0"),
  usageDay10: decimal("usage_day_10", { precision: 12, scale: 3 }).default("0"),
  usageDay11: decimal("usage_day_11", { precision: 12, scale: 3 }).default("0"),
  usageDay12: decimal("usage_day_12", { precision: 12, scale: 3 }).default("0"),
  usageDay13: decimal("usage_day_13", { precision: 12, scale: 3 }).default("0"),
  usageDay14: decimal("usage_day_14", { precision: 12, scale: 3 }).default("0"),
  usageDay15: decimal("usage_day_15", { precision: 12, scale: 3 }).default("0"),
  usageDay16: decimal("usage_day_16", { precision: 12, scale: 3 }).default("0"),
  usageDay17: decimal("usage_day_17", { precision: 12, scale: 3 }).default("0"),
  usageDay18: decimal("usage_day_18", { precision: 12, scale: 3 }).default("0"),
  usageDay19: decimal("usage_day_19", { precision: 12, scale: 3 }).default("0"),
  usageDay20: decimal("usage_day_20", { precision: 12, scale: 3 }).default("0"),
  usageDay21: decimal("usage_day_21", { precision: 12, scale: 3 }).default("0"),
  usageDay22: decimal("usage_day_22", { precision: 12, scale: 3 }).default("0"),
  usageDay23: decimal("usage_day_23", { precision: 12, scale: 3 }).default("0"),
  usageDay24: decimal("usage_day_24", { precision: 12, scale: 3 }).default("0"),
  usageDay25: decimal("usage_day_25", { precision: 12, scale: 3 }).default("0"),
  usageDay26: decimal("usage_day_26", { precision: 12, scale: 3 }).default("0"),
  usageDay27: decimal("usage_day_27", { precision: 12, scale: 3 }).default("0"),
  usageDay28: decimal("usage_day_28", { precision: 12, scale: 3 }).default("0"),
  usageDay29: decimal("usage_day_29", { precision: 12, scale: 3 }).default("0"),
  usageDay30: decimal("usage_day_30", { precision: 12, scale: 3 }).default("0"),
  usageDay31: decimal("usage_day_31", { precision: 12, scale: 3 }).default("0"),
  endStock: decimal("end_stock", { precision: 12, scale: 3 }).default("0"),
  unitPrice: decimal("unit_price", { precision: 12, scale: 2 }).default("0"),
  receivingAmount: decimal("receiving_amount", { precision: 15, scale: 2 }).default("0"),
  usageAmount: decimal("usage_amount", { precision: 15, scale: 2 }).default("0"),
  status: varchar("status", { length: 20 }).default("draft"),
  createdAt: timestamp("created_at").defaultNow(),
  updatedAt: timestamp("updated_at").defaultNow().onUpdateNow(),
}, (table) => ({
  // ★ 2026-05-09 (PR #273): ON DUPLICATE KEY UPDATE 동작을 위한 UNIQUE 제약
  // 누락 시 cron 매일 INSERT 만 누적 (2026-04 21배 중복 사고 발생)
  uqTenantMaterialYearMonth: uniqueIndex("uq_mlm_tenant_material_year_month").on(table.tenantId, table.materialId, table.yearMonth),
  tenantMonthIdx: index("idx_tenant_month").on(table.tenantId, table.yearMonth),
  materialIdx: index("idx_material").on(table.materialId),
}));

// 월마감 승인
export const materialLedgerApproval = mysqlTable("material_ledger_approval", {
  id: bigint("id", { mode: "number" }).primaryKey().autoincrement(),
  tenantId: int("tenant_id").notNull().default(2),
  yearMonth: varchar("year_month", { length: 7 }).notNull(),
  status: varchar("status", { length: 20 }).default("pending"),
  submittedBy: bigint("submitted_by", { mode: "number" }),
  submittedAt: timestamp("submitted_at"),
  approvedBy: bigint("approved_by", { mode: "number" }),
  approvedAt: timestamp("approved_at"),
  rejectedReason: text("rejected_reason"),
  notes: text("notes"),
  createdAt: timestamp("created_at").defaultNow(),
  updatedAt: timestamp("updated_at").defaultNow().onUpdateNow(),
});
