/**
 * schema_main 분할: CCP 모니터링
 */
import {
  bigint, boolean, date, decimal, int, json,
  mysqlEnum, mysqlTable, text, timestamp, tinyint, varchar
} from "drizzle-orm/mysql-core";
import { tenants } from "./schema_main_core";

export const hCcpInstances = mysqlTable("h_ccp_instances", {
  id: bigint("id", { mode: "number" }).autoincrement().primaryKey(),
  tenantId: int('tenant_id').notNull().default(1).references(() => tenants.id),
  siteId: bigint("site_id", { mode: "number" }).notNull(),
  workDate: date("work_date").notNull(),
  ccpType: varchar("ccp_type", { length: 50 }).notNull(),
  processGroupId: int("process_group_id"),
  productName: varchar("product_name", { length: 100 }),
  productId: bigint("product_id", { mode: "number" }),
  batchId: bigint("batch_id", { mode: "number" }),
  status: mysqlEnum("status", ["draft", "submitted", "approved", "rejected"]).default("draft").notNull(),
  submittedAt: timestamp("submitted_at"),
  submittedBy: bigint("submitted_by", { mode: "number" }),
  approvedAt: timestamp("approved_at"),
  approvedBy: bigint("approved_by", { mode: "number" }),
  createdBy: bigint("created_by", { mode: "number" }),
  createdAt: timestamp("created_at").defaultNow().notNull(),
  updatedAt: timestamp("updated_at").defaultNow().onUpdateNow().notNull(),
});

export const hCcpRows = mysqlTable("h_ccp_rows", {
  id: bigint("id", { mode: "number" }).autoincrement().primaryKey(),
  tenantId: int('tenant_id').notNull().default(1).references(() => tenants.id),
  instanceId: bigint("instance_id", { mode: "number" }).notNull(),
  sortOrder: int("sort_order"),
  rowType: mysqlEnum("row_type", ["measurement", "corrective_action", "verification"]).default("measurement").notNull(),
  measuredAt: timestamp("measured_at"),
  tempC: decimal("temp_c", { precision: 5, scale: 1 }),
  durationMin: int("duration_min"),
  pressureBar: decimal("pressure_bar", { precision: 5, scale: 2 }),
  result: mysqlEnum("result", ["PASS", "FAIL", "N/A"]),
  note: text("note"),
  equipmentId: int("equipment_id"),
  equipmentName: varchar("equipment_name", { length: 100 }),
  batchNo: int("batch_no"),
  autoGenerated: tinyint("auto_generated").default(0),
  heatingMin: int("heating_min"),
  cycleTotalMin: int("cycle_total_min"),
  createdAt: timestamp("created_at").defaultNow().notNull(),
  updatedAt: timestamp("updated_at").defaultNow().onUpdateNow().notNull(),
});

export const hCcpTemplates = mysqlTable("h_ccp_templates", {
  id: bigint("id", { mode: "number" }).autoincrement().primaryKey(),
  tenantId: int('tenant_id').notNull().default(1).references(() => tenants.id),
  ccpType: varchar("ccp_type", { length: 50 }).notNull(),
  processGroupId: int("process_group_id"),
  templateName: varchar("template_name", { length: 100 }).notNull(),
  productNamePattern: varchar("product_name_pattern", { length: 255 }),
  priority: int("priority").default(0).notNull(),
  isActive: tinyint("is_active").default(1).notNull(),
  description: text("description"),
  criticalLimit: text("critical_limit"), // 한계기준 요약 (예: "75°C 이상", "2시간 이내")
  createdAt: timestamp("created_at").defaultNow().notNull(),
  updatedAt: timestamp("updated_at").defaultNow().onUpdateNow().notNull(),
});

export const hCcpTemplateRows = mysqlTable("h_ccp_template_rows", {
  id: bigint("id", { mode: "number" }).autoincrement().primaryKey(),
  tenantId: int('tenant_id').notNull().default(1).references(() => tenants.id),
  templateId: bigint("template_id", { mode: "number" }).notNull(),
  sortOrder: int("sort_order"),
  rowType: mysqlEnum("row_type", ["measurement", "corrective_action", "verification"]).default("measurement").notNull(),
  criticalLimitMin: decimal("critical_limit_min", { precision: 10, scale: 3 }),
  criticalLimitMax: decimal("critical_limit_max", { precision: 10, scale: 3 }),
  unit: varchar("unit", { length: 20 }),
  note: text("note"),
  createdAt: timestamp("created_at").defaultNow().notNull(),
});

export const hCcpTemplatesV2 = mysqlTable("h_ccp_templates_v2", {
  id: bigint("id", { mode: "number" }).autoincrement().primaryKey(),
  tenantId: int('tenant_id').notNull().default(1).references(() => tenants.id),
  ccpType: varchar("ccp_type", { length: 50 }).notNull(),
  processGroupId: int("process_group_id"),
  templateName: varchar("template_name", { length: 100 }).notNull(),
  version: int("version").default(1).notNull(),
  description: text("description"),
  createdAt: timestamp("created_at").defaultNow().notNull(),
});

export const hCcpTemplateRowsV2 = mysqlTable("h_ccp_template_rows_v2", {
  id: bigint("id", { mode: "number" }).autoincrement().primaryKey(),
  tenantId: int('tenant_id').notNull().default(1).references(() => tenants.id),
  templateId: bigint("template_id", { mode: "number" }).notNull(),
  sortOrder: int("sort_order"),
  rowType: mysqlEnum("row_type", ["measurement", "corrective_action", "verification"]).default("measurement").notNull(),
  criticalLimitMin: decimal("critical_limit_min", { precision: 10, scale: 3 }),
  criticalLimitMax: decimal("critical_limit_max", { precision: 10, scale: 3 }),
  unit: varchar("unit", { length: 20 }),
  note: text("note"),
  createdAt: timestamp("created_at").defaultNow().notNull(),
});

export const hCcpManualMapping = mysqlTable("h_ccp_manual_mapping", {
  id: bigint("id", { mode: "number" }).autoincrement().primaryKey(),
  tenantId: int('tenant_id').notNull().default(1).references(() => tenants.id),
  productId: bigint("product_id", { mode: "number" }).notNull(),
  ccpType: varchar("ccp_type", { length: 50 }).notNull(),
  processGroupId: int("process_group_id"),
  templateId: bigint("template_id", { mode: "number" }),
  createdAt: timestamp("created_at").defaultNow().notNull(),
});

export const hCcpSchedules = mysqlTable("h_ccp_schedules", {
  id: bigint("id", { mode: "number" }).autoincrement().primaryKey(),
  tenantId: int('tenant_id').notNull().default(1).references(() => tenants.id),
  ccpInstanceId: bigint("ccp_instance_id", { mode: "number" }).notNull(),
  scheduledDate: date("scheduled_date").notNull(),
  frequency: mysqlEnum("frequency", ["daily", "weekly", "monthly"]).notNull(),
  status: mysqlEnum("status", ["pending", "completed", "skipped"]).default("pending").notNull(),
  completedAt: timestamp("completed_at"),
  completedBy: bigint("completed_by", { mode: "number" }),
  note: text("note"),
  createdAt: timestamp("created_at").defaultNow().notNull(),
  updatedAt: timestamp("updated_at").defaultNow().onUpdateNow().notNull(),
});

// ============================================================================
// 배치-LOT 연결 테이블 (2개)
// ============================================================================

/**
 * 배치에서 사용된 원재료 LOT 정보
 */

export const hCcpFormRecords = mysqlTable("h_ccp_form_records", {
  id: bigint("id", { mode: "number" }).autoincrement().primaryKey(),
  tenantId: int("tenant_id").notNull().default(1),
  siteId: bigint("site_id", { mode: "number" }).notNull(),
  batchId: bigint("batch_id", { mode: "number" }).notNull(),
  ccpType: varchar("ccp_type", { length: 20 }).notNull(),       // 'CCP-1B','CCP-2B','CCP-4P'
  workDate: date("work_date").notNull(),
  productId: bigint("product_id", { mode: "number" }),
  productName: varchar("product_name", { length: 200 }),
  processGroupId: int("process_group_id"),
  processGroupName: varchar("process_group_name", { length: 100 }),

  // 배치 계산 정보
  bomBatchKg: decimal("bom_batch_kg", { precision: 10, scale: 2 }),
  plannedQtyKg: decimal("planned_qty_kg", { precision: 10, scale: 2 }),
  batchCount: int("batch_count").notNull().default(1),

  // 설비 그룹 설정
  equipGroupMode: mysqlEnum("equip_group_mode", ["concurrent", "sequential", "grouped"]).notNull().default("sequential"),
  equipIntervalMin: int("equip_interval_min").default(10),

  // CL 한계기준 - CCP-2B (굽기)
  clHeatTimeMinLo: int("cl_heat_time_min_lo"),
  clHeatTimeMinHi: int("cl_heat_time_min_hi"),
  clHeatTempLo: decimal("cl_heat_temp_lo", { precision: 5, scale: 1 }),
  // CL 한계기준 - CCP-1B (증숙)
  clPressureMpaLo: decimal("cl_pressure_mpa_lo", { precision: 5, scale: 3 }),
  clProductTempLo: decimal("cl_product_temp_lo", { precision: 5, scale: 1 }),
  // CL 한계기준 - CCP-4P (금속검출)
  clMetalSensitivity: int("cl_metal_sensitivity").default(130),
  clFeMm: decimal("cl_fe_mm", { precision: 4, scale: 1 }).default("2.0"),
  clSusMm: decimal("cl_sus_mm", { precision: 4, scale: 1 }).default("3.0"),

  // 승인 정보
  writerId: bigint("writer_id", { mode: "number" }),
  approverId: bigint("approver_id", { mode: "number" }),
  status: mysqlEnum("status", ["draft", "submitted", "approved", "rejected"]).notNull().default("draft"),
  approvalRequestId: bigint("approval_request_id", { mode: "number" }),
  submittedAt: timestamp("submitted_at"),
  approvedAt: timestamp("approved_at"),
  rejectedReason: text("rejected_reason"),

  createdAt: timestamp("created_at").defaultNow().notNull(),
  updatedAt: timestamp("updated_at").defaultNow().notNull(),
});

export type CcpFormRecord = typeof hCcpFormRecords.$inferSelect;
export type InsertCcpFormRecord = typeof hCcpFormRecords.$inferInsert;

export const hCcpFormRows = mysqlTable("h_ccp_form_rows", {
  id: bigint("id", { mode: "number" }).autoincrement().primaryKey(),
  tenantId: int("tenant_id").notNull().default(1),
  formRecordId: bigint("form_record_id", { mode: "number" }).notNull(),
  batchSeq: int("batch_seq").notNull().default(1),
  equipmentId: int("equipment_id"),
  equipmentName: varchar("equipment_name", { length: 100 }),
  equipmentType: varchar("equipment_type", { length: 50 }),

  // 공통 필드
  productName: varchar("product_name", { length: 200 }),
  measurementTime: varchar("measurement_time", { length: 10 }),  // TIME stored as string
  inputQtyKg: decimal("input_qty_kg", { precision: 10, scale: 2 }),
  result: mysqlEnum("result", ["적합", "부적합"]),

  // CCP-2B (가열굽기)
  heatTimeMin: int("heat_time_min"),
  heatTempC: decimal("heat_temp_c", { precision: 5, scale: 1 }),

  // CCP-1B (가열증숙)
  siruName: varchar("siru_name", { length: 50 }),
  pressureMpa: decimal("pressure_mpa", { precision: 5, scale: 3 }),
  tempEdgeC: decimal("temp_edge_c", { precision: 5, scale: 1 }),
  tempCenterC: decimal("temp_center_c", { precision: 5, scale: 1 }),

  // CCP-4P (금속검출) - 감도 모니터링
  metalPassTime: varchar("metal_pass_time", { length: 10 }),
  metalFeMid: varchar("metal_fe_mid", { length: 10 }),
  metalSusMid: varchar("metal_sus_mid", { length: 10 }),
  metalProductOnly: varchar("metal_product_only", { length: 10 }),
  metalFeProduct: varchar("metal_fe_product", { length: 10 }),
  metalSusProduct: varchar("metal_sus_product", { length: 10 }),

  // CCP-4P 통과량
  passTimeStart: varchar("pass_time_start", { length: 10 }),
  passTimeEnd: varchar("pass_time_end", { length: 10 }),
  passQty: int("pass_qty"),
  detectedQty: int("detected_qty"),
  specialNote: text("special_note"),

  // 이탈/개선조치
  isDeviation: tinyint("is_deviation").notNull().default(0),
  deviationNote: text("deviation_note"),
  correctiveAction: text("corrective_action"),
  actionBy: varchar("action_by", { length: 100 }),
  confirmedBy: varchar("confirmed_by", { length: 100 }),

  note: text("note"),
  createdAt: timestamp("created_at").defaultNow().notNull(),
  updatedAt: timestamp("updated_at").defaultNow().notNull(),
});

export type CcpFormRow = typeof hCcpFormRows.$inferSelect;
export type InsertCcpFormRow = typeof hCcpFormRows.$inferInsert;

export const hCcpEquipBatchSettings = mysqlTable("h_ccp_equip_batch_settings", {
  id: int("id").autoincrement().primaryKey(),
  tenantId: int("tenant_id").notNull().default(1),
  processGroupId: int("process_group_id").notNull(),
  groupMode: mysqlEnum("group_mode", ["concurrent", "sequential", "grouped"]).notNull().default("sequential"),
  intervalBetweenMin: int("interval_between_min").default(10),
  maxConcurrent: int("max_concurrent").default(1),
  notes: text("notes"),
  createdAt: timestamp("created_at").defaultNow().notNull(),
  updatedAt: timestamp("updated_at").defaultNow().notNull(),
});

export type CcpEquipBatchSetting = typeof hCcpEquipBatchSettings.$inferSelect;
export type InsertCcpEquipBatchSetting = typeof hCcpEquipBatchSettings.$inferInsert;

// ─────────────────────────────────────────────────────────
// Metal Detection Record Frame Tables
// ─────────────────────────────────────────────────────────

/**
 * BatchProcessRun: 배치별 금속검출 공정 실행 기록
 * Batch → Equipment → Time allocation with random offset
 */

export const hCcpBatchProcessRuns = mysqlTable("h_ccp_batch_process_runs", {
  id: bigint("id", { mode: "number" }).autoincrement().primaryKey(),
  tenantId: int("tenant_id").notNull().default(1),
  siteId: bigint("site_id", { mode: "number" }),
  batchId: bigint("batch_id", { mode: "number" }).notNull(),
  processGroupId: int("process_group_id"),
  processCode: varchar("process_code", { length: 30 }).notNull().default("METAL_DETECT"),
  equipmentId: int("equipment_id"),
  mode: mysqlEnum("mode", ["PARALLEL", "SEQUENTIAL"]).notNull().default("SEQUENTIAL"),
  channels: int("channels").notNull().default(1),

  // quantity
  plannedTotalQty: decimal("planned_total_qty", { precision: 12, scale: 3 }),
  actualTotalQty: decimal("actual_total_qty", { precision: 12, scale: 3 }),

  // time
  workDate: date("work_date").notNull(),
  workStartTime: varchar("work_start_time", { length: 10 }).default("09:00"),
  workEndTime: varchar("work_end_time", { length: 10 }).default("16:30"),
  lunchStartTime: varchar("lunch_start_time", { length: 10 }).default("12:00"),
  lunchEndTime: varchar("lunch_end_time", { length: 10 }).default("13:00"),
  randomOffsetMin: int("random_offset_min").notNull().default(0),
  randomSeed: varchar("random_seed", { length: 100 }),

  plannedStartAt: timestamp("planned_start_at"),
  plannedEndAt: timestamp("planned_end_at"),
  actualStartAt: timestamp("actual_start_at"),
  actualEndAt: timestamp("actual_end_at"),

  // status
  status: mysqlEnum("status", ["PLANNED", "RUNNING", "DONE", "HOLD", "FAIL"]).notNull().default("PLANNED"),

  createdAt: timestamp("created_at").defaultNow().notNull(),
  updatedAt: timestamp("updated_at").defaultNow().notNull(),
});

export type CcpBatchProcessRun = typeof hCcpBatchProcessRuns.$inferSelect;
export type InsertCcpBatchProcessRun = typeof hCcpBatchProcessRuns.$inferInsert;

/**
 * MetalDetectSkuSlot: SKU별 시간/수량 배분 슬롯
 * Each SKU gets proportional time/quantity allocation within a batch process run
 */

export const hCcpMetalSkuSlots = mysqlTable("h_ccp_metal_sku_slots", {
  id: bigint("id", { mode: "number" }).autoincrement().primaryKey(),
  tenantId: int("tenant_id").notNull().default(1),
  batchProcessRunId: bigint("batch_process_run_id", { mode: "number" }).notNull(),
  skuId: bigint("sku_id", { mode: "number" }),
  productId: bigint("product_id", { mode: "number" }),
  productName: varchar("product_name", { length: 200 }),
  skuName: varchar("sku_name", { length: 200 }),
  channelNo: int("channel_no").notNull().default(1),
  sequenceNo: int("sequence_no").notNull().default(1),

  // planned
  plannedQty: decimal("planned_qty", { precision: 12, scale: 3 }),
  plannedPassQty: int("planned_pass_qty"),
  allocatedDurationMin: decimal("allocated_duration_min", { precision: 8, scale: 2 }),
  plannedStartAt: timestamp("planned_start_at"),
  plannedEndAt: timestamp("planned_end_at"),

  // actual
  actualFirstPassAt: timestamp("actual_first_pass_at"),
  actualLastPassAt: timestamp("actual_last_pass_at"),
  actualPassQty: int("actual_pass_qty"),
  detectQty: int("detect_qty").notNull().default(0),

  note: text("note"),
  status: mysqlEnum("status", ["PLANNED", "RUNNING", "DONE", "FAIL"]).notNull().default("PLANNED"),

  createdAt: timestamp("created_at").defaultNow().notNull(),
  updatedAt: timestamp("updated_at").defaultNow().notNull(),
});

export type CcpMetalSkuSlot = typeof hCcpMetalSkuSlots.$inferSelect;
export type InsertCcpMetalSkuSlot = typeof hCcpMetalSkuSlots.$inferInsert;

/**
 * MetalDetectSensitivityCheck: 감도 모니터링 기록
 * START check, PERIODIC (every 2h), END check
 */

export const hCcpMetalSensitivityChecks = mysqlTable("h_ccp_metal_sensitivity_checks", {
  id: bigint("id", { mode: "number" }).autoincrement().primaryKey(),
  tenantId: int("tenant_id").notNull().default(1),
  batchProcessRunId: bigint("batch_process_run_id", { mode: "number" }).notNull(),
  skuSlotId: bigint("sku_slot_id", { mode: "number" }),
  equipmentId: int("equipment_id"),

  checkType: mysqlEnum("check_type", ["START", "PERIODIC", "END"]).notNull(),
  checkSeq: int("check_seq").notNull().default(1),
  scheduledAt: timestamp("scheduled_at"),
  checkedAt: timestamp("checked_at"),

  feResult: varchar("fe_result", { length: 10 }),
  susResult: varchar("sus_result", { length: 10 }),
  productOnlyResult: varchar("product_only_result", { length: 10 }),
  feProductResult: varchar("fe_product_result", { length: 10 }),
  susProductResult: varchar("sus_product_result", { length: 10 }),

  feThresholdMm: decimal("fe_threshold_mm", { precision: 4, scale: 1 }).default("2.0"),
  susThresholdMm: decimal("sus_threshold_mm", { precision: 4, scale: 1 }).default("3.0"),

  result: mysqlEnum("result", ["PASS", "FAIL", "PENDING"]).notNull().default("PENDING"),
  note: text("note"),
  checkedBy: bigint("checked_by", { mode: "number" }),

  createdAt: timestamp("created_at").defaultNow().notNull(),
  updatedAt: timestamp("updated_at").defaultNow().notNull(),
});

export type CcpMetalSensitivityCheck = typeof hCcpMetalSensitivityChecks.$inferSelect;
export type InsertCcpMetalSensitivityCheck = typeof hCcpMetalSensitivityChecks.$inferInsert;

/**
 * CCPDeviationAction: CCP 이탈 발생 시 조치 기록
 * On FAIL → HOLD run → create deviation → require approver signature to release
 */

export const hCcpDeviationActions = mysqlTable("h_ccp_deviation_actions", {
  id: bigint("id", { mode: "number" }).autoincrement().primaryKey(),
  tenantId: int("tenant_id").notNull().default(1),
  deviationId: bigint("deviation_id", { mode: "number" }),
  batchProcessRunId: bigint("batch_process_run_id", { mode: "number" }),
  skuSlotId: bigint("sku_slot_id", { mode: "number" }),
  sensitivityCheckId: bigint("sensitivity_check_id", { mode: "number" }),

  deviationType: varchar("deviation_type", { length: 50 }).default("METAL_DETECT"),
  deviationDescription: text("deviation_description"),

  actionTaken: text("action_taken"),
  disposedQty: int("disposed_qty").default(0),
  recheckResult: mysqlEnum("recheck_result", ["PASS", "FAIL", "PENDING"]),
  holdStartAt: timestamp("hold_start_at"),
  holdEndAt: timestamp("hold_end_at"),

  approverId: bigint("approver_id", { mode: "number" }),
  approvedAt: timestamp("approved_at"),
  approverSignature: text("approver_signature"),

  status: mysqlEnum("status", ["OPEN", "IN_PROGRESS", "RESOLVED", "CLOSED"]).notNull().default("OPEN"),
  resolutionNote: text("resolution_note"),

  createdAt: timestamp("created_at").defaultNow().notNull(),
  updatedAt: timestamp("updated_at").defaultNow().notNull(),
  createdBy: bigint("created_by", { mode: "number" }),
});

export type CcpDeviationAction = typeof hCcpDeviationActions.$inferSelect;
export type InsertCcpDeviationAction = typeof hCcpDeviationActions.$inferInsert;

// Type exports
export type CcpInstance = typeof hCcpInstances.$inferSelect;
export type InsertCcpInstance = typeof hCcpInstances.$inferInsert;

/**
 * CCP 점검 기록 (원본 schema_main에서 복원)
 */
export const hCcpRecords = mysqlTable("h_ccp_records", {
  id: bigint("id", { mode: "number" }).primaryKey().autoincrement(),
  tenantId: int('tenant_id').notNull().references(() => tenants.id),
  instanceId: bigint("instance_id", { mode: "number" }).notNull(),
  recordData: text("record_data"),
  createdAt: timestamp("created_at").defaultNow().notNull(),
});
