import { getDb } from "../db";
import { and, gte, lte, eq, desc } from "drizzle-orm";
import puppeteer from "puppeteer";
import { mkdirSync, writeFileSync } from "fs";
import { join } from "path";

/**
 * CCP 점검 리포트 데이터 조회
 */
export async function getCcpReportData(params: {
  startDate: Date;
  endDate: Date;
  ccpType?: string;
}) {
  const db = await getDb();
  if (!db) throw new Error("Database not initialized");
  
  const { hCcpInstances, hCcpRows, hBatches, hProductsV2 } = await import("../../drizzle/schema_main");
  
  // CCP 인스턴스 및 행 조회
  const ccpRecords = await db
    .select({
      instanceId: hCcpInstances.id,
      ccpType: hCcpInstances.ccpType,
      batchCode: hBatches.batchCode,
      productName: hProductsV2.productName,
      rowId: hCcpRows.id,
      measuredAt: hCcpRows.measuredAt,
      tempC: hCcpRows.tempC,
      pressureBar: hCcpRows.pressureBar,
      durationMin: hCcpRows.durationMin,
      result: hCcpRows.result,
      note: hCcpRows.note,
      autoGenerated: hCcpRows.autoGenerated,
    })
    .from(hCcpInstances)
    .innerJoin(hBatches, eq(hCcpInstances.batchId, hBatches.id))
    .innerJoin(hProductsV2, eq(hBatches.productId, hProductsV2.id))
    .leftJoin(hCcpRows, eq(hCcpRows.instanceId, hCcpInstances.id))
    .where(
      and(
        hCcpRows.measuredAt ? gte(hCcpRows.measuredAt, params.startDate) : undefined,
        hCcpRows.measuredAt ? lte(hCcpRows.measuredAt, params.endDate) : undefined,
        params.ccpType ? eq(hCcpInstances.ccpType, params.ccpType) : undefined
      )
    )
    .orderBy(hCcpRows.measuredAt ? desc(hCcpRows.measuredAt) : desc(hCcpInstances.id));

  // 통계 계산
  const totalRecords = ccpRecords.length;
  const deviationRecords = ccpRecords.filter((r: any) => r.result === 'FAIL').length;
  const deviationRate = totalRecords > 0 ? (deviationRecords / totalRecords) * 100 : 0;

  // CCP 타입별 집계
  const ccpTypeStats = ccpRecords.reduce((acc: any, record: any) => {
    if (!record.ccpType) return acc;
    if (!acc[record.ccpType]) {
      acc[record.ccpType] = { total: 0, deviations: 0 };
    }
    acc[record.ccpType].total++;
    if (record.result === 'FAIL') {
      acc[record.ccpType].deviations++;
    }
    return acc;
  }, {} as Record<string, { total: number; deviations: number }>);

  return {
    records: ccpRecords,
    summary: {
      totalRecords,
      deviationRecords,
      deviationRate: deviationRate.toFixed(2),
      ccpTypeStats,
    },
  };
}

/**
 * HTML 보고서 생성
 */
export function generateReportHtml(params: {
  title: string;
  period: string;
  data: Awaited<ReturnType<typeof getCcpReportData>>;
}) {
  const { title, period, data } = params;
  
  const html = `
<!DOCTYPE html>
<html lang="ko">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>${title}</title>
  <style>
    body {
      font-family: 'Malgun Gothic', sans-serif;
      margin: 40px;
      color: #333;
    }
    h1 {
      text-align: center;
      color: #2563eb;
      margin-bottom: 10px;
    }
    .period {
      text-align: center;
      color: #666;
      margin-bottom: 30px;
    }
    .summary {
      background: #f3f4f6;
      padding: 20px;
      border-radius: 8px;
      margin-bottom: 30px;
    }
    .summary-grid {
      display: grid;
      grid-template-columns: repeat(3, 1fr);
      gap: 20px;
    }
    .summary-item {
      text-align: center;
    }
    .summary-item .label {
      font-size: 14px;
      color: #666;
      margin-bottom: 5px;
    }
    .summary-item .value {
      font-size: 28px;
      font-weight: bold;
      color: #2563eb;
    }
    .summary-item.deviation .value {
      color: #dc2626;
    }
    table {
      width: 100%;
      border-collapse: collapse;
      margin-bottom: 30px;
    }
    th, td {
      border: 1px solid #ddd;
      padding: 12px;
      text-align: left;
    }
    th {
      background-color: #2563eb;
      color: white;
      font-weight: bold;
    }
    tr:nth-child(even) {
      background-color: #f9fafb;
    }
    .deviation-row {
      background-color: #fee2e2 !important;
    }
    .footer {
      text-align: center;
      color: #999;
      font-size: 12px;
      margin-top: 40px;
    }
  </style>
</head>
<body>
  <h1>${title}</h1>
  <div class="period">${period}</div>
  
  <div class="summary">
    <h2>요약</h2>
    <div class="summary-grid">
      <div class="summary-item">
        <div class="label">총 점검 건수</div>
        <div class="value">${data.summary.totalRecords}</div>
      </div>
      <div class="summary-item deviation">
        <div class="label">이탈 건수</div>
        <div class="value">${data.summary.deviationRecords}</div>
      </div>
      <div class="summary-item">
        <div class="label">이탈률</div>
        <div class="value">${data.summary.deviationRate}%</div>
      </div>
    </div>
  </div>

  <h2>CCP 타입별 통계</h2>
  <table>
    <thead>
      <tr>
        <th>CCP 타입</th>
        <th>총 점검 건수</th>
        <th>이탈 건수</th>
        <th>이탈률</th>
      </tr>
    </thead>
    <tbody>
      ${Object.entries(data.summary.ccpTypeStats).map(([ccpType, stats]: [string, any]) => `
        <tr>
          <td>${ccpType}</td>
          <td>${stats.total}</td>
          <td>${stats.deviations}</td>
          <td>${stats.total > 0 ? ((stats.deviations / stats.total) * 100).toFixed(2) : 0}%</td>
        </tr>
      `).join('')}
    </tbody>
  </table>

  <h2>상세 점검 기록</h2>
  <table>
    <thead>
      <tr>
        <th>점검 시간</th>
        <th>배치 코드</th>
        <th>제품명</th>
        <th>CCP 타입</th>
        <th>온도(°C)</th>
        <th>압력(bar)</th>
        <th>시간(분)</th>
        <th>이탈 여부</th>
        <th>점검자</th>
      </tr>
    </thead>
    <tbody>
      ${data.records.map((record: any) => `
        <tr class="${record.result === 'FAIL' ? 'deviation-row' : ''}">
          <td>${record.measuredAt ? new Date(record.measuredAt).toLocaleString('ko-KR') : '-'}</td>
          <td>${record.batchCode || '-'}</td>
          <td>${record.productName || '-'}</td>
          <td>${record.ccpType || '-'}</td>
          <td>${record.tempC || '-'}</td>
          <td>${record.pressureBar || '-'}</td>
          <td>${record.durationMin || '-'}</td>
          <td>${record.result === 'FAIL' ? '<strong>이탈</strong>' : (record.result === 'PASS' ? '정상' : 'N/A')}</td>
          <td>${record.autoGenerated ? '자동생성' : '수동입력'}</td>
        </tr>
      `).join('')}
    </tbody>
  </table>

  <div class="footer">
    <p>HACCP 식품 안전 관리 시스템</p>
    <p>생성 일시: ${new Date().toLocaleString('ko-KR')}</p>
  </div>
</body>
</html>
  `;
  
  return html;
}

/**
 * PDF 보고서 생성
 */
export async function generatePdfReport(params: {
  title: string;
  period: string;
  startDate: Date;
  endDate: Date;
  ccpType?: string;
}) {
  // 데이터 조회
  const data = await getCcpReportData({
    startDate: params.startDate,
    endDate: params.endDate,
    ccpType: params.ccpType,
  });

  // HTML 생성
  const html = generateReportHtml({
    title: params.title,
    period: params.period,
    data,
  });

  // PDF 변환
  const browser = await puppeteer.launch({
    headless: true,
    args: ['--no-sandbox', '--disable-setuid-sandbox'],
  });
  
  try {
    const page = await browser.newPage();
    await page.setContent(html, { waitUntil: 'networkidle0' });
    
    // PDF 생성
    const pdfBuffer = await page.pdf({
      format: 'A4',
      printBackground: true,
      margin: {
        top: '20mm',
        right: '15mm',
        bottom: '20mm',
        left: '15mm',
      },
    });
    
    return pdfBuffer;
  } finally {
    await browser.close();
  }
}
