/**
 * 배치 생성 시 CCP 자동 생성 서비스
 * 
 * 백업 소스(haccp_system)의 CCP 자동 생성 로직 통합
 * - 제품명 기반 CCP 타입 자동 추론
 * - CCP 인스턴스 및 기본 행 자동 생성
 * - 현장 운영 중단 방지 (에러 처리 개선)
 */

import * as db from "../db";

export type CcpType = "CCP_1B" | "CCP_2B" | "CCP_4P";

/**
 * 제품명 기반 CCP 타입 추론
 * - 설기/송편/약식 등 전통 떡류 → CCP-1B (증숙)
 * - 인절미/찰떡/가래떡 등 → CCP-2B (교반)
 * - 모든 제품 → CCP-4P (금속검출)
 */
function inferCcpTypesByProductName(productName: string): CcpType[] {
  const n = (productName || "").replace(/\s+/g, "");

  // 기본: 전 제품 금속검출
  const types: CcpType[] = ["CCP_4P"];

  // 설기/송편/약식/절편 등 전통 떡류 → 증숙(CCP-1B)
  if (
    /설기|송편|약식|절편|시루|버무리|개떡|백설기|쑥절편|모시송편/.test(n)
  ) {
    types.push("CCP_1B");
  }

  // 인절미/찰떡/찹쌀떡/가래떡 등 → 교반(CCP-2B)
  if (/인절미|찰떡|찹쌀떡|가래떡|떡(\(|$)/.test(n)) {
    types.push("CCP_2B");
  }

  // 중복 제거
  return Array.from(new Set(types));
}

/**
 * CCP 템플릿 조회
 * 1. 제품별 매핑 우선 적용 (defaultCcpTypes)
 * 2. 매핑이 없으면 제품명 기반 추론
 */
export async function getCcpTemplatesForRecipe(args: {
  recipeId?: number;
  productId?: number;
  productName: string;
}): Promise<CcpType[]> {
  // 1. 제품별 매핑 확인
  if (args.productId) {
    try {
      const product = await db.getProductById(args.productId);
      if (product?.defaultCcpTypes && Array.isArray(product.defaultCcpTypes) && product.defaultCcpTypes.length > 0) {
        return product.defaultCcpTypes as CcpType[];
      }
    } catch (error) {
      console.error("제품별 CCP 매핑 조회 실패:", error);
    }
  }
  
  // 2. 매핑이 없으면 제품명 기반 추론
  return inferCcpTypesByProductName(args.productName);
}

/**
 * 배치 생성 시 CCP 인스턴스/행 자동 생성
 * - h_ccp_instances.batch_id = batchId 로 연결
 * - 제품명 기반 CCP 타입 자동 추론
 * - CCP 타입별 기본 행 자동 생성
 */
export async function autoCreateCcpInstancesForBatch(args: {
  siteId: number;
  workDate: string; // YYYY-MM-DD
  batchId: number;
  productId?: number;
  productName: string;
  createdBy?: number;
  tenantId?: number;
}): Promise<{ instanceIds: number[] }> {
  const ccpTypes = await getCcpTemplatesForRecipe({
    productId: args.productId,
    productName: args.productName,
  });

  const instanceIds: number[] = [];

  for (const ccpType of ccpTypes) {
    try {
      // CCP 인스턴스 생성
      const instanceId = await db.createCcpInstance({
        siteId: args.siteId,
        workDate: args.workDate,
        ccpType,
        productName: args.productName,
        batchId: args.batchId,
        status: "draft",
        createdBy: args.createdBy,
        tenantId: args.tenantId,
      });

      // CCP 타입별 기본 행 자동 생성
      if (ccpType === "CCP_1B") {
        // 증숙: 3행 기본 (현장 문서와 동일하게 확장 가능)
        for (let i = 1; i <= 3; i++) {
          await db.createCcpRow({
            instanceId,
            sortOrder: i,
            rowType: "measurement",
            durationMin: 12, // 10~15분 범위의 실무 기본값
            pressureBar: "2.8", // 0.28MPa ≒ 2.8bar
            tempC: "90",
            result: "PASS",
            autoGenerated: 1,
          });
        }
      } else if (ccpType === "CCP_2B") {
        // 교반: 3행 기본(교반기 1/2/3) - 압력 기준이 다르므로 평균값으로 시작
        const pressures = [1.6, 1.2, 1.2]; // 0.16MPa/0.12MPa
        for (let i = 1; i <= 3; i++) {
          await db.createCcpRow({
            instanceId,
            sortOrder: i,
            rowType: "measurement",
            durationMin: 12,
            pressureBar: pressures[i - 1].toString(),
            tempC: "90",
            result: "PASS",
            autoGenerated: 1,
          });
        }
      } else if (ccpType === "CCP_4P") {
        // 금속검출: 2행 기본 (Fe/SUS 각각)
        await db.createCcpRow({
          instanceId,
          sortOrder: 1,
          rowType: "measurement",
          result: "PASS",
          note: "Fe 검출 테스트",
          autoGenerated: 1,
        });
        await db.createCcpRow({
          instanceId,
          sortOrder: 2,
          rowType: "measurement",
          result: "PASS",
          note: "SUS 검출 테스트",
          autoGenerated: 1,
        });
      }

      instanceIds.push(instanceId);
    } catch (error) {
      // CCP 생성 실패 시에도 배치 생성은 유지 (현장 운영 중단 방지)
      console.error(`CCP 인스턴스 생성 실패 (${ccpType}):`, error);
    }
  }

  return { instanceIds };
}
