/**
 * CCP 자동 생성 통계 서비스
 * 
 * 제품별 CCP 자동 생성 성공/실패 건수, CCP 타입별 생성 빈도 등을 조회
 */

import * as db from "../db";

export interface CcpStatsOverview {
  totalBatches: number;
  totalCcpInstances: number;
  autoGeneratedCount: number;
  autoGeneratedRate: number; // 백분율
}

export interface CcpStatsByProduct {
  productId: number;
  productName: string;
  batchCount: number;
  ccpInstanceCount: number;
  autoGeneratedCount: number;
}

export interface CcpStatsByCcpType {
  ccpType: string;
  instanceCount: number;
  autoGeneratedCount: number;
}

export interface CcpStatsTrend {
  date: string; // YYYY-MM-DD
  batchCount: number;
  ccpInstanceCount: number;
  autoGeneratedCount: number;
}

/**
 * CCP 자동 생성 전체 통계 조회
 */
export async function getCcpStatsOverview(args: {
  startDate?: string;
  endDate?: string;
}): Promise<CcpStatsOverview> {
  const dbInstance = await db.getDb();
  if (!dbInstance) throw new Error("Database not available");

  const { hBatches, hCcpInstances } = await import("../../drizzle/schema.js");
  const { sql, and, gte, lte } = await import("drizzle-orm");

  // 날짜 필터 조건
  const dateConditions = [];
  if (args.startDate) {
    dateConditions.push(gte(hBatches.plannedDate, new Date(args.startDate)));
  }
  if (args.endDate) {
    dateConditions.push(lte(hBatches.plannedDate, new Date(args.endDate)));
  }

  // 전체 배치 수
  const batchCountResult = await dbInstance
    .select({ count: sql<number>`COUNT(*)` })
    .from(hBatches)
    .where(dateConditions.length > 0 ? and(...dateConditions) : undefined);
  
  const totalBatches = Number(batchCountResult[0]?.count || 0);

  // 전체 CCP 인스턴스 수
  const ccpInstanceResult = await dbInstance
    .select({ count: sql<number>`COUNT(*)` })
    .from(hCcpInstances)
    .innerJoin(hBatches, sql`${hCcpInstances.batchId} = ${hBatches.id}`)
    .where(dateConditions.length > 0 ? and(...dateConditions) : undefined);
  
  const totalCcpInstances = Number(ccpInstanceResult[0]?.count || 0);

  // CCP 행 기준 자동 생성 수
  const { hCcpRows } = await import("../../drizzle/schema.js");
  const ccpRowsResult = await dbInstance
    .select({
      autoGenerated: sql<number>`SUM(CASE WHEN ${hCcpRows.autoGenerated} = 1 THEN 1 ELSE 0 END)`,
    })
    .from(hCcpRows)
    .innerJoin(hCcpInstances, sql`${hCcpRows.instanceId} = ${hCcpInstances.id}`)
    .innerJoin(hBatches, sql`${hCcpInstances.batchId} = ${hBatches.id}`)
    .where(dateConditions.length > 0 ? and(...dateConditions) : undefined);

  const autoGeneratedCount = Number(ccpRowsResult[0]?.autoGenerated || 0);
  const autoGeneratedRate = totalCcpInstances > 0 
    ? (autoGeneratedCount / totalCcpInstances) * 100 
    : 0;

  return {
    totalBatches,
    totalCcpInstances,
    autoGeneratedCount,
    autoGeneratedRate: Math.round(autoGeneratedRate * 10) / 10, // 소수점 1자리
  };
}

/**
 * 제품별 CCP 자동 생성 통계 조회
 */
export async function getCcpStatsByProduct(args: {
  startDate?: string;
  endDate?: string;
}): Promise<CcpStatsByProduct[]> {
  const dbInstance = await db.getDb();
  if (!dbInstance) throw new Error("Database not available");

  const { hBatches, hCcpInstances, hProducts } = await import("../../drizzle/schema.js");
  const { sql, and, gte, lte } = await import("drizzle-orm");

  // 날짜 필터 조건
  const dateConditions = [];
  if (args.startDate) {
    dateConditions.push(gte(hBatches.plannedDate, new Date(args.startDate)));
  }
  if (args.endDate) {
    dateConditions.push(lte(hBatches.plannedDate, new Date(args.endDate)));
  }

  const { hCcpRows } = await import("../../drizzle/schema.js");
  const results = await dbInstance
    .select({
      productId: hProducts.id,
      productName: hProducts.productName,
      batchCount: sql<number>`COUNT(DISTINCT ${hBatches.id})`,
      ccpInstanceCount: sql<number>`COUNT(DISTINCT ${hCcpInstances.id})`,
      autoGeneratedCount: sql<number>`SUM(CASE WHEN ${hCcpRows.autoGenerated} = 1 THEN 1 ELSE 0 END)`,
    })
    .from(hBatches)
    .innerJoin(hProducts, sql`${hBatches.productId} = ${hProducts.id}`)
    .leftJoin(hCcpInstances, sql`${hCcpInstances.batchId} = ${hBatches.id}`)
    .leftJoin(hCcpRows, sql`${hCcpRows.instanceId} = ${hCcpInstances.id}`)
    .where(dateConditions.length > 0 ? and(...dateConditions) : undefined)
    .groupBy(hProducts.id, hProducts.productName)
    .orderBy(sql`COUNT(DISTINCT ${hCcpInstances.id}) DESC`);

  return results.map((row) => ({
    productId: Number(row.productId),
    productName: row.productName,
    batchCount: Number(row.batchCount),
    ccpInstanceCount: Number(row.ccpInstanceCount || 0),
    autoGeneratedCount: Number(row.autoGeneratedCount || 0),
  }));
}

/**
 * CCP 타입별 생성 통계 조회
 */
export async function getCcpStatsByCcpType(args: {
  startDate?: string;
  endDate?: string;
}): Promise<CcpStatsByCcpType[]> {
  const dbInstance = await db.getDb();
  if (!dbInstance) throw new Error("Database not available");

  const { hBatches, hCcpInstances } = await import("../../drizzle/schema.js");
  const { sql, and, gte, lte } = await import("drizzle-orm");

  // 날짜 필터 조건
  const dateConditions = [];
  if (args.startDate) {
    dateConditions.push(gte(hBatches.plannedDate, new Date(args.startDate)));
  }
  if (args.endDate) {
    dateConditions.push(lte(hBatches.plannedDate, new Date(args.endDate)));
  }

  const { hCcpRows } = await import("../../drizzle/schema.js");
  const results = await dbInstance
    .select({
      ccpType: hCcpInstances.ccpType,
      instanceCount: sql<number>`COUNT(DISTINCT ${hCcpInstances.id})`,
      autoGeneratedCount: sql<number>`SUM(CASE WHEN ${hCcpRows.autoGenerated} = 1 THEN 1 ELSE 0 END)`,
    })
    .from(hCcpInstances)
    .innerJoin(hBatches, sql`${hCcpInstances.batchId} = ${hBatches.id}`)
    .leftJoin(hCcpRows, sql`${hCcpRows.instanceId} = ${hCcpInstances.id}`)
    .where(dateConditions.length > 0 ? and(...dateConditions) : undefined)
    .groupBy(hCcpInstances.ccpType)
    .orderBy(sql`COUNT(DISTINCT ${hCcpInstances.id}) DESC`);

  return results.map((row) => ({
    ccpType: row.ccpType || "Unknown",
    instanceCount: Number(row.instanceCount),
    autoGeneratedCount: Number(row.autoGeneratedCount || 0),
  }));
}

/**
 * CCP 자동 생성 추이 조회 (일별)
 */
export async function getCcpStatsTrend(args: {
  startDate: string;
  endDate: string;
}): Promise<CcpStatsTrend[]> {
  const dbInstance = await db.getDb();
  if (!dbInstance) throw new Error("Database not available");

  const { hBatches, hCcpInstances } = await import("../../drizzle/schema.js");
  const { sql, and, gte, lte } = await import("drizzle-orm");

  const { hCcpRows } = await import("../../drizzle/schema.js");
  const results = await dbInstance
    .select({
      date: sql<string>`DATE(${hBatches.plannedDate})`,
      batchCount: sql<number>`COUNT(DISTINCT ${hBatches.id})`,
      ccpInstanceCount: sql<number>`COUNT(DISTINCT ${hCcpInstances.id})`,
      autoGeneratedCount: sql<number>`SUM(CASE WHEN ${hCcpRows.autoGenerated} = 1 THEN 1 ELSE 0 END)`,
    })
    .from(hBatches)
    .leftJoin(hCcpInstances, sql`${hCcpInstances.batchId} = ${hBatches.id}`)
    .leftJoin(hCcpRows, sql`${hCcpRows.instanceId} = ${hCcpInstances.id}`)
    .where(
      and(
        gte(hBatches.plannedDate, new Date(args.startDate)),
        lte(hBatches.plannedDate, new Date(args.endDate))
      )
    )
    .groupBy(sql`DATE(${hBatches.plannedDate})`)
    .orderBy(sql`DATE(${hBatches.plannedDate}) ASC`);

  return results.map((row) => ({
    date: row.date,
    batchCount: Number(row.batchCount),
    ccpInstanceCount: Number(row.ccpInstanceCount || 0),
    autoGeneratedCount: Number(row.autoGeneratedCount || 0),
  }));
}
