/**
 * 배치 완료 시 일일일지(일일보고서) 자동 생성 서비스
 * 
 * 워크플로우:
 * 1. 배치 정보 조회 (제품명, 수량, CCP 결과 등)
 * 2. 해당 날짜의 기존 일일일지 확인 (중복 방지)
 * 3. 일일일지 생성 또는 기존 일지에 배치 정보 추가
 * 4. h_daily_reports 테이블에 기록
 */

import { getDb } from "../db";
import { sql, eq, and } from "drizzle-orm";

interface DailyReportResult {
  success: boolean;
  reportId: number | null;
  isNew: boolean;
  message: string;
}

export async function autoGenerateDailyReport(
  batchId: number,
  userId: number
): Promise<DailyReportResult> {
  const db = await getDb();
  if (!db) throw new Error("Database connection not available");

  try {
    // 1. 배치 정보 조회
    const { hBatches } = await import("../../drizzle/schema");
    const [batch] = await db.select().from(hBatches).where(eq(hBatches.id, batchId)).limit(1);
    
    if (!batch) {
      throw new Error(`배치 ID ${batchId}를 찾을 수 없습니다.`);
    }

    const siteId = Number(batch.siteId);
    const tenantId = Number(batch.tenantId);
    const reportDate = new Date().toISOString().split("T")[0];

    // 2. 해당 날짜의 기존 일일보고서 확인
    const existingReport = await db.execute(sql`
      SELECT id, summary FROM h_daily_reports 
      WHERE site_id = ${siteId} 
        AND report_date = ${reportDate}
        AND tenant_id = ${tenantId}
      LIMIT 1
    `);

    // 3. 배치 관련 데이터 수집
    // 3-1. 제품 정보
    const productInfo = await db.execute(sql`
      SELECT p.product_name, p.product_code 
      FROM h_products p 
      WHERE p.id = ${Number(batch.productId)}
      LIMIT 1
    `);
    const product = (productInfo as any)[0]?.[0] || { product_name: "미확인", product_code: "" };

    // 3-2. CCP 기록 조회
    const ccpRecords = await db.execute(sql`
      SELECT COUNT(*) as total_count,
             SUM(CASE WHEN status = 'normal' THEN 1 ELSE 0 END) as normal_count,
             SUM(CASE WHEN status = 'deviation' THEN 1 ELSE 0 END) as deviation_count
      FROM h_ccp_monitoring 
      WHERE batch_id = ${batchId}
    `);
    const ccp = (ccpRecords as any)[0]?.[0] || { total_count: 0, normal_count: 0, deviation_count: 0 };

    // 3-3. 원료 출고 기록 조회
    const materialRecords = await db.execute(sql`
      SELECT COUNT(DISTINCT source_line_id) as material_count,
             SUM(ABS(CAST(amount AS DECIMAL(15,2)))) as total_cost
      FROM h_inventory_transactions 
      WHERE source_type = 'BATCH' AND source_id = ${batchId} AND action_type = 'AUTO_ISSUE'
    `);
    const materials = (materialRecords as any)[0]?.[0] || { material_count: 0, total_cost: 0 };

    // 4. 일일보고서 요약 데이터 생성
    const batchSummary = {
      batchId: batchId,
      batchCode: batch.batchCode || `BATCH-${batchId}`,
      productName: product.product_name,
      productCode: product.product_code,
      plannedQuantity: parseFloat(batch.plannedQuantity?.toString() || "0"),
      actualQuantity: parseFloat(batch.actualQuantity?.toString() || "0"),
      status: batch.status,
      ccpTotal: Number(ccp.total_count),
      ccpNormal: Number(ccp.normal_count),
      ccpDeviation: Number(ccp.deviation_count),
      materialCount: Number(materials.material_count),
      totalMaterialCost: parseFloat(materials.total_cost?.toString() || "0"),
      completedAt: new Date().toISOString()
    };

    let reportId: number;
    let isNew: boolean;

    if (existingReport && (existingReport as any)[0]?.length > 0) {
      // 기존 보고서에 배치 정보 추가
      const existing = (existingReport as any)[0][0];
      reportId = Number(existing.id);
      isNew = false;

      let existingSummary: any = {};
      try {
        existingSummary = JSON.parse(existing.summary || "{}");
      } catch {
        existingSummary = { batches: [] };
      }

      if (!existingSummary.batches) {
        existingSummary.batches = [];
      }
      
      // 중복 배치 방지
      const alreadyExists = existingSummary.batches.some((b: any) => b.batchId === batchId);
      if (!alreadyExists) {
        existingSummary.batches.push(batchSummary);
      }

      // 요약 통계 업데이트
      existingSummary.totalBatches = existingSummary.batches.length;
      existingSummary.totalProduction = existingSummary.batches.reduce(
        (sum: number, b: any) => sum + (b.actualQuantity || 0), 0
      );
      existingSummary.totalCcpDeviations = existingSummary.batches.reduce(
        (sum: number, b: any) => sum + (b.ccpDeviation || 0), 0
      );

      await db.execute(sql`
        UPDATE h_daily_reports 
        SET summary = ${JSON.stringify(existingSummary)}
        WHERE id = ${reportId}
      `);

    } else {
      // 새 일일보고서 생성
      isNew = true;

      const summary = {
        batches: [batchSummary],
        totalBatches: 1,
        totalProduction: batchSummary.actualQuantity,
        totalCcpDeviations: batchSummary.ccpDeviation,
        generatedAt: new Date().toISOString()
      };

      const insertResult = await db.execute(sql`
        INSERT INTO h_daily_reports (site_id, report_date, report_type, summary, generated_by, tenant_id)
        VALUES (${siteId}, ${reportDate}, 'production', ${JSON.stringify(summary)}, ${userId}, ${tenantId})
      `);

      reportId = Number((insertResult as any)[0]?.insertId || 0);
    }

    console.log(`[autoDailyReport] 배치 #${batchId} → 일일보고서 #${reportId} ${isNew ? "생성" : "업데이트"} 완료`);

    return {
      success: true,
      reportId,
      isNew,
      message: isNew 
        ? `일일보고서가 새로 생성되었습니다 (ID: ${reportId})`
        : `기존 일일보고서에 배치 정보가 추가되었습니다 (ID: ${reportId})`
    };

  } catch (error: any) {
    console.error(`[autoDailyReport] 배치 #${batchId} 일일보고서 생성 실패:`, error);
    return {
      success: false,
      reportId: null,
      isNew: false,
      message: error.message || "일일보고서 생성 실패"
    };
  }
}
