/**
 * 자동 기간별 일지 생성 서비스 (주간/월간/연간)
 *
 * ─────────────────────────────────────────────
 * 트리거: 배치 생성 시 (auto/manual 모두)
 *  → 일일일지: autoGenerateDailyReport (별도 파일)
 *  → 주간일지: 해당 주 첫 배치 → autoGenerateWeeklyLog
 *  → 월간일지: 해당 월 첫 배치 → autoGenerateMonthlyLog
 *  → 연간일지: 연간 첫 작성일 기준 → autoGenerateYearlyLog
 *
 * 데이터 저장:
 *  → h_generic_checklist_records 테이블 (form_type으로 구분)
 *  → 프론트엔드 WeeklyLogForm / MonthlyLogForm 양식과 동일한 구조
 *
 * 문서결재설정 연동:
 *  → h_document_approval_settings에서 검토자/승인자 조회
 *  → h_approval_requests 생성 시 설정값 반영
 *
 * 휴무 관리 (h_holidays) 연동:
 *  → 주간/월간 "첫 배치"는 h_holidays를 제외한 첫 영업일 배치
 *  → 이미 해당 기간에 일지가 있으면 skip
 * ─────────────────────────────────────────────
 */

import { getDb, getRawConnection } from "../db";
import { sql } from "drizzle-orm";

export interface PeriodicLogResult {
  success: boolean;
  logType: "weekly" | "monthly" | "yearly";
  recordId: number | null;
  approvalRequestId: number | null;
  isNew: boolean;
  message: string;
}

// ============================================================================
// 문서결재설정 조회 헬퍼
// ============================================================================

interface ApprovalSetting {
  authorEmployeeId: number | null;
  reviewerEmployeeId: number | null;
  approverEmployeeId: number | null;
}

async function getApprovalSettingForType(
  tenantId: number,
  documentType: string
): Promise<ApprovalSetting> {
  try {
    const db = await getDb();
    if (!db) return { authorEmployeeId: null, reviewerEmployeeId: null, approverEmployeeId: null };

    const result = await db.execute(sql`
      SELECT author_employee_id, reviewer_employee_id, approver_employee_id
      FROM h_document_approval_settings
      WHERE document_type = ${documentType}
        AND tenant_id = ${tenantId}
        AND is_active = 1
      LIMIT 1
    `);
    const rows = (result as any)[0] || [];
    if (rows.length === 0) {
      return { authorEmployeeId: null, reviewerEmployeeId: null, approverEmployeeId: null };
    }
    return {
      authorEmployeeId: rows[0].author_employee_id ? Number(rows[0].author_employee_id) : null,
      reviewerEmployeeId: rows[0].reviewer_employee_id ? Number(rows[0].reviewer_employee_id) : null,
      approverEmployeeId: rows[0].approver_employee_id ? Number(rows[0].approver_employee_id) : null,
    };
  } catch (err) {
    console.error(`[autoPeriodicLogs] 문서결재설정 조회 실패 (${documentType}):`, err);
    return { authorEmployeeId: null, reviewerEmployeeId: null, approverEmployeeId: null };
  }
}

// ============================================================================
// 주간일지 기본 폼 데이터 (WeeklyLogForm.tsx 구조와 동일)
// ============================================================================

function buildDefaultWeeklyFormData(date: string, batchInfo?: { productName: string }) {
  return {
    date,
    checkerName: "",
    managementNotes: batchInfo
      ? `[자동생성] 주간점검 - 배치: ${batchInfo.productName}`
      : "[자동생성] 주간점검",
    hygieneChecks: [
      { category: "청소소독", itemOrder: 1, itemText: "냉장창고 내부 청소 상태는 양호한가?", checkResult: null },
      { category: "청소소독", itemOrder: 2, itemText: "작업장 벽, 제조설비(제품과 직접 닿지 않는 부분)에 대한 청소.소독 상태는 양호한가?", checkResult: null },
      { category: "위생관리", itemOrder: 3, itemText: "위생복 세탁은 실시하였는가?", checkResult: null },
      { category: "위생관리", itemOrder: 4, itemText: "작업장 내 환기 시스템이 정상 작동하고 있는가?", checkResult: null },
      { category: "폐기물관리", itemOrder: 5, itemText: "폐기물 처리 및 반출이 주기적으로 이루어지고 있는가?", checkResult: null },
      { category: "용수관리", itemOrder: 6, itemText: "용수(물) 관리 상태가 양호한가?", checkResult: null },
    ],
    hygieneNotes: { specialNotes: "", improvementAction: "", actionBy: "", confirmedBy: "" },
    pestChecks: [
      { category: "포충등", itemOrder: 1, itemText: "포충등 점검 - 먼지 청소 상태", checkResult: null },
      { category: "포충등", itemOrder: 2, itemText: "포충등 점검 - 끈끈이 상태", checkResult: null },
      { category: "해충", itemOrder: 3, itemText: "파리류 포획 여부", checkResult: null },
      { category: "해충", itemOrder: 4, itemText: "초파리류 포획 여부", checkResult: null },
      { category: "해충", itemOrder: 5, itemText: "나방파리류 포획 여부", checkResult: null },
      { category: "해충", itemOrder: 6, itemText: "날개벌레류 포획 여부", checkResult: null },
      { category: "해충", itemOrder: 7, itemText: "바퀴벌레 발견 여부", checkResult: null },
      { category: "해충", itemOrder: 8, itemText: "개미류 발견 여부", checkResult: null },
      { category: "해충", itemOrder: 9, itemText: "거미류 발견 여부", checkResult: null },
      { category: "서류", itemOrder: 10, itemText: "쥐류 흔적 여부 (배설물, 발자국 등)", checkResult: null },
      { category: "기타", itemOrder: 11, itemText: "기타 해충 발견 여부", checkResult: null },
      { category: "방충관리", itemOrder: 12, itemText: "방충망/에어커튼 등 방충시설 정상 작동 여부", checkResult: null },
    ],
    pestNotes: { specialNotes: "", improvementAction: "", actionBy: "", confirmedBy: "" },
    autoGenerated: true,
    generatedAt: new Date().toISOString(),
  };
}

// ============================================================================
// 월간일지 기본 폼 데이터 (MonthlyLogForm.tsx 구조와 동일)
// ============================================================================

function buildDefaultMonthlyFormData(date: string, batchInfo?: { productName: string }) {
  const yearMonth = date.substring(0, 7);
  return {
    date,
    checkerName: "",
    confirmerName: "",
    hygieneChecks: [
      { category: "청소소독", itemOrder: 1, itemText: "작업장 전체 대청소 및 소독 실시 여부", checkResult: null },
      { category: "청소소독", itemOrder: 2, itemText: "환기시설, 배수시설 청소 상태", checkResult: null },
      { category: "교육훈련", itemOrder: 3, itemText: "종사자 위생교육 실시 여부", checkResult: null },
      { category: "교육훈련", itemOrder: 4, itemText: "HACCP 관련 교육 실시 여부", checkResult: null },
      { category: "설비관리", itemOrder: 5, itemText: "제조설비 정기 점검 및 정비 실시 여부", checkResult: null },
      { category: "설비관리", itemOrder: 6, itemText: "계측기기 교정 상태 확인", checkResult: null },
      { category: "방충방서", itemOrder: 7, itemText: "방역업체 정기 방역 실시 여부", checkResult: null },
      { category: "방충방서", itemOrder: 8, itemText: "포충등/끈끈이 교체 실시 여부", checkResult: null },
      { category: "용수관리", itemOrder: 9, itemText: "용수 수질검사 실시 여부", checkResult: null },
      { category: "기타", itemOrder: 10, itemText: "보존식 관리 기록 확인", checkResult: null },
    ],
    hygieneNotes: { specialNotes: "", improvementAction: "", actionBy: "", confirmedBy: "" },
    ccpChecks: [
      { category: "가열공정", itemOrder: 1, itemText: "CCP 한계기준 온도/시간 모니터링 기록 확인", checkResult: null, notes: "" },
      { category: "가열공정", itemOrder: 2, itemText: "모니터링 장비(온도계 등) 교정 확인", checkResult: null, notes: "" },
      { category: "가열공정", itemOrder: 3, itemText: "온도 측정 방법 적절성 확인", checkResult: null, notes: "" },
      { category: "가열공정", itemOrder: 4, itemText: "시간 측정 방법 적절성 확인", checkResult: null, notes: "" },
      { category: "가열공정", itemOrder: 5, itemText: "중심부 온도 측정 방법 적절성 확인", checkResult: null, notes: "" },
      { category: "가열공정", itemOrder: 6, itemText: "모니터링 담당자 현장 관찰 (관찰일:", checkResult: null, notes: "" },
      { category: "가열공정", itemOrder: 7, itemText: "개선조치 절차 이해도 확인", checkResult: null, notes: "" },
      { category: "가열공정", itemOrder: 8, itemText: "모니터링 담당자 면담 (면담일:", checkResult: null, notes: "" },
      { category: "금속검출", itemOrder: 9, itemText: "금속검출기 테스트 기록 확인", checkResult: null, notes: "" },
      { category: "금속검출", itemOrder: 10, itemText: "금속검출기 교정 확인", checkResult: null, notes: "" },
      { category: "금속검출", itemOrder: 11, itemText: "금속검출 방법 적절성 확인", checkResult: null, notes: "" },
      { category: "금속검출", itemOrder: 12, itemText: "모니터링 담당자 현장 관찰 (관찰일:", checkResult: null, notes: "" },
      { category: "금속검출", itemOrder: 13, itemText: "개선조치 절차 이해도 확인", checkResult: null, notes: "" },
      { category: "금속검출", itemOrder: 14, itemText: "모니터링 담당자 면담 (면담일:", checkResult: null, notes: "" },
    ],
    ccpDeviation: { deviationDetails: "", improvementAction: "", actionTaker: "", confirmation: "" },
    autoGenerated: true,
    autoNote: batchInfo
      ? `[자동생성] ${yearMonth} 월간점검 - 배치: ${batchInfo.productName}`
      : `[자동생성] ${yearMonth} 월간점검`,
    generatedAt: new Date().toISOString(),
  };
}

// ============================================================================
// 주간일지 자동 생성
// ============================================================================

/**
 * 해당 주의 첫 배치인지 확인 후 주간일지 자동 생성
 * - h_generic_checklist_records (form_type='weekly_log') 기반
 * - WeeklyLogForm.tsx 양식과 동일한 form_data 구조
 * - h_document_approval_settings 연동
 */
export async function autoGenerateWeeklyLog(
  tenantId: number,
  siteId: number,
  workDate: string,
  userId: number,
  batchInfo?: { batchId: number; productName: string; plannedQty: number }
): Promise<PeriodicLogResult> {
  const db = await getDb();
  if (!db) return { success: false, logType: "weekly", recordId: null, approvalRequestId: null, isNew: false, message: "DB 연결 실패" };

  try {
    // 1. 해당 주의 월~일 범위 계산
    const { weekStart, weekEnd } = getWeekRange(workDate);

    // 2. 이미 해당 주에 주간일지가 있으면 skip (h_generic_checklist_records 기준)
    const existingResult = await db.execute(sql`
      SELECT id FROM h_generic_checklist_records
      WHERE form_type = 'weekly_log'
        AND tenant_id = ${tenantId}
        AND form_date BETWEEN ${weekStart} AND ${weekEnd}
      LIMIT 1
    `);
    const existingRows = (existingResult as any)[0] || [];
    if (existingRows.length > 0) {
      return {
        success: true, logType: "weekly",
        recordId: existingRows[0].id,
        approvalRequestId: null, isNew: false,
        message: `주간일지 이미 존재 (ID: ${existingRows[0].id})`,
      };
    }

    // 3. 해당 주에 이전 배치가 있었는지 확인 (현재가 첫 배치인지)
    const conn = await getRawConnection();
    const isFirst = await isFirstBatchOfPeriod(conn, tenantId, weekStart, workDate);
    if (!isFirst) {
      return {
        success: true, logType: "weekly",
        recordId: null, approvalRequestId: null, isNew: false,
        message: `이번 주 첫 배치가 아니므로 주간일지 미생성`,
      };
    }

    // 4. 문서결재설정 조회
    const approvalSetting = await getApprovalSettingForType(tenantId, 'weekly_log');

    // 5. 주간일지 생성 (h_generic_checklist_records)
    const formData = buildDefaultWeeklyFormData(workDate, batchInfo);

    const seqResult = await db.execute(sql`
      SELECT COALESCE(MAX(tenant_seq), 0) + 1 as next_seq
      FROM h_generic_checklist_records
      WHERE form_type = 'weekly_log'
        AND tenant_id = ${tenantId}
        AND YEAR(created_at) = YEAR(NOW())
    `);
    const nextSeq = Number((seqResult as any)[0]?.[0]?.next_seq || 1);

    const title = `주간일지 - ${weekStart} ~ ${weekEnd}`;
    const createdBy = approvalSetting.authorEmployeeId || userId;

    const insertResult = await db.execute(sql`
      INSERT INTO h_generic_checklist_records
        (site_id, tenant_id, form_type, tenant_seq, form_date, title, form_data, status, created_by)
      VALUES
        (${siteId}, ${tenantId}, 'weekly_log', ${nextSeq}, ${workDate}, ${title},
         ${JSON.stringify(formData)}, 'draft', ${createdBy})
    `);
    const recordId = Number((insertResult as any)[0]?.insertId || 0);

    // 6. 승인요청 등록 (h_approval_requests)
    const approvalTitle = `[주간일지] ${weekStart} ~ ${weekEnd} 주간 위생점검`;
    const approvalDesc =
      `점검기간: ${weekStart} ~ ${weekEnd}\n` +
      `점검일: ${workDate}\n` +
      (approvalSetting.reviewerEmployeeId ? `검토자 ID: ${approvalSetting.reviewerEmployeeId}\n` : '') +
      (approvalSetting.approverEmployeeId ? `승인자 ID: ${approvalSetting.approverEmployeeId}\n` : '') +
      `[자동생성 - 위생점검 항목을 작성해주세요]`;

    const approvalInsert = await db.execute(sql`
      INSERT INTO h_approval_requests
        (site_id, tenant_id, request_type, reference_type, reference_id,
         title, description, status, priority, requested_by, created_at)
      VALUES
        (${siteId}, ${tenantId}, 'weekly_log', 'checklist', ${recordId},
         ${approvalTitle}, ${approvalDesc}, 'pending_review', 'medium', ${createdBy}, NOW())
    `);
    const approvalRequestId = Number((approvalInsert as any)[0]?.insertId || 0);

    console.log(`[autoPeriodicLogs] 주간일지 생성: #${recordId}, 승인요청: #${approvalRequestId}`);

    return {
      success: true, logType: "weekly",
      recordId, approvalRequestId, isNew: true,
      message: `주간일지 자동 생성 완료 (#${recordId})`,
    };
  } catch (error: any) {
    console.error("[autoPeriodicLogs] 주간일지 생성 실패:", error);
    return {
      success: false, logType: "weekly",
      recordId: null, approvalRequestId: null, isNew: false,
      message: error.message || "주간일지 생성 실패",
    };
  }
}

// ============================================================================
// 월간일지 자동 생성
// ============================================================================

/**
 * 해당 월의 첫 배치인지 확인 후 월간일지 자동 생성
 * - h_generic_checklist_records (form_type='monthly_log') 기반
 * - MonthlyLogForm.tsx 양식과 동일한 form_data 구조
 * - h_document_approval_settings 연동
 */
export async function autoGenerateMonthlyLog(
  tenantId: number,
  siteId: number,
  workDate: string,
  userId: number,
  batchInfo?: { batchId: number; productName: string; plannedQty: number }
): Promise<PeriodicLogResult> {
  const db = await getDb();
  if (!db) return { success: false, logType: "monthly", recordId: null, approvalRequestId: null, isNew: false, message: "DB 연결 실패" };

  try {
    // 1. 해당 월의 1일~말일 범위
    const { monthStart, monthEnd } = getMonthRange(workDate);

    // 2. 이미 해당 월에 월간일지가 있으면 skip (h_generic_checklist_records 기준)
    const existingResult = await db.execute(sql`
      SELECT id FROM h_generic_checklist_records
      WHERE form_type = 'monthly_log'
        AND tenant_id = ${tenantId}
        AND form_date BETWEEN ${monthStart} AND ${monthEnd}
      LIMIT 1
    `);
    const existingRows = (existingResult as any)[0] || [];
    if (existingRows.length > 0) {
      return {
        success: true, logType: "monthly",
        recordId: existingRows[0].id,
        approvalRequestId: null, isNew: false,
        message: `월간일지 이미 존재`,
      };
    }

    // 3. 해당 월 첫 배치 확인
    const conn = await getRawConnection();
    const isFirst = await isFirstBatchOfPeriod(conn, tenantId, monthStart, workDate);
    if (!isFirst) {
      return {
        success: true, logType: "monthly",
        recordId: null, approvalRequestId: null, isNew: false,
        message: `이번 달 첫 배치가 아니므로 월간일지 미생성`,
      };
    }

    const yearMonth = workDate.substring(0, 7); // "YYYY-MM"

    // 4. 문서결재설정 조회
    const approvalSetting = await getApprovalSettingForType(tenantId, 'monthly_log');

    // 5. 월간일지 생성 (h_generic_checklist_records)
    const formData = buildDefaultMonthlyFormData(workDate, batchInfo);

    const seqResult = await db.execute(sql`
      SELECT COALESCE(MAX(tenant_seq), 0) + 1 as next_seq
      FROM h_generic_checklist_records
      WHERE form_type = 'monthly_log'
        AND tenant_id = ${tenantId}
        AND YEAR(created_at) = YEAR(NOW())
    `);
    const nextSeq = Number((seqResult as any)[0]?.[0]?.next_seq || 1);

    const title = `월간일지 - ${yearMonth}`;
    const createdBy = approvalSetting.authorEmployeeId || userId;

    const insertResult = await db.execute(sql`
      INSERT INTO h_generic_checklist_records
        (site_id, tenant_id, form_type, tenant_seq, form_date, title, form_data, status, created_by)
      VALUES
        (${siteId}, ${tenantId}, 'monthly_log', ${nextSeq}, ${workDate}, ${title},
         ${JSON.stringify(formData)}, 'draft', ${createdBy})
    `);
    const recordId = Number((insertResult as any)[0]?.insertId || 0);

    // 6. 승인요청 등록
    const approvalTitle = `[월간일지] ${yearMonth} 월간 위생/CCP 점검`;
    const approvalDesc =
      `점검월: ${yearMonth}\n` +
      `점검일: ${workDate}\n` +
      (approvalSetting.reviewerEmployeeId ? `검토자 ID: ${approvalSetting.reviewerEmployeeId}\n` : '') +
      (approvalSetting.approverEmployeeId ? `승인자 ID: ${approvalSetting.approverEmployeeId}\n` : '') +
      `[자동생성 - 점검 항목을 작성해주세요]`;

    const approvalInsert = await db.execute(sql`
      INSERT INTO h_approval_requests
        (site_id, tenant_id, request_type, reference_type, reference_id,
         title, description, status, priority, requested_by, created_at)
      VALUES
        (${siteId}, ${tenantId}, 'monthly_log', 'checklist', ${recordId},
         ${approvalTitle}, ${approvalDesc}, 'pending_review', 'medium', ${createdBy}, NOW())
    `);
    const approvalRequestId = Number((approvalInsert as any)[0]?.insertId || 0);

    console.log(`[autoPeriodicLogs] 월간일지 생성: #${recordId}, 승인요청: #${approvalRequestId}`);

    return {
      success: true, logType: "monthly",
      recordId, approvalRequestId, isNew: true,
      message: `월간일지 자동 생성 완료 (#${recordId})`,
    };
  } catch (error: any) {
    console.error("[autoPeriodicLogs] 월간일지 생성 실패:", error);
    return {
      success: false, logType: "monthly",
      recordId: null, approvalRequestId: null, isNew: false,
      message: error.message || "월간일지 생성 실패",
    };
  }
}

// ============================================================================
// 연간일지 자동 생성
// ============================================================================

/**
 * 연간일지 자동 생성
 * - h_generic_checklist_records (form_type='yearly_log') 기반
 * - h_document_approval_settings 연동
 */
export async function autoGenerateYearlyLog(
  tenantId: number,
  siteId: number,
  workDate: string,
  userId: number,
): Promise<PeriodicLogResult> {
  const db = await getDb();
  if (!db) return { success: false, logType: "yearly", recordId: null, approvalRequestId: null, isNew: false, message: "DB 연결 실패" };

  try {
    const year = Number(workDate.split("-")[0]);
    const yearStart = `${year}-01-01`;
    const yearEnd = `${year}-12-31`;

    // 1. 올해 연간일지가 이미 있으면 skip
    const existingResult = await db.execute(sql`
      SELECT id FROM h_generic_checklist_records
      WHERE form_type = 'yearly_log'
        AND tenant_id = ${tenantId}
        AND form_date BETWEEN ${yearStart} AND ${yearEnd}
      LIMIT 1
    `);
    const existingRows = (existingResult as any)[0] || [];
    if (existingRows.length > 0) {
      return {
        success: true, logType: "yearly",
        recordId: existingRows[0].id,
        approvalRequestId: null, isNew: false,
        message: `${year}년 연간일지 이미 존재`,
      };
    }

    // 2. 문서결재설정 조회
    const approvalSetting = await getApprovalSettingForType(tenantId, 'yearly_log');

    // 3. 연간일지 생성
    const seqResult = await db.execute(sql`
      SELECT COALESCE(MAX(tenant_seq), 0) + 1 as next_seq
      FROM h_generic_checklist_records
      WHERE form_type = 'yearly_log'
        AND tenant_id = ${tenantId}
        AND YEAR(created_at) = YEAR(NOW())
    `);
    const nextSeq = Number((seqResult as any)[0]?.[0]?.next_seq || 1);

    const title = `연간일지 - ${year}년`;
    const createdBy = approvalSetting.authorEmployeeId || userId;

    const formData = {
      date: workDate,
      year,
      inspector: "",
      // 검교정 항목 (YearlyLogModal 양식과 동일)
      calibrationChecks: [
        { equipmentName: "냉동고 판넬 온도계", result: null, notes: "" },
        { equipmentName: "냉장고 온도계", result: null, notes: "" },
        { equipmentName: "타이머", result: null, notes: "" },
        { equipmentName: "탐침 온도계", result: null, notes: "" },
        { equipmentName: "저울", result: null, notes: "" },
        { equipmentName: "오븐 온도계", result: null, notes: "" },
        { equipmentName: "금속검출기", result: null, notes: "" },
        { equipmentName: "온습도계", result: null, notes: "" },
        { equipmentName: "방사 온도계 1", result: null, notes: "" },
        { equipmentName: "방사 온도계 2", result: null, notes: "" },
        { equipmentName: "오븐 작업용 온도계", result: null, notes: "" },
      ],
      // 개별 필드도 유지 (YearlyLogModal 호환)
      calibrationFreezerPanelThermometer: "",
      calibrationRefrigerator: "",
      calibrationTimer: "",
      calibrationProbeThermometer: "",
      calibrationScale: "",
      calibrationOven: "",
      calibrationMetalDetector: "",
      calibrationHygrothermograph: "",
      calibrationRadiationThermometer1: "",
      calibrationRadiationThermometer2: "",
      calibrationOvenWorkThermometer: "",
      // 금속검출기 정기 점검
      metalDetectorCheckDate: "",
      metalDetectorNextCheck: "",
      // 정기 검증
      periodicVerificationDate: "",
      periodicVerificationNext: "",
      // 특이사항/개선조치
      specialNotes: "",
      improvementAction: "",
      actionTaker: "",
      confirmation: "",
      autoGenerated: true,
      autoNote: `[자동생성] ${year}년 연간 검교정 점검 - 미작성 항목을 작성해주세요`,
      generatedAt: new Date().toISOString(),
    };

    const insertResult = await db.execute(sql`
      INSERT INTO h_generic_checklist_records
        (site_id, tenant_id, form_type, tenant_seq, form_date, title, form_data, status, created_by)
      VALUES
        (${siteId}, ${tenantId}, 'yearly_log', ${nextSeq}, ${workDate}, ${title},
         ${JSON.stringify(formData)}, 'draft', ${createdBy})
    `);
    const recordId = Number((insertResult as any)[0]?.insertId || 0);

    // 4. 승인요청 등록
    const approvalTitle = `[연간일지] ${year}년 연간 검교정 점검`;
    const approvalDesc =
      `점검년도: ${year}\n` +
      `작성일: ${workDate}\n` +
      (approvalSetting.reviewerEmployeeId ? `검토자 ID: ${approvalSetting.reviewerEmployeeId}\n` : '') +
      (approvalSetting.approverEmployeeId ? `승인자 ID: ${approvalSetting.approverEmployeeId}\n` : '') +
      `[자동생성 - 검교정 점검 항목을 작성해주세요]`;

    const approvalInsert = await db.execute(sql`
      INSERT INTO h_approval_requests
        (site_id, tenant_id, request_type, reference_type, reference_id,
         title, description, status, priority, requested_by, created_at)
      VALUES
        (${siteId}, ${tenantId}, 'yearly_log', 'checklist', ${recordId},
         ${approvalTitle}, ${approvalDesc}, 'pending_review', 'medium', ${createdBy}, NOW())
    `);
    const approvalRequestId = Number((approvalInsert as any)[0]?.insertId || 0);

    console.log(`[autoPeriodicLogs] 연간일지 생성: #${recordId}, 승인요청: #${approvalRequestId}`);

    return {
      success: true, logType: "yearly",
      recordId, approvalRequestId, isNew: true,
      message: `${year}년 연간일지 자동 생성 완료 (#${recordId})`,
    };
  } catch (error: any) {
    console.error("[autoPeriodicLogs] 연간일지 생성 실패:", error);
    return {
      success: false, logType: "yearly",
      recordId: null, approvalRequestId: null, isNew: false,
      message: error.message || "연간일지 생성 실패",
    };
  }
}

// ============================================================================
// 통합 자동 기간별 일지 생성 (배치 생성 시 호출)
// ============================================================================

export interface AllPeriodicLogsResult {
  weekly: PeriodicLogResult;
  monthly: PeriodicLogResult;
  yearly: PeriodicLogResult;
}

/**
 * 배치 생성 시 주간/월간/연간 일지 일괄 확인 및 생성
 * - auto/manual 모두 실행 (기간별 일지는 배치 모드와 무관하게 필수 HACCP 문서)
 */
export async function autoGenerateAllPeriodicLogs(
  mode: "auto" | "manual",
  tenantId: number,
  siteId: number,
  workDate: string,
  userId: number,
  batchInfo?: { batchId: number; productName: string; plannedQty: number }
): Promise<AllPeriodicLogsResult | null> {
  // workDate 유효성 검증
  if (!workDate || !/^\d{4}-\d{2}-\d{2}$/.test(workDate)) {
    console.error(`[autoPeriodicLogs] 유효하지 않은 workDate: ${workDate}`);
    return null;
  }

  console.log(`[autoPeriodicLogs] 배치 모드(${mode}) → 주간/월간/연간 일지 확인 (${workDate})`);

  const [weekly, monthly, yearly] = await Promise.allSettled([
    autoGenerateWeeklyLog(tenantId, siteId, workDate, userId, batchInfo),
    autoGenerateMonthlyLog(tenantId, siteId, workDate, userId, batchInfo),
    autoGenerateYearlyLog(tenantId, siteId, workDate, userId),
  ]);

  const result: AllPeriodicLogsResult = {
    weekly: weekly.status === "fulfilled" ? weekly.value : {
      success: false, logType: "weekly", recordId: null, approvalRequestId: null, isNew: false,
      message: (weekly as PromiseRejectedResult).reason?.message || "주간일지 생성 실패",
    },
    monthly: monthly.status === "fulfilled" ? monthly.value : {
      success: false, logType: "monthly", recordId: null, approvalRequestId: null, isNew: false,
      message: (monthly as PromiseRejectedResult).reason?.message || "월간일지 생성 실패",
    },
    yearly: yearly.status === "fulfilled" ? yearly.value : {
      success: false, logType: "yearly", recordId: null, approvalRequestId: null, isNew: false,
      message: (yearly as PromiseRejectedResult).reason?.message || "연간일지 생성 실패",
    },
  };

  const newLogs = [result.weekly, result.monthly, result.yearly].filter(r => r.isNew);
  if (newLogs.length > 0) {
    console.log(`[autoPeriodicLogs] 기간별 일지 ${newLogs.length}건 신규 생성: ${newLogs.map(l => l.logType).join(", ")}`);
  }

  return result;
}

// ============================================================================
// 유틸리티 함수
// ============================================================================

/** 월요일~일요일 주 범위 계산 (ISO 주 기준) — timezone-safe */
function getWeekRange(dateStr: string): { weekStart: string; weekEnd: string } {
  const [y, m, dd] = dateStr.split("-").map(Number);
  const d = new Date(y, m - 1, dd);
  const day = d.getDay(); // 0=Sun, 1=Mon, ...
  const diffToMon = day === 0 ? -6 : 1 - day;
  const monday = new Date(y, m - 1, dd + diffToMon);
  const sunday = new Date(monday.getFullYear(), monday.getMonth(), monday.getDate() + 6);
  return {
    weekStart: formatLocalDate(monday),
    weekEnd: formatLocalDate(sunday),
  };
}

/** 월 범위 계산 — timezone-safe */
function getMonthRange(dateStr: string): { monthStart: string; monthEnd: string } {
  const [y, m] = dateStr.split("-").map(Number);
  const first = new Date(y, m - 1, 1);
  const last = new Date(y, m, 0);
  return {
    monthStart: formatLocalDate(first),
    monthEnd: formatLocalDate(last),
  };
}

/** YYYY-MM-DD 포맷 (local timezone) */
function formatLocalDate(d: Date): string {
  const yyyy = d.getFullYear();
  const mm = String(d.getMonth() + 1).padStart(2, "0");
  const dd = String(d.getDate()).padStart(2, "0");
  return `${yyyy}-${mm}-${dd}`;
}

/**
 * 해당 기간(periodStart ~ workDate) 내에 이전 배치가 있었는지 확인
 * → h_holidays 연동: 공휴일/휴무일 배치는 제외하고 판단
 */
async function isFirstBatchOfPeriod(
  conn: any,
  tenantId: number,
  periodStart: string,
  workDate: string,
): Promise<boolean> {
  const [priorBatches] = await (conn as any).execute(
    `SELECT COUNT(*) as cnt FROM h_batches
     WHERE tenant_id = ?
       AND planned_date >= ?
       AND planned_date < ?`,
    [tenantId, periodStart, workDate]
  );
  const priorCount = Number((priorBatches as any[])[0]?.cnt || 0);

  if (priorCount === 0) return true;

  // 이전 배치가 있지만 모두 휴무일이었으면 → 영업일 기준 첫 배치
  const [holidayBatches] = await (conn as any).execute(
    `SELECT COUNT(*) as cnt FROM h_batches b
     INNER JOIN h_holidays h ON h.holiday_date = b.planned_date AND h.tenant_id = b.tenant_id
     WHERE b.tenant_id = ?
       AND b.planned_date >= ?
       AND b.planned_date < ?`,
    [tenantId, periodStart, workDate]
  );
  const holidayCount = Number((holidayBatches as any[])[0]?.cnt || 0);

  return holidayCount >= priorCount;
}
