/**
 * 자동 기간별 일지 생성 서비스 (주간/월간/연간)
 *
 * ─────────────────────────────────────────────
 * 트리거: 자동 배치 생성 시 (auto mode)
 *  → 일일일지: autoGenerateDailyReport (기존)
 *  → 주간일지: 해당 주 첫 배치 → autoGenerateWeeklyLog
 *  → 월간일지: 해당 월 첫 배치 → autoGenerateMonthlyLog
 *  → 연간일지: 연간 첫 작성일 기준 → autoGenerateYearlyLog
 *
 * 수동 배치 생성 시 (manual mode)
 *  → 기간별 일지 자동 생성 안 함 → 수동 작성
 *
 * 휴무 관리 (h_holidays) 연동:
 *  → 주간/월간 "첫 배치"는 h_holidays를 제외한 첫 영업일 배치
 *  → 이미 해당 기간에 일지가 있으면 skip
 * ─────────────────────────────────────────────
 */

import { getDb, getRawConnection } from "../db";
import { sql } from "drizzle-orm";

export interface PeriodicLogResult {
  success: boolean;
  logType: "weekly" | "monthly" | "yearly";
  recordId: number | null;
  approvalRequestId: number | null;
  isNew: boolean;
  message: string;
}

// ============================================================================
// 주간일지 자동 생성
// ============================================================================

/**
 * 해당 주의 첫 배치인지 확인 후 주간일지 자동 생성
 * - h_holidays 연동: 주의 첫 영업일 배치에서만 생성
 * - weekly_hygiene_logs + h_approval_requests에 등록
 */
export async function autoGenerateWeeklyLog(
  tenantId: number,
  siteId: number,
  workDate: string,
  userId: number,
  batchInfo?: { batchId: number; productName: string; plannedQty: number }
): Promise<PeriodicLogResult> {
  const conn = await getRawConnection();

  try {
    // 1. 해당 주의 월~일 범위 계산
    const { weekStart, weekEnd } = getWeekRange(workDate);

    // 2. 이미 해당 주에 주간일지가 있으면 skip
    const [existingRows] = await conn.execute<any[]>(
      `SELECT id FROM weekly_hygiene_logs
       WHERE tenant_id = ? AND check_date BETWEEN ? AND ?
       LIMIT 1`,
      [tenantId, weekStart, weekEnd]
    );
    if ((existingRows as any[]).length > 0) {
      return {
        success: true, logType: "weekly",
        recordId: (existingRows as any[])[0].id,
        approvalRequestId: null, isNew: false,
        message: `주간일지 이미 존재 (ID: ${(existingRows as any[])[0].id})`,
      };
    }

    // 3. 해당 주에 이전 배치가 있었는지 확인 (현재가 첫 배치인지)
    const isFirst = await isFirstBatchOfPeriod(conn, tenantId, weekStart, workDate);
    if (!isFirst) {
      return {
        success: true, logType: "weekly",
        recordId: null, approvalRequestId: null, isNew: false,
        message: `이번 주 첫 배치가 아니므로 주간일지 미생성`,
      };
    }

    // 4. 주간일지 생성 (weekly_hygiene_logs) - status 컬럼은 DB default('작성중') 사용
    const [insertResult] = await conn.execute<any>(
      `INSERT INTO weekly_hygiene_logs
        (tenant_id, check_date, checker_name, special_notes)
       VALUES (?, ?, ?, ?)`,
      [
        tenantId,
        workDate,
        "", // checker_name: 추후 검토자가 작성
        batchInfo
          ? `[자동생성] 주간점검 - 배치: ${batchInfo.productName} (${batchInfo.plannedQty}kg)`
          : `[자동생성] 주간점검`,
      ]
    );
    const recordId = (insertResult as any).insertId;

    // 4.5. 주간 방충방서 일지도 함께 생성 (weekly_pest_logs)
    try {
      await conn.execute(
        `INSERT INTO weekly_pest_logs
          (tenant_id, check_date, management_notes)
         VALUES (?, ?, ?)`,
        [
          tenantId,
          workDate,
          batchInfo
            ? `[자동생성] 주간 방충방서 점검 - 배치: ${batchInfo.productName}`
            : `[자동생성] 주간 방충방서 점검`,
        ]
      );
    } catch (pestErr) {
      console.error("[autoPeriodicLogs] 주간 방충방서 일지 생성 실패:", pestErr);
    }

    // 5. 승인요청 등록 (h_approval_requests)
    const approvalTitle = `[주간일지] ${weekStart} ~ ${weekEnd} 주간 위생점검`;
    const approvalDesc =
      `점검기간: ${weekStart} ~ ${weekEnd}\n` +
      `점검일: ${workDate}\n` +
      `[자동생성 - 위생점검 항목을 작성해주세요]`;

    const [approvalResult] = await conn.execute<any>(
      `INSERT INTO h_approval_requests
        (site_id, tenant_id, request_type, reference_type, reference_id,
         title, description, status, priority, requested_by, created_at)
       VALUES (?, ?, 'weekly_log', 'weekly_hygiene', ?, ?, ?, 'pending_review', 'medium', ?, NOW())`,
      [siteId, tenantId, recordId, approvalTitle, approvalDesc, userId]
    );
    const approvalRequestId = (approvalResult as any).insertId;

    console.log(`[autoPeriodicLogs] 주간일지 생성: #${recordId}, 승인요청: #${approvalRequestId}`);

    return {
      success: true, logType: "weekly",
      recordId, approvalRequestId, isNew: true,
      message: `주간일지 자동 생성 완료 (#${recordId})`,
    };
  } catch (error: any) {
    console.error("[autoPeriodicLogs] 주간일지 생성 실패:", error);
    return {
      success: false, logType: "weekly",
      recordId: null, approvalRequestId: null, isNew: false,
      message: error.message || "주간일지 생성 실패",
    };
  }
}

// ============================================================================
// 월간일지 자동 생성
// ============================================================================

/**
 * 해당 월의 첫 배치인지 확인 후 월간일지 자동 생성
 * - monthly_hygiene_logs + monthly_ccp_logs 모두 생성
 * - h_approval_requests에 등록
 */
export async function autoGenerateMonthlyLog(
  tenantId: number,
  siteId: number,
  workDate: string,
  userId: number,
  batchInfo?: { batchId: number; productName: string; plannedQty: number }
): Promise<PeriodicLogResult> {
  const conn = await getRawConnection();

  try {
    // 1. 해당 월의 1일~말일 범위
    const { monthStart, monthEnd } = getMonthRange(workDate);

    // 2. 이미 해당 월에 월간일지가 있으면 skip
    const [existingHygiene] = await conn.execute<any[]>(
      `SELECT id FROM monthly_hygiene_logs
       WHERE tenant_id = ? AND check_date BETWEEN ? AND ?
       LIMIT 1`,
      [tenantId, monthStart, monthEnd]
    );
    if ((existingHygiene as any[]).length > 0) {
      return {
        success: true, logType: "monthly",
        recordId: (existingHygiene as any[])[0].id,
        approvalRequestId: null, isNew: false,
        message: `월간일지 이미 존재`,
      };
    }

    // 3. 해당 월 첫 배치 확인
    const isFirst = await isFirstBatchOfPeriod(conn, tenantId, monthStart, workDate);
    if (!isFirst) {
      return {
        success: true, logType: "monthly",
        recordId: null, approvalRequestId: null, isNew: false,
        message: `이번 달 첫 배치가 아니므로 월간일지 미생성`,
      };
    }

    const yearMonth = workDate.substring(0, 7); // "YYYY-MM"

    // 4-A. 월간 위생관리 일지 생성
    const [hygieneResult] = await conn.execute<any>(
      `INSERT INTO monthly_hygiene_logs
        (tenant_id, check_date, special_notes)
       VALUES (?, ?, ?)`,
      [
        tenantId,
        workDate,
        batchInfo
          ? `[자동생성] ${yearMonth} 월간 위생점검 - 배치: ${batchInfo.productName}`
          : `[자동생성] ${yearMonth} 월간 위생점검`,
      ]
    );
    const hygieneId = (hygieneResult as any).insertId;

    // 4-B. 월간 CCP 검증점검표 생성
    const [ccpResult] = await conn.execute<any>(
      `INSERT INTO monthly_ccp_logs
        (tenant_id, check_date, deviation_details)
       VALUES (?, ?, ?)`,
      [
        tenantId,
        workDate,
        `[자동생성] ${yearMonth} CCP 검증점검`,
      ]
    );
    const ccpId = (ccpResult as any).insertId;

    // 5. h_monthly_reports 통계 기록
    const [reportYear, reportMonth] = workDate.split("-").map(Number);
    await conn.execute(
      `INSERT INTO h_monthly_reports
        (site_id, report_year, report_month, report_type, summary, generated_by, tenant_id)
       VALUES (?, ?, ?, 'production', ?, ?, ?)
       ON DUPLICATE KEY UPDATE summary = VALUES(summary)`,
      [
        siteId,
        reportYear,
        reportMonth,
        JSON.stringify({
          hygieneLogId: hygieneId,
          ccpLogId: ccpId,
          autoGenerated: true,
          generatedAt: new Date().toISOString(),
        }),
        userId,
        tenantId,
      ]
    );

    // 6. 승인요청 등록
    const approvalTitle = `[월간일지] ${yearMonth} 월간 위생/CCP 점검`;
    const approvalDesc =
      `점검월: ${yearMonth}\n` +
      `위생관리 일지: #${hygieneId}\n` +
      `CCP 검증 일지: #${ccpId}\n` +
      `[자동생성 - 점검 항목을 작성해주세요]`;

    const [approvalResult] = await conn.execute<any>(
      `INSERT INTO h_approval_requests
        (site_id, tenant_id, request_type, reference_type, reference_id,
         title, description, status, priority, requested_by, created_at)
       VALUES (?, ?, 'monthly_log', 'monthly_hygiene', ?, ?, ?, 'pending_review', 'medium', ?, NOW())`,
      [siteId, tenantId, hygieneId, approvalTitle, approvalDesc, userId]
    );
    const approvalRequestId = (approvalResult as any).insertId;

    console.log(`[autoPeriodicLogs] 월간일지 생성: 위생 #${hygieneId}, CCP #${ccpId}, 승인요청: #${approvalRequestId}`);

    return {
      success: true, logType: "monthly",
      recordId: hygieneId, approvalRequestId, isNew: true,
      message: `월간일지 자동 생성 완료 (위생 #${hygieneId}, CCP #${ccpId})`,
    };
  } catch (error: any) {
    console.error("[autoPeriodicLogs] 월간일지 생성 실패:", error);
    return {
      success: false, logType: "monthly",
      recordId: null, approvalRequestId: null, isNew: false,
      message: error.message || "월간일지 생성 실패",
    };
  }
}

// ============================================================================
// 연간일지 자동 생성
// ============================================================================

/**
 * 연간일지 자동 생성
 * - 매년 첫 작성일로부터 연간 단위
 * - 미작성 시 관리 이후부터 카운팅
 * - yearly_logs + h_approval_requests
 */
export async function autoGenerateYearlyLog(
  tenantId: number,
  siteId: number,
  workDate: string,
  userId: number,
): Promise<PeriodicLogResult> {
  const conn = await getRawConnection();

  try {
    const year = Number(workDate.split("-")[0]);
    const yearStart = `${year}-01-01`;
    const yearEnd = `${year}-12-31`;

    // 1. 올해 연간일지가 이미 있으면 skip
    const [existingRows] = await conn.execute<any[]>(
      `SELECT id FROM yearly_logs
       WHERE tenant_id = ? AND inspection_date BETWEEN ? AND ?
       LIMIT 1`,
      [tenantId, yearStart, yearEnd]
    );
    if ((existingRows as any[]).length > 0) {
      return {
        success: true, logType: "yearly",
        recordId: (existingRows as any[])[0].id,
        approvalRequestId: null, isNew: false,
        message: `${year}년 연간일지 이미 존재`,
      };
    }

    // 2. 연간 첫 작성일 기준 확인: 최초 연간일지 기록이 있는지
    const [firstEverRows] = await conn.execute<any[]>(
      `SELECT MIN(inspection_date) as first_date FROM yearly_logs WHERE tenant_id = ?`,
      [tenantId]
    );
    const firstEverDate = (firstEverRows as any[])[0]?.first_date;

    // 첫 기록이 있으면 해당 기록 이후 1년 단위로 체크
    // 첫 기록이 없으면 올해를 기준년으로 설정
    let shouldCreate = false;

    if (!firstEverDate) {
      // 아직 연간일지가 한 건도 없음 → 올해 첫 배치에서 생성
      shouldCreate = true;
    } else {
      // 최초 작성일로부터 연간 단위 체크
      const firstYear = typeof firstEverDate === 'string'
        ? Number(firstEverDate.substring(0, 4))
        : new Date(firstEverDate).getFullYear();
      const yearsDiff = year - firstYear;
      // 올해 일지가 없으면 (위에서 이미 체크) → 생성
      shouldCreate = yearsDiff >= 1 || firstYear === year;
    }

    if (!shouldCreate) {
      return {
        success: true, logType: "yearly",
        recordId: null, approvalRequestId: null, isNew: false,
        message: `연간일지 생성 조건 미충족`,
      };
    }

    // 3. 올해 첫 배치인지 확인
    const [batchesThisYear] = await conn.execute<any[]>(
      `SELECT COUNT(*) as cnt FROM h_batches
       WHERE tenant_id = ? AND planned_date BETWEEN ? AND ? AND planned_date < ?`,
      [tenantId, yearStart, yearEnd, workDate]
    );
    const priorBatchCount = Number((batchesThisYear as any[])[0]?.cnt || 0);
    if (priorBatchCount > 0) {
      // 올해 이전에 이미 배치가 있었는데 연간일지가 없음 → 지금 생성 (미작성 보완)
      console.log(`[autoPeriodicLogs] 올해 이전 배치 ${priorBatchCount}건 있었으나 연간일지 미작성 → 지금 생성`);
    }

    // 4. 연간일지 생성
    const [insertResult] = await conn.execute<any>(
      `INSERT INTO yearly_logs
        (tenant_id, site_id, inspection_date, inspector, special_notes, status, created_by)
       VALUES (?, ?, ?, ?, ?, '작성중', ?)`,
      [
        tenantId,
        siteId,
        workDate,
        "", // inspector: 추후 작성
        `[자동생성] ${year}년 연간 검교정 점검 - 미작성 항목을 작성해주세요`,
        userId,
      ]
    );
    const recordId = (insertResult as any).insertId;

    // 5. 승인요청 등록
    const approvalTitle = `[연간일지] ${year}년 연간 검교정 점검`;
    const approvalDesc =
      `점검년도: ${year}\n` +
      `작성일: ${workDate}\n` +
      `[자동생성 - 검교정 점검 항목을 작성해주세요]`;

    const [approvalResult] = await conn.execute<any>(
      `INSERT INTO h_approval_requests
        (site_id, tenant_id, request_type, reference_type, reference_id,
         title, description, status, priority, requested_by, created_at)
       VALUES (?, ?, 'yearly_log', 'yearly', ?, ?, ?, 'pending_review', 'medium', ?, NOW())`,
      [siteId, tenantId, recordId, approvalTitle, approvalDesc, userId]
    );
    const approvalRequestId = (approvalResult as any).insertId;

    console.log(`[autoPeriodicLogs] 연간일지 생성: #${recordId}, 승인요청: #${approvalRequestId}`);

    return {
      success: true, logType: "yearly",
      recordId, approvalRequestId, isNew: true,
      message: `${year}년 연간일지 자동 생성 완료 (#${recordId})`,
    };
  } catch (error: any) {
    console.error("[autoPeriodicLogs] 연간일지 생성 실패:", error);
    return {
      success: false, logType: "yearly",
      recordId: null, approvalRequestId: null, isNew: false,
      message: error.message || "연간일지 생성 실패",
    };
  }
}

// ============================================================================
// 통합 자동 기간별 일지 생성 (배치 auto 모드에서 호출)
// ============================================================================

export interface AllPeriodicLogsResult {
  weekly: PeriodicLogResult;
  monthly: PeriodicLogResult;
  yearly: PeriodicLogResult;
}

/**
 * 자동 배치 생성 시 주간/월간/연간 일지 일괄 확인 및 생성
 * @param mode "auto" 일 때만 실행, "manual"이면 skip
 */
export async function autoGenerateAllPeriodicLogs(
  mode: "auto" | "manual",
  tenantId: number,
  siteId: number,
  workDate: string,
  userId: number,
  batchInfo?: { batchId: number; productName: string; plannedQty: number }
): Promise<AllPeriodicLogsResult | null> {
  // 수동 모드에서는 기간별 일지 자동 생성 안 함
  if (mode === "manual") {
    console.log("[autoPeriodicLogs] 수동 배치 모드 → 기간별 일지 자동 생성 skip");
    return null;
  }

  // workDate 유효성 검증
  if (!workDate || !/^\d{4}-\d{2}-\d{2}$/.test(workDate)) {
    console.error(`[autoPeriodicLogs] 유효하지 않은 workDate: ${workDate}`);
    return null;
  }

  console.log(`[autoPeriodicLogs] 자동 배치 모드 → 주간/월간/연간 일지 확인 (${workDate})`);

  const [weekly, monthly, yearly] = await Promise.allSettled([
    autoGenerateWeeklyLog(tenantId, siteId, workDate, userId, batchInfo),
    autoGenerateMonthlyLog(tenantId, siteId, workDate, userId, batchInfo),
    autoGenerateYearlyLog(tenantId, siteId, workDate, userId),
  ]);

  const result: AllPeriodicLogsResult = {
    weekly: weekly.status === "fulfilled" ? weekly.value : {
      success: false, logType: "weekly", recordId: null, approvalRequestId: null, isNew: false,
      message: (weekly as PromiseRejectedResult).reason?.message || "주간일지 생성 실패",
    },
    monthly: monthly.status === "fulfilled" ? monthly.value : {
      success: false, logType: "monthly", recordId: null, approvalRequestId: null, isNew: false,
      message: (monthly as PromiseRejectedResult).reason?.message || "월간일지 생성 실패",
    },
    yearly: yearly.status === "fulfilled" ? yearly.value : {
      success: false, logType: "yearly", recordId: null, approvalRequestId: null, isNew: false,
      message: (yearly as PromiseRejectedResult).reason?.message || "연간일지 생성 실패",
    },
  };

  const newLogs = [result.weekly, result.monthly, result.yearly].filter(r => r.isNew);
  if (newLogs.length > 0) {
    console.log(`[autoPeriodicLogs] 기간별 일지 ${newLogs.length}건 신규 생성: ${newLogs.map(l => l.logType).join(", ")}`);
  }

  return result;
}

// ============================================================================
// 유틸리티 함수
// ============================================================================

/** 월요일~일요일 주 범위 계산 (ISO 주 기준) — timezone-safe */
function getWeekRange(dateStr: string): { weekStart: string; weekEnd: string } {
  // dateStr = "YYYY-MM-DD" → parse parts directly to avoid UTC/local timezone issues
  const [y, m, dd] = dateStr.split("-").map(Number);
  const d = new Date(y, m - 1, dd); // local date
  const day = d.getDay(); // 0=Sun, 1=Mon, ...
  const diffToMon = day === 0 ? -6 : 1 - day;
  const monday = new Date(y, m - 1, dd + diffToMon);
  const sunday = new Date(monday.getFullYear(), monday.getMonth(), monday.getDate() + 6);
  return {
    weekStart: formatLocalDate(monday),
    weekEnd: formatLocalDate(sunday),
  };
}

/** 월 범위 계산 — timezone-safe */
function getMonthRange(dateStr: string): { monthStart: string; monthEnd: string } {
  const [y, m] = dateStr.split("-").map(Number);
  const first = new Date(y, m - 1, 1);   // local: first day of month
  const last = new Date(y, m, 0);         // local: last day of month
  return {
    monthStart: formatLocalDate(first),
    monthEnd: formatLocalDate(last),
  };
}

/** YYYY-MM-DD 포맷 (local timezone) */
function formatLocalDate(d: Date): string {
  const yyyy = d.getFullYear();
  const mm = String(d.getMonth() + 1).padStart(2, "0");
  const dd = String(d.getDate()).padStart(2, "0");
  return `${yyyy}-${mm}-${dd}`;
}

/**
 * 해당 기간(periodStart ~ workDate) 내에 이전 배치가 있었는지 확인
 * → h_holidays 연동: 공휴일/휴무일 배치는 제외하고 판단
 */
async function isFirstBatchOfPeriod(
  conn: any,
  tenantId: number,
  periodStart: string,
  workDate: string,
): Promise<boolean> {
  // workDate 이전에 해당 기간 내 배치가 있었는지 확인
  const [priorBatches] = await (conn as any).execute(
    `SELECT COUNT(*) as cnt FROM h_batches
     WHERE tenant_id = ?
       AND planned_date >= ?
       AND planned_date < ?`,
    [tenantId, periodStart, workDate]
  );
  const priorCount = Number((priorBatches as any[])[0]?.cnt || 0);

  // 이전 배치가 없으면 → 첫 배치
  if (priorCount === 0) return true;

  // 이전 배치가 있지만 모두 휴무일(h_holidays)이었으면 → 영업일 기준 첫 배치
  const [holidayBatches] = await (conn as any).execute(
    `SELECT COUNT(*) as cnt FROM h_batches b
     INNER JOIN h_holidays h ON h.holiday_date = b.planned_date AND h.tenant_id = b.tenant_id
     WHERE b.tenant_id = ?
       AND b.planned_date >= ?
       AND b.planned_date < ?`,
    [tenantId, periodStart, workDate]
  );
  const holidayCount = Number((holidayBatches as any[])[0]?.cnt || 0);

  // 모든 이전 배치가 휴무일 배치면 → 오늘이 실질적 첫 영업일 배치
  return holidayCount >= priorCount;
}
