/**
 * ChecklistDashboard 분해 — 항목별 일지 카테고리 정의 (PDF 양식 기반 매칭).
 * 정적 카테고리+아이템 설정 데이터.
 */
import {
  AlertTriangle, Bug, Building, Building2, ClipboardCheck, Cog, Droplet, Droplets,
  FileCheck, FileText, Filter, FlaskConical, FolderOpen, Gauge, GraduationCap,
  Handshake, HeartPulse, MessageSquareWarning, Microscope, Package, Scale,
  ShieldCheck, Sparkles, Sun, Thermometer, ThermometerSun, Trash, Trash2, Truck,
  UserCheck, Wrench, Zap,
} from "lucide-react";

export const checklistCategories = [
  {
    id: "hygiene",
    title: "위생 관리",
    description: "개인위생, 종사자 건강, 세척·소독, 표면오염도, 위생시설, 작업장위생",
    icon: Droplet,
    color: "text-purple-600",
    bgColor: "bg-purple-50",
    filterLabel: "위생",
    items: [
      {
        id: "personal-hygiene",
        title: "개인 위생관리 점검표",
        description: "종사자 개인위생 상태를 점검합니다",
        icon: UserCheck,
        listPath: "/personal-hygiene-check",
        createPath: "/personal-hygiene-check/new",
      },
      {
        id: "employee-health",
        title: "종사자 건강상태 확인 일지",
        description: "작업장 출입 전 종사자 건강상태를 확인합니다",
        icon: HeartPulse,
        listPath: "/employee-health-check",
        createPath: "/employee-health-check/new",
      },
      {
        id: "sanitation",
        title: "세척소독 관리대장",
        description: "세척·소독 제품 및 사용 기록을 관리합니다",
        icon: Sparkles,
        listPath: "/sanitation-record",
        createPath: "/sanitation-record/new",
      },
      {
        id: "surface-contamination",
        title: "표면오염도 검사 성적서",
        description: "표면오염도 검사 결과를 기록합니다",
        icon: Microscope,
        listPath: "/surface-contamination-test",
        createPath: "/surface-contamination-test/new",
      },
      {
        id: "health-certificates",
        title: "건강진단결과서 관리",
        description: "건강진단결과서(구, 보건증) 현황 및 만료 임박 현황",
        icon: FileCheck,
        listPath: "/dashboard/checklist/employee-health",
        createPath: "/dashboard/checklist/employee-health",
      },
      {
        id: "hygiene-facility",
        title: "위생시설 점검일지",
        description: "위생시설의 상태를 점검합니다",
        icon: Building2,
        listPath: "/hygiene-facility-check",
        createPath: "/hygiene-facility-check/new",
      },
      {
        id: "workplace-hygiene",
        title: "작업장 위생관리 점검표",
        description: "작업장 전반의 위생 상태를 점검합니다",
        icon: ClipboardCheck,
        listPath: "/workplace-hygiene-check",
        createPath: "/workplace-hygiene-check/new",
      },
    ],
  },
  {
    id: "facility",
    title: "시설·설비 관리",
    description: "온·습도, 냉장·냉동 온도, 필터, 조도, 차량온도, 설비이력, 설비점검",
    icon: Thermometer,
    color: "text-blue-600",
    bgColor: "bg-blue-50",
    filterLabel: "시설",
    items: [
      {
        id: "temperature-humidity",
        title: "온·습도 점검표",
        description: "각 공간의 온·습도를 점검합니다",
        icon: ThermometerSun,
        listPath: "/temperature-humidity-check",
        createPath: "/temperature-humidity-check/new",
      },
      {
        id: "cold-storage-temperature",
        title: "냉장·냉동창고 자동온도 기록지",
        description: "냉장·냉동창고의 온도를 기록합니다",
        icon: Thermometer,
        listPath: "/refrigeration-check",
        createPath: "/refrigeration-check/new",
      },
      {
        id: "filter-management",
        title: "압축공기 필터·에어컨 필터 관리대장",
        description: "압축공기 및 에어컨 필터를 관리합니다",
        icon: Filter,
        listPath: "/air-compressor",
        createPath: "/air-compressor/new",
      },
      {
        id: "illumination",
        title: "조도점검표",
        description: "작업장 조도를 점검합니다",
        icon: Sun,
        listPath: "/illumination-check",
        createPath: "/illumination-check/new",
      },
      {
        id: "vehicle-temperature",
        title: "입·출고 차량 온도기록지",
        description: "입·출고 차량의 온도를 기록합니다",
        icon: Truck,
        listPath: "/vehicle-temperature-check",
        createPath: "/vehicle-temperature-check/new",
      },
      {
        id: "equipment-history",
        title: "시설·설비 이력카드",
        description: "시설·설비의 이력을 관리합니다",
        icon: Cog,
        listPath: "/equipment-history",
        createPath: "/equipment-history/new",
      },
      {
        id: "equipment-inspection",
        title: "시설·설비·제조도구 점검표",
        description: "시설·설비·제조도구를 점검합니다",
        icon: Wrench,
        listPath: "/equipment-inspection",
        createPath: "/equipment-inspection/new",
      },
      {
        id: "air-compressor-maintenance",
        title: "에어콤프레샤 관리일지",
        description: "에어 콤프레샤 윤활유 교환 및 에어 크리너 세척/소독을 기록합니다",
        icon: Cog,
        listPath: "/air-compressor-maintenance",
        createPath: "/air-compressor-maintenance/new",
      },
    ],
  },
  {
    id: "quality",
    title: "품질·시정·교육",
    description: "부적합품 관리, 검교정, 교육훈련, 소비자불만",
    icon: AlertTriangle,
    color: "text-red-600",
    bgColor: "bg-red-50",
    filterLabel: "품질",
    items: [
      {
        id: "nonconformance",
        title: "부적합품 관리 점검표",
        description: "부적합품 발생 및 처리를 관리합니다",
        icon: AlertTriangle,
        listPath: "/quality-issue-record",
        createPath: "/quality-issue-record/new",
      },
      {
        id: "calibration",
        title: "검교정 관리",
        description: "계측기기 검교정을 관리합니다",
        icon: Gauge,
        listPath: "/calibration",
        createPath: "/calibration",
      },
      {
        id: "training-log",
        title: "교육훈련일지",
        description: "교육훈련 기록을 관리합니다",
        icon: GraduationCap,
        listPath: "/training-log",
        createPath: "/training-log/new",
      },
      {
        id: "consumer-complaint",
        title: "소비자 불만 관리 일지",
        description: "소비자 불만 접수 및 처리를 관리합니다",
        icon: MessageSquareWarning,
        listPath: "/consumer-complaint",
        createPath: "/consumer-complaint/new",
      },
    ],
  },
  {
    id: "inspection",
    title: "검사·성적·품질보증",
    description: "자가품질검사, 중량·품질검사, 제품검사, 완제품출고검사, 협력업체점검",
    icon: FlaskConical,
    color: "text-green-600",
    bgColor: "bg-green-50",
    filterLabel: "검사",
    items: [
      {
        id: "self-inspection",
        title: "자가품질검사",
        description: "자가품질검사 기록을 관리합니다",
        icon: FlaskConical,
        listPath: "/quality/self-inspection",
        createPath: "/quality/self-inspection/new",
      },
      {
        id: "weight-quality",
        title: "중량 및 품질 검사 일지",
        description: "중량 및 품질 검사를 기록합니다",
        icon: Scale,
        listPath: "/weight-quality-check",
        createPath: "/weight-quality-check/new",
      },
      {
        id: "product-test-report",
        title: "제품검사 성적서",
        description: "제품검사 성적서를 관리합니다",
        icon: FileCheck,
        listPath: "/product-test-report",
        createPath: "/product-test-report/new",
      },
      {
        id: "product-test-log",
        title: "제품 검사 일지",
        description: "제품 검사 일지를 기록합니다",
        icon: FileText,
        listPath: "/product-test-log",
        createPath: "/product-test-log/new",
      },
      {
        id: "finished-product",
        title: "완제품 출고검사 일지",
        description: "완제품 출고 시 검사를 기록합니다",
        icon: Package,
        listPath: "/finished-product-check",
        createPath: "/finished-product-check/new",
      },
      {
        id: "supplier-inspection",
        title: "협력업체 점검표",
        description: "협력업체를 점검합니다",
        icon: Handshake,
        listPath: "/supplier-inspection",
        createPath: "/supplier-inspection/new",
      },
    ],
  },
  {
    id: "pest-control",
    title: "방충·방서 관리",
    description: "방충·방서 점검, 공중낙하세균 검사, 식품회수",
    icon: Bug,
    color: "text-amber-600",
    bgColor: "bg-amber-50",
    filterLabel: "방충",
    items: [
      {
        id: "pest-control-checklist",
        title: "방충·방서 점검표",
        description: "방충·방서 상태를 점검합니다",
        icon: Bug,
        listPath: "/pest-control/checklists",
        createPath: "/pest-control/checklists/new",
      },
      {
        id: "airborne-bacteria",
        title: "공중낙하세균 검사 성적서",
        description: "공중낙하세균 검사 결과를 기록합니다",
        icon: Zap,
        listPath: "/airborne-bacteria-test",
        createPath: "/airborne-bacteria-test/new",
      },
      {
        id: "food-recall",
        title: "식품 회수 안내문",
        description: "식품 회수 안내문을 관리합니다",
        icon: ShieldCheck,
        listPath: "/food-recall-notice",
        createPath: "/food-recall-notice/new",
      },
    ],
  },
  {
    id: "water",
    title: "용수 관리",
    description: "용수검사 성적서, 용수관리 점검표",
    icon: Droplets,
    color: "text-cyan-600",
    bgColor: "bg-cyan-50",
    filterLabel: "용수",
    items: [
      {
        id: "water-quality-test",
        title: "용수검사 성적서",
        description: "용수검사 결과를 관리합니다",
        icon: Droplets,
        listPath: "/water-quality-test",
        createPath: "/water-quality-test/new",
      },
      {
        id: "water-management",
        title: "용수관리 점검표",
        description: "용수 관리 상태를 점검합니다",
        icon: Droplet,
        listPath: "/water-management-check",
        createPath: "/water-management-check/new",
      },
    ],
  },
  {
    id: "document",
    title: "문서·기록·기타",
    description: "업무인수인계서, 보건증 관리, 일일 폐기 기록",
    icon: FolderOpen,
    color: "text-indigo-600",
    bgColor: "bg-indigo-50",
    filterLabel: "문서",
    items: [
      {
        id: "handover-document",
        title: "업무 인수인계서",
        description: "업무 인수인계 기록을 관리합니다",
        icon: FolderOpen,
        listPath: "/handover-document",
        createPath: "/handover-document/new",
      },
      {
        id: "waste-disposal-record",
        title: "일일 폐기 기록",
        description: "일일 폐기 기록을 관리합니다",
        icon: Trash2,
        listPath: "/daily-disposal-record",
        createPath: "/daily-disposal-record/new",
      },
      {
        id: "waste-management",
        title: "폐기물 관리대장",
        description: "폐기물 발생량, 자가처리, 재활용 현황을 기록합니다",
        icon: Trash2,
        listPath: "/waste-management",
        createPath: "/waste-management/new",
      },
    ],
  },
];
